module.exports = {
    content: [
        './src/lib/**/*.{html,js,svelte,ts}',
        './src/routes/**/*.{html,js,svelte,ts}',
        './node_modules/@graphace/ui/dist/**/*.{html,js,svelte,ts}',
        './node_modules/@graphace/ui-graphql/dist/**/*.{html,js,svelte,ts}'
    ],
    plugins: [
        require('@tailwindcss/typography'),
        require('daisyui')
    ],
    daisyui: {
        themes: [
            "light",
            "dark",
            "cupcake",
            "bumblebee",
            "emerald",
            "corporate",
            "synthwave",
            "retro",
            "cyberpunk",
            "valentine",
            "halloween",
            "garden",
            "forest",
            "aqua",
            "lofi",
            "pastel",
            "fantasy",
            "wireframe",
            "black",
            "luxury",
            "dracula",
            "cmyk",
            "autumn",
            "business",
            "acid",
            "lemonade",
            "night",
            "coffee",
            "winter",
        ],
    },
}
