query PermissionTypesQuery($type: StringExpression, $first: Int, $offset: Int) {
	permissionConnection(type: $type, first: $first, offset: $offset, groupBy: ["type"]) {
		totalCount
		edges {
			node {
				type
			}
		}
	}
}
