// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * Welcome to Svelte Fall Summit {year}
	 * @param {number} year
	 */
	HI: RequiredParams<'year'>
	localeName: {
		/**
		 * English
		 */
		en: string
		/**
		 * Chinese
		 */
		zh: string
	}
	message: {
		/**
		 * Save success
		 */
		saveSuccess: string
		/**
		 * Create Success
		 */
		createSuccess: string
		/**
		 * Delete Success
		 */
		deleteSuccess: string
		/**
		 * Request failed
		 */
		requestFailed: string
		/**
		 * Save failed
		 */
		saveFailed: string
		/**
		 * Create failed
		 */
		createFailed: string
		/**
		 * Delete failed
		 */
		deleteFailed: string
	}
	components: {
		messageBox: {
			/**
			 * Cancel
			 */
			cancel: string
			/**
			 * Confirm
			 */
			confirm: string
		}
		ui: {
			cursor: {
				/**
				 * size
				 */
				size: string
				/**
				 * Previous
				 */
				previous: string
				/**
				 * Next
				 */
				next: string
			}
			pagination: {
				/**
				 * size
				 */
				size: string
				/**
				 * {total} results
				 * @param {number} total
				 */
				total: RequiredParams<'total'>
				/**
				 * Page {current}
				 * @param {number} current
				 */
				current: RequiredParams<'current'>
				/**
				 * Previous
				 */
				previous: string
				/**
				 * Next
				 */
				next: string
			}
			searchInput: {
				/**
				 * Search
				 */
				placeholder: string
			}
		}
		graphql: {
			editor: {
				/**
				 * Save
				 */
				saveBtn: string
				/**
				 * Delete
				 */
				deleteBtn: string
				/**
				 * Back
				 */
				backBtn: string
			}
			table: {
				/**
				 * Delete row?
				 */
				deleteModalTitle: string
				/**
				 * Edit
				 */
				editBtn: string
				/**
				 * Delete
				 */
				deleteBtn: string
				/**
				 * Cancel
				 */
				cancelBtn: string
				th: {
					/**
					 * filter
					 */
					filter: string
					/**
					 * cancel
					 */
					cancel: string
					/**
					 * No Sort
					 */
					noSort: string
					/**
					 * ASC
					 */
					asc: string
					/**
					 * DESC
					 */
					desc: string
					/**
					 * Equals
					 */
					eq: string
					/**
					 * Not Equals
					 */
					neq: string
					/**
					 * Like
					 */
					lk: string
					/**
					 * Not Like
					 */
					nlk: string
					/**
					 * Greater Than
					 */
					gt: string
					/**
					 * Greater Equals
					 */
					gte: string
					/**
					 * Less Than
					 */
					lt: string
					/**
					 * Less Equals
					 */
					lte: string
					/**
					 * Is Null
					 */
					nil: string
					/**
					 * Not Null
					 */
					nnil: string
					/**
					 * In
					 */
					'in': string
					/**
					 * Not In
					 */
					nin: string
					/**
					 * Filter..
					 */
					filterPlaceholder: string
				}
				td: {
					/**
					 * save
					 */
					save: string
					/**
					 * clear
					 */
					clear: string
				}
			}
		}
		routers: {
			type: {
				/**
				 * Create
				 */
				create: string
			}
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Welcome to Svelte Fall Summit {year}
	 */
	HI: (arg: { year: number }) => LocalizedString
	localeName: {
		/**
		 * English
		 */
		en: () => LocalizedString
		/**
		 * Chinese
		 */
		zh: () => LocalizedString
	}
	message: {
		/**
		 * Save success
		 */
		saveSuccess: () => LocalizedString
		/**
		 * Create Success
		 */
		createSuccess: () => LocalizedString
		/**
		 * Delete Success
		 */
		deleteSuccess: () => LocalizedString
		/**
		 * Request failed
		 */
		requestFailed: () => LocalizedString
		/**
		 * Save failed
		 */
		saveFailed: () => LocalizedString
		/**
		 * Create failed
		 */
		createFailed: () => LocalizedString
		/**
		 * Delete failed
		 */
		deleteFailed: () => LocalizedString
	}
	components: {
		messageBox: {
			/**
			 * Cancel
			 */
			cancel: () => LocalizedString
			/**
			 * Confirm
			 */
			confirm: () => LocalizedString
		}
		ui: {
			cursor: {
				/**
				 * size
				 */
				size: () => LocalizedString
				/**
				 * Previous
				 */
				previous: () => LocalizedString
				/**
				 * Next
				 */
				next: () => LocalizedString
			}
			pagination: {
				/**
				 * size
				 */
				size: () => LocalizedString
				/**
				 * {total} results
				 */
				total: (arg: { total: number }) => LocalizedString
				/**
				 * Page {current}
				 */
				current: (arg: { current: number }) => LocalizedString
				/**
				 * Previous
				 */
				previous: () => LocalizedString
				/**
				 * Next
				 */
				next: () => LocalizedString
			}
			searchInput: {
				/**
				 * Search
				 */
				placeholder: () => LocalizedString
			}
		}
		graphql: {
			editor: {
				/**
				 * Save
				 */
				saveBtn: () => LocalizedString
				/**
				 * Delete
				 */
				deleteBtn: () => LocalizedString
				/**
				 * Back
				 */
				backBtn: () => LocalizedString
			}
			table: {
				/**
				 * Delete row?
				 */
				deleteModalTitle: () => LocalizedString
				/**
				 * Edit
				 */
				editBtn: () => LocalizedString
				/**
				 * Delete
				 */
				deleteBtn: () => LocalizedString
				/**
				 * Cancel
				 */
				cancelBtn: () => LocalizedString
				th: {
					/**
					 * filter
					 */
					filter: () => LocalizedString
					/**
					 * cancel
					 */
					cancel: () => LocalizedString
					/**
					 * No Sort
					 */
					noSort: () => LocalizedString
					/**
					 * ASC
					 */
					asc: () => LocalizedString
					/**
					 * DESC
					 */
					desc: () => LocalizedString
					/**
					 * Equals
					 */
					eq: () => LocalizedString
					/**
					 * Not Equals
					 */
					neq: () => LocalizedString
					/**
					 * Like
					 */
					lk: () => LocalizedString
					/**
					 * Not Like
					 */
					nlk: () => LocalizedString
					/**
					 * Greater Than
					 */
					gt: () => LocalizedString
					/**
					 * Greater Equals
					 */
					gte: () => LocalizedString
					/**
					 * Less Than
					 */
					lt: () => LocalizedString
					/**
					 * Less Equals
					 */
					lte: () => LocalizedString
					/**
					 * Is Null
					 */
					nil: () => LocalizedString
					/**
					 * Not Null
					 */
					nnil: () => LocalizedString
					/**
					 * In
					 */
					'in': () => LocalizedString
					/**
					 * Not In
					 */
					nin: () => LocalizedString
					/**
					 * Filter..
					 */
					filterPlaceholder: () => LocalizedString
				}
				td: {
					/**
					 * save
					 */
					save: () => LocalizedString
					/**
					 * clear
					 */
					clear: () => LocalizedString
				}
			}
		}
		routers: {
			type: {
				/**
				 * Create
				 */
				create: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
