// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * Welcome to Svelte Fall Summit {year}
	 * @param {number} year
	 */
	HI: RequiredParams<'year'>
}

export type TranslationFunctions = {
	/**
	 * Welcome to Svelte Fall Summit {year}
	 */
	HI: (arg: { year: number }) => LocalizedString
}

export type Formatters = {}
