// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	uiGraphql: NamespaceUiGraphqlTranslation
}

type RootTranslation = {}

export type NamespaceUiGraphqlTranslation = {
	table: {
		/**
		 * R​e​m​o​v​e​ ​r​o​w​?
		 */
		removeModalTitle: string
		/**
		 * E​d​i​t
		 */
		editBtn: string
		/**
		 * R​e​m​o​v​e
		 */
		removeBtn: string
		/**
		 * C​a​n​c​e​l
		 */
		cancelBtn: string
		th: {
			/**
			 * f​i​l​t​e​r
			 */
			filter: string
			/**
			 * c​a​n​c​e​l
			 */
			cancel: string
			/**
			 * N​o​ ​S​o​r​t
			 */
			noSort: string
			/**
			 * A​S​C
			 */
			asc: string
			/**
			 * D​E​S​C
			 */
			desc: string
			/**
			 * E​q​u​a​l​s
			 */
			eq: string
			/**
			 * N​o​t​ ​E​q​u​a​l​s
			 */
			neq: string
			/**
			 * L​i​k​e
			 */
			lk: string
			/**
			 * N​o​t​ ​L​i​k​e
			 */
			nlk: string
			/**
			 * G​r​e​a​t​e​r​ ​T​h​a​n
			 */
			gt: string
			/**
			 * G​r​e​a​t​e​r​ ​E​q​u​a​l​s
			 */
			gte: string
			/**
			 * L​e​s​s​ ​T​h​a​n
			 */
			lt: string
			/**
			 * L​e​s​s​ ​E​q​u​a​l​s
			 */
			lte: string
			/**
			 * I​s​ ​N​u​l​l
			 */
			nil: string
			/**
			 * N​o​t​ ​N​u​l​l
			 */
			nnil: string
			/**
			 * I​n
			 */
			'in': string
			/**
			 * N​o​t​ ​I​n
			 */
			nin: string
			/**
			 * B​e​t​w​e​e​n
			 */
			bt: string
			/**
			 * N​o​t​ ​B​e​t​w​e​e​n
			 */
			nbt: string
			/**
			 * F​i​l​t​e​r​.​.
			 */
			filterPlaceholder: string
		}
		td: {
			/**
			 * s​a​v​e
			 */
			save: string
			/**
			 * c​l​e​a​r
			 */
			clear: string
		}
	}
	multiSelect: {
		/**
		 * C​r​e​a​t​e​ ​t​h​i​s​ ​o​p​t​i​o​n​.​.​.
		 */
		createOptionMsg: string
		/**
		 * T​h​i​s​ ​o​p​t​i​o​n​ ​i​s​ ​d​i​s​a​b​l​e​d
		 */
		defaultDisabledTitle: string
		/**
		 * T​h​i​s​ ​i​n​p​u​t​ ​i​s​ ​d​i​s​a​b​l​e​d
		 */
		disabledInputTitle: string
		/**
		 * T​h​i​s​ ​o​p​t​i​o​n​ ​i​s​ ​a​l​r​e​a​d​y​ ​s​e​l​e​c​t​e​d
		 */
		duplicateOptionMsg: string
		/**
		 * N​o​ ​m​a​t​c​h​i​n​g​ ​o​p​t​i​o​n​s
		 */
		noMatchingOptionsMsg: string
		/**
		 * R​e​m​o​v​e​ ​a​l​l
		 */
		removeAllTitle: string
		/**
		 * R​e​m​o​v​e
		 */
		removeBtnTitle: string
	}
}

export type Namespaces =
	| 'uiGraphql'

type DisallowNamespaces = {
	/**
	 * reserved for 'uiGraphql'-namespace\
	 * you need to use the `./uiGraphql/index.ts` file instead
	 */
	uiGraphql?: "[typesafe-i18n] reserved for 'uiGraphql'-namespace. You need to use the `./uiGraphql/index.ts` file instead."
}

export type TranslationFunctions = {
	uiGraphql: {
		table: {
			/**
			 * Remove row?
			 */
			removeModalTitle: () => LocalizedString
			/**
			 * Edit
			 */
			editBtn: () => LocalizedString
			/**
			 * Remove
			 */
			removeBtn: () => LocalizedString
			/**
			 * Cancel
			 */
			cancelBtn: () => LocalizedString
			th: {
				/**
				 * filter
				 */
				filter: () => LocalizedString
				/**
				 * cancel
				 */
				cancel: () => LocalizedString
				/**
				 * No Sort
				 */
				noSort: () => LocalizedString
				/**
				 * ASC
				 */
				asc: () => LocalizedString
				/**
				 * DESC
				 */
				desc: () => LocalizedString
				/**
				 * Equals
				 */
				eq: () => LocalizedString
				/**
				 * Not Equals
				 */
				neq: () => LocalizedString
				/**
				 * Like
				 */
				lk: () => LocalizedString
				/**
				 * Not Like
				 */
				nlk: () => LocalizedString
				/**
				 * Greater Than
				 */
				gt: () => LocalizedString
				/**
				 * Greater Equals
				 */
				gte: () => LocalizedString
				/**
				 * Less Than
				 */
				lt: () => LocalizedString
				/**
				 * Less Equals
				 */
				lte: () => LocalizedString
				/**
				 * Is Null
				 */
				nil: () => LocalizedString
				/**
				 * Not Null
				 */
				nnil: () => LocalizedString
				/**
				 * In
				 */
				'in': () => LocalizedString
				/**
				 * Not In
				 */
				nin: () => LocalizedString
				/**
				 * Between
				 */
				bt: () => LocalizedString
				/**
				 * Not Between
				 */
				nbt: () => LocalizedString
				/**
				 * Filter..
				 */
				filterPlaceholder: () => LocalizedString
			}
			td: {
				/**
				 * save
				 */
				save: () => LocalizedString
				/**
				 * clear
				 */
				clear: () => LocalizedString
			}
		}
		multiSelect: {
			/**
			 * Create this option...
			 */
			createOptionMsg: () => LocalizedString
			/**
			 * This option is disabled
			 */
			defaultDisabledTitle: () => LocalizedString
			/**
			 * This input is disabled
			 */
			disabledInputTitle: () => LocalizedString
			/**
			 * This option is already selected
			 */
			duplicateOptionMsg: () => LocalizedString
			/**
			 * No matching options
			 */
			noMatchingOptionsMsg: () => LocalizedString
			/**
			 * Remove all
			 */
			removeAllTitle: () => LocalizedString
			/**
			 * Remove
			 */
			removeBtnTitle: () => LocalizedString
		}
	}
}

export type Formatters = {}
