// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	ui_graphql: NamespaceUiGraphqlTranslation
}

type RootTranslation = {}

export type NamespaceUiGraphqlTranslation = {
	text: {
		/**
		 * Y​e​s
		 */
		'true': string
		/**
		 * N​o
		 */
		'false': string
	}
	table: {
		/**
		 * R​e​m​o​v​e​ ​R​o​w​?
		 */
		removeModalTitle: string
		/**
		 * E​d​i​t
		 */
		editBtn: string
		/**
		 * R​e​m​o​v​e
		 */
		removeBtn: string
		/**
		 * C​a​n​c​e​l
		 */
		cancelBtn: string
		th: {
			/**
			 * F​i​l​t​e​r
			 */
			filter: string
			/**
			 * C​a​n​c​e​l
			 */
			cancel: string
			/**
			 * N​o​ ​S​o​r​t
			 */
			noSort: string
			/**
			 * A​S​C
			 */
			asc: string
			/**
			 * D​E​S​C
			 */
			desc: string
			/**
			 * E​q​u​a​l​s
			 */
			eq: string
			/**
			 * N​o​t​ ​E​q​u​a​l​s
			 */
			neq: string
			/**
			 * L​i​k​e
			 */
			lk: string
			/**
			 * N​o​t​ ​L​i​k​e
			 */
			nlk: string
			/**
			 * G​r​e​a​t​e​r​ ​T​h​a​n
			 */
			gt: string
			/**
			 * G​r​e​a​t​e​r​ ​E​q​u​a​l​s
			 */
			gte: string
			/**
			 * L​e​s​s​ ​T​h​a​n
			 */
			lt: string
			/**
			 * L​e​s​s​ ​E​q​u​a​l​s
			 */
			lte: string
			/**
			 * I​s​ ​N​u​l​l
			 */
			nil: string
			/**
			 * N​o​t​ ​N​u​l​l
			 */
			nnil: string
			/**
			 * I​n
			 */
			'in': string
			/**
			 * N​o​t​ ​I​n
			 */
			nin: string
			/**
			 * B​e​t​w​e​e​n
			 */
			bt: string
			/**
			 * N​o​t​ ​B​e​t​w​e​e​n
			 */
			nbt: string
			/**
			 * F​i​l​t​e​r​ ​V​a​l​u​e
			 */
			filterPlaceholder: string
		}
		td: {
			/**
			 * S​a​v​e
			 */
			save: string
			/**
			 * C​l​e​a​r
			 */
			clear: string
		}
	}
}

export type Namespaces =
	| 'ui_graphql'

type DisallowNamespaces = {
	/**
	 * reserved for 'ui_graphql'-namespace\
	 * you need to use the `./ui_graphql/index.ts` file instead
	 */
	ui_graphql?: "[typesafe-i18n] reserved for 'ui_graphql'-namespace. You need to use the `./ui_graphql/index.ts` file instead."
}

export type TranslationFunctions = {
	ui_graphql: {
		text: {
			/**
			 * Yes
			 */
			'true': () => LocalizedString
			/**
			 * No
			 */
			'false': () => LocalizedString
		}
		table: {
			/**
			 * Remove Row?
			 */
			removeModalTitle: () => LocalizedString
			/**
			 * Edit
			 */
			editBtn: () => LocalizedString
			/**
			 * Remove
			 */
			removeBtn: () => LocalizedString
			/**
			 * Cancel
			 */
			cancelBtn: () => LocalizedString
			th: {
				/**
				 * Filter
				 */
				filter: () => LocalizedString
				/**
				 * Cancel
				 */
				cancel: () => LocalizedString
				/**
				 * No Sort
				 */
				noSort: () => LocalizedString
				/**
				 * ASC
				 */
				asc: () => LocalizedString
				/**
				 * DESC
				 */
				desc: () => LocalizedString
				/**
				 * Equals
				 */
				eq: () => LocalizedString
				/**
				 * Not Equals
				 */
				neq: () => LocalizedString
				/**
				 * Like
				 */
				lk: () => LocalizedString
				/**
				 * Not Like
				 */
				nlk: () => LocalizedString
				/**
				 * Greater Than
				 */
				gt: () => LocalizedString
				/**
				 * Greater Equals
				 */
				gte: () => LocalizedString
				/**
				 * Less Than
				 */
				lt: () => LocalizedString
				/**
				 * Less Equals
				 */
				lte: () => LocalizedString
				/**
				 * Is Null
				 */
				nil: () => LocalizedString
				/**
				 * Not Null
				 */
				nnil: () => LocalizedString
				/**
				 * In
				 */
				'in': () => LocalizedString
				/**
				 * Not In
				 */
				nin: () => LocalizedString
				/**
				 * Between
				 */
				bt: () => LocalizedString
				/**
				 * Not Between
				 */
				nbt: () => LocalizedString
				/**
				 * Filter Value
				 */
				filterPlaceholder: () => LocalizedString
			}
			td: {
				/**
				 * Save
				 */
				save: () => LocalizedString
				/**
				 * Clear
				 */
				clear: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
