query Query_menu_role($menu_id: StringExpression, $id: StringExpression, $name: StringExpression, $description: StringExpression, $users: UserExpression, $composites: RoleExpression, $permissions: PermissionExpression, $apis: ApiExpression, $menus: MenuExpression, $realm: RealmExpression, $includeDeprecated: Boolean, $version: IntExpression, $realmId: IntExpression, $createUserId: StringExpression, $createTime: StringExpression, $updateUserId: StringExpression, $updateTime: StringExpression, $createGroupId: StringExpression, $userRole: UserRoleExpression, $roleComposite: RoleCompositeExpression, $roleApi: RoleApiExpression, $roleMenu: RoleMenuExpression, ) {
  menu(id: $menu_id)  {
    id
    name
    type
    path
    icon
    description
    isDeprecated
    version
    realmId
    createUserId
    createTime
    updateUserId
    updateTime
    createGroupId
    role(id: $id name: $name description: $description users: $users composites: $composites permissions: $permissions apis: $apis menus: $menus realm: $realm includeDeprecated: $includeDeprecated version: $version realmId: $realmId createUserId: $createUserId createTime: $createTime updateUserId: $updateUserId updateTime: $updateTime createGroupId: $createGroupId userRole: $userRole roleComposite: $roleComposite roleApi: $roleApi roleMenu: $roleMenu)  {
      id
      name
      description
      isDeprecated
      version
      realmId
      createUserId
      createTime
      updateUserId
      updateTime
      createGroupId
    }
  }
}