query Query_role($composites: RoleExpression, $cond: Conditional, $createGroupId: StringExpression, $createTime: StringExpression, $createUserId: StringExpression, $description: StringExpression, $exs: [RoleExpression], $id: StringExpression, $includeDeprecated: Boolean, $name: StringExpression, $permissions: PermissionExpression, $realm: RealmExpression, $realmId: StringExpression, $roleComposite: RoleCompositeExpression, $updateTime: StringExpression, $updateUserId: StringExpression, $userRole: UserRoleExpression, $users: UserExpression, $version: IntExpression, $skipNullArguments: Boolean = true) {
  role(composites: $composites cond: $cond createGroupId: $createGroupId createTime: $createTime createUserId: $createUserId description: $description exs: $exs id: $id includeDeprecated: $includeDeprecated name: $name permissions: $permissions realm: $realm realmId: $realmId roleComposite: $roleComposite updateTime: $updateTime updateUserId: $updateUserId userRole: $userRole users: $users version: $version) @skipNullArguments(if: $skipNullArguments) {
    createGroupId
    createTime
    createUserId
    description
    id
    isDeprecated
    name
    realmId
    updateTime
    updateUserId
    version
  }
}