query Query_userRole($cond: Conditional, $createGroupId: StringExpression, $createTime: StringExpression, $createUserId: StringExpression, $exs: [UserRoleExpression], $from: UserExpression, $id: StringExpression, $includeDeprecated: Boolean, $realmId: StringExpression, $roleId: IntExpression, $to: RoleExpression, $updateTime: StringExpression, $updateUserId: StringExpression, $userId: IntExpression, $version: IntExpression, $skipNullArguments: Boolean = true) {
  userRole(cond: $cond createGroupId: $createGroupId createTime: $createTime createUserId: $createUserId exs: $exs from: $from id: $id includeDeprecated: $includeDeprecated realmId: $realmId roleId: $roleId to: $to updateTime: $updateTime updateUserId: $updateUserId userId: $userId version: $version) @skipNullArguments(if: $skipNullArguments) {
    createGroupId
    createTime
    createUserId
    id
    isDeprecated
    realmId
    roleId
    updateTime
    updateUserId
    userId
    version
  }
}