query Query_parent2($organization: OrganizationInput, $skipNullArguments: Boolean = true) {
  parent2(organization: $organization) @skipNullArguments(if: $skipNullArguments) {
    aboveId
    createGroupId
    createTime
    createUserId
    id
    isDeprecated
    name
    orgLevel3
    realmId
    roleDisable
    updateTime
    updateUserId
    version
  }
}