query Query_role_roleMenu($role_id: StringExpression, $first: Int, $last: Int, $offset: Int, $orderBy: RoleMenuOrderBy, $groupBy: [String!], $id: StringExpression, $roleId: IntExpression, $from: RoleExpression, $menuId: IntExpression, $to: MenuExpression, $totalCount: IntExpression, ) {
  role(id: $role_id)  {
    id
    name
    description
    isDeprecated
    version
    realmId
    createUserId
    createTime
    updateUserId
    updateTime
    createGroupId
    roleMenuConnection(first: $first last: $last offset: $offset orderBy: $orderBy groupBy: $groupBy id: $id roleId: $roleId from: $from menuId: $menuId to: $to totalCount: $totalCount)  {
      totalCount
      edges {
        node {
          id
          roleId
          menuId
          isDeprecated
          version
          realmId
          createUserId
          createTime
          updateUserId
          updateTime
          createGroupId
        }
      }
    }
  }
}