query Query_user_realm($user_id: StringExpression, $id: StringExpression, $name: StringExpression, ) {
  user(id: $user_id)  {
    id
    name
    lastName
    login
    email
    phones
    disable
    isDeprecated
    version
    realmId
    createUserId
    createTime
    updateUserId
    updateTime
    createGroupId
    realm(id: $id name: $name)  {
      id
      name
      isDeprecated
      version
      realmId
      createUserId
      createTime
      updateUserId
      updateTime
      createGroupId
    }
  }
}