query Query_userRoleConnection($after: ID, $before: ID, $cond: Conditional, $createGroupId: StringExpression, $createTime: StringExpression, $createUserId: StringExpression, $exs: [UserRoleExpression], $first: Int, $groupBy: [String!], $id: StringExpression, $includeDeprecated: Boolean, $last: Int, $offset: Int, $orderBy: UserRoleOrderBy, $realmId: StringExpression, $roleId: IntExpression, $updateTime: StringExpression, $updateUserId: StringExpression, $userId: IntExpression, $version: IntExpression, $skipNullArguments: Boolean = true) {
  userRoleConnection(after: $after before: $before cond: $cond createGroupId: $createGroupId createTime: $createTime createUserId: $createUserId exs: $exs first: $first groupBy: $groupBy id: $id includeDeprecated: $includeDeprecated last: $last offset: $offset orderBy: $orderBy realmId: $realmId roleId: $roleId updateTime: $updateTime updateUserId: $updateUserId userId: $userId version: $version) @skipNullArguments(if: $skipNullArguments) {
    totalCount
    edges {
      node {
        createGroupId
        createTime
        createUserId
        id
        isDeprecated
        realmId
        roleId
        updateTime
        updateUserId
        userId
        version
      }
    }
  }
}