query Query_userTest2List($after: ID $before: ID $cond: Conditional $createGroupId: StringExpression $createTime: StringExpression $createUserId: StringExpression $first: Int $groupBy: [String!] $id: StringExpression $includeDeprecated: Boolean $last: Int $offset: Int $orderBy: UserTest2OrderBy $realmId: StringExpression $test2: BooleanExpression $updateTime: StringExpression $updateUserId: StringExpression $userId: IntExpression $version: IntExpression $skipNullArguments: Boolean = true) {
  userTest2List(after: $after before: $before cond: $cond createGroupId: $createGroupId createTime: $createTime createUserId: $createUserId first: $first groupBy: $groupBy id: $id includeDeprecated: $includeDeprecated last: $last offset: $offset orderBy: $orderBy realmId: $realmId test2: $test2 updateTime: $updateTime updateUserId: $updateUserId userId: $userId version: $version) @skipNullArguments(if: $skipNullArguments) {
    createGroupId
    createTime
    createUserId
    id
    isDeprecated
    realmId
    test2
    updateTime
    updateUserId
    userId
    version
  }
}