query Query_menu_folder($menu_id: StringExpression, $id: StringExpression, $name: StringExpression, $type: MenuTypeExpression, $path: StringExpression, $icon: StringExpression, $folder: MenuExpression, $description: StringExpression, $role: RoleExpression, $realm: RealmExpression, ) {
  menu(id: $menu_id)  {
    id
    name
    type
    path
    icon
    description
    isDeprecated
    version
    realmId
    createUserId
    createTime
    updateUserId
    updateTime
    createGroupId
    folder(id: $id name: $name type: $type path: $path icon: $icon folder: $folder description: $description role: $role realm: $realm)  {
      id
      name
      type
      path
      icon
      description
      isDeprecated
      version
      realmId
      createUserId
      createTime
      updateUserId
      updateTime
      createGroupId
      parentId
      roleId
    }
  }
}