query Query_userByOrg2_roles($organization: OrganizationInput $skipNullArguments: Boolean = true) {
  userByOrg2(organization: $organization) @skipNullArguments(if: $skipNullArguments) {
    age
    createGroupId
    createTime
    createUserId
    disable
    id
    isDeprecated
    login
    name
    organizationId
    password
    phones
    realmId
    sex
    test1
    test2
    updateTime
    updateUserId
    userDetail2
    version
    rolesConnection {
      totalCount
      edges {
        node {
          createGroupId
          createTime
          createUserId
          id
          isDeprecated
          name
          realmId
          type
          updateTime
          updateUserId
          version
        }
      }
    }
  }
}