query Query_organization_userByOrg($organization_id: StringExpression, $skipNullArguments: Boolean = true) {
  organization(id: $organization_id) @skipNullArguments(if: $skipNullArguments) {
    aboveId
    createGroupId
    createTime
    createUserId
    id
    isDeprecated
    name
    orgLevel3
    realmId
    roleDisable
    updateTime
    updateUserId
    version
    userByOrg {
      age
      createGroupId
      createTime
      createUserId
      disable
      id
      isDeprecated
      login
      name
      organizationId
      password
      phones
      realmId
      sex
      test1
      test2
      updateTime
      updateUserId
      userDetail2
      version
    }
  }
}