query Query_roleComposite($compositeId: IntExpression, $cond: Conditional, $createGroupId: StringExpression, $createTime: StringExpression, $createUserId: StringExpression, $from: RoleExpression, $id: StringExpression, $includeDeprecated: Boolean, $realmId: StringExpression, $roleId: IntExpression, $to: RoleExpression, $updateTime: StringExpression, $updateUserId: StringExpression, $version: IntExpression, $skipNullArguments: Boolean = true) {
  roleComposite(compositeId: $compositeId cond: $cond createGroupId: $createGroupId createTime: $createTime createUserId: $createUserId from: $from id: $id includeDeprecated: $includeDeprecated realmId: $realmId roleId: $roleId to: $to updateTime: $updateTime updateUserId: $updateUserId version: $version) @skipNullArguments(if: $skipNullArguments) {
    compositeId
    createGroupId
    createTime
    createUserId
    id
    isDeprecated
    realmId
    roleId
    updateTime
    updateUserId
    version
  }
}