query Query_group_realm($group_id: StringExpression, $id: StringExpression, $name: StringExpression, $groupBy: [String!]) {
  group(id: $group_id)  {
    id
    name
    path
    deep
    isDeprecated
    version
    realmId
    createUserId
    createTime
    updateUserId
    updateTime
    createGroupId
    realm(id: $id name: $name groupBy: $groupBy)  {
      id
      name
      isDeprecated
      version
      realmId
      createUserId
      createTime
      updateUserId
      updateTime
      createGroupId
    }
  }
}