query Query_menu($id: StringExpression, $name: StringExpression, $type: MenuTypeExpression, $path: StringExpression, $icon: StringExpression, $folder: MenuExpression, $description: StringExpression, $role: RoleExpression, $realm: RealmExpression, $includeDeprecated: Boolean, $version: IntExpression, $realmId: IntExpression, $createUserId: StringExpression, $createTime: StringExpression, $updateUserId: StringExpression, $updateTime: StringExpression, $createGroupId: StringExpression, $parentId: IntExpression, $roleId: IntExpression, $cond: Conditional, $exs: [MenuExpression]) {
  menu(id: $id name: $name type: $type path: $path icon: $icon folder: $folder description: $description role: $role realm: $realm includeDeprecated: $includeDeprecated version: $version realmId: $realmId createUserId: $createUserId createTime: $createTime updateUserId: $updateUserId updateTime: $updateTime createGroupId: $createGroupId parentId: $parentId roleId: $roleId cond: $cond exs: $exs)  {
    id
    name
    type
    path
    icon
    description
    isDeprecated
    version
    realmId
    createUserId
    createTime
    updateUserId
    updateTime
    createGroupId
  }
}