query Query_userList($after: ID, $before: ID, $cond: Conditional, $createGroupId: StringExpression, $createTime: StringExpression, $createUserId: StringExpression, $disable: BooleanExpression, $email: StringExpression, $first: Int, $groupBy: [String!], $groups: GroupExpression, $id: StringExpression, $includeDeprecated: Boolean, $last: Int, $lastName: StringExpression, $login: StringExpression, $name: StringExpression, $offset: Int, $orderBy: UserOrderBy, $password: StringExpression, $realm: RealmExpression, $realmId: StringExpression, $roles: RoleExpression, $updateTime: StringExpression, $updateUserId: StringExpression, $userGroup: UserGroupExpression, $userRole: UserRoleExpression, $version: IntExpression, $skipNullArguments: Boolean = true) {
  userList(after: $after before: $before cond: $cond createGroupId: $createGroupId createTime: $createTime createUserId: $createUserId disable: $disable email: $email first: $first groupBy: $groupBy groups: $groups id: $id includeDeprecated: $includeDeprecated last: $last lastName: $lastName login: $login name: $name offset: $offset orderBy: $orderBy password: $password realm: $realm realmId: $realmId roles: $roles updateTime: $updateTime updateUserId: $updateUserId userGroup: $userGroup userRole: $userRole version: $version) @skipNullArguments(if: $skipNullArguments) {
    createGroupId
    createTime
    createUserId
    disable
    email
    id
    isDeprecated
    lastName
    login
    name
    password
    realmId
    updateTime
    updateUserId
    version
  }
}