query Query_role_realm($role_id: StringExpression, $id: StringExpression, $name: StringExpression, $description: StringExpression, $groupBy: [String!]) {
  role(id: $role_id)  {
    id
    name
    description
    isDeprecated
    version
    realmId
    createUserId
    createTime
    updateUserId
    updateTime
    createGroupId
    realm(id: $id name: $name description: $description groupBy: $groupBy)  {
      id
      name
      description
      isDeprecated
      version
      realmId
      createUserId
      createTime
      updateUserId
      updateTime
      createGroupId
    }
  }
}