query Query_user_userProfile($user_id: StringExpression, $address: StringExpression, $email: StringExpression, $id: StringExpression, $qq: StringExpression, $user: UserExpression, $userId: StringExpression, $skipNullArguments: Boolean = true) {
  user(id: $user_id) @skipNullArguments(if: $skipNullArguments) {
    age
    createGroupId
    createTime
    createUserId
    disable
    id
    isDeprecated
    login
    name
    organizationId
    password
    phones
    realmId
    sex
    test1
    test2
    updateTime
    updateUserId
    userDetail2
    version
    userProfile(address: $address email: $email id: $id qq: $qq user: $user userId: $userId) {
      address
      createGroupId
      createTime
      createUserId
      email
      id
      isDeprecated
      qq
      realmId
      updateTime
      updateUserId
      userId
      version
    }
  }
}