query Query_role_groups($role_id: StringExpression, $first: Int, $last: Int, $offset: Int, $orderBy: GroupOrderBy, $groupBy: [String!], $after: ID, $before: ID, $id: StringExpression, $name: StringExpression, $description: StringExpression, $path: StringExpression, $deep: IntExpression, $parentId: StringExpression, $parent: GroupExpression, $subGroups: GroupExpression, $users: UserExpression, $roles: RoleExpression, $realm: RealmExpression) {
  role(id: $role_id)  {
    id
    name
    description
    isDeprecated
    version
    realmId
    createUserId
    createTime
    updateUserId
    updateTime
    createGroupId
    groupsConnection(first: $first last: $last offset: $offset orderBy: $orderBy groupBy: $groupBy after: $after before: $before id: $id name: $name description: $description path: $path deep: $deep parentId: $parentId parent: $parent subGroups: $subGroups users: $users roles: $roles realm: $realm)  {
      totalCount
      edges {
        node {
          id
          name
          description
          path
          deep
          parentId
          isDeprecated
          version
          realmId
          createUserId
          createTime
          updateUserId
          updateTime
          createGroupId
          parent {
            id
            name
            description
            path
            deep
            parentId
            isDeprecated
            version
            realmId
            createUserId
            createTime
            updateUserId
            updateTime
            createGroupId
          }
          subGroups {
            id
            name
            description
            path
            deep
            parentId
            isDeprecated
            version
            realmId
            createUserId
            createTime
            updateUserId
            updateTime
            createGroupId
          }
          users {
            id
            name
            description
            lastName
            login
            email
            phones
            disable
            isDeprecated
            version
            realmId
            createUserId
            createTime
            updateUserId
            updateTime
            createGroupId
          }
          roles {
            id
            name
            description
            isDeprecated
            version
            realmId
            createUserId
            createTime
            updateUserId
            updateTime
            createGroupId
          }
          realm {
            name
            description
          }
        }
      }
    }
  }
}