query Query_user_userGroup($user_id: StringExpression, $first: Int, $from: UserExpression, $groupBy: [String!], $groupId: IntExpression, $id: StringExpression, $last: Int, $offset: Int, $orderBy: UserGroupOrderBy, $to: GroupExpression, $totalCount: IntExpression, $userId: IntExpression, $skipNullArguments: Boolean = true) {
  user(id: $user_id) @skipNullArguments(if: $skipNullArguments) {
    createGroupId
    createTime
    createUserId
    disable
    email
    id
    isDeprecated
    lastName
    login
    name
    password
    realmId
    updateTime
    updateUserId
    version
    userGroupConnection(first: $first from: $from groupBy: $groupBy groupId: $groupId id: $id last: $last offset: $offset orderBy: $orderBy to: $to totalCount: $totalCount userId: $userId) @skipNullArguments(if: $skipNullArguments) {
      totalCount
      edges {
        node {
          createGroupId
          createTime
          createUserId
          groupId
          id
          isDeprecated
          realmId
          updateTime
          updateUserId
          userId
          version
        }
      }
    }
  }
}