query Query_menu_folder($menu_id: StringExpression, $id: StringExpression, $name: StringExpression, $type: MenuTypeExpression, $path: StringExpression, $icon: StringExpression, $folder: MenuExpression, $description: StringExpression, $role: RoleExpression, $realm: RealmExpression, $includeDeprecated: Boolean, $version: IntExpression, $realmId: StringExpression, $createUserId: StringExpression, $createTime: StringExpression, $updateUserId: StringExpression, $updateTime: StringExpression, $createGroupId: StringExpression, $parentId: IntExpression, $roleId: IntExpression, ) {
  menu(id: $menu_id)  {
    id
    name
    type
    path
    icon
    description
    isDeprecated
    version
    realmId
    createUserId
    createTime
    updateUserId
    updateTime
    createGroupId
    folder(id: $id name: $name type: $type path: $path icon: $icon folder: $folder description: $description role: $role realm: $realm includeDeprecated: $includeDeprecated version: $version realmId: $realmId createUserId: $createUserId createTime: $createTime updateUserId: $updateUserId updateTime: $updateTime createGroupId: $createGroupId parentId: $parentId roleId: $roleId)  {
      id
      name
      type
      path
      icon
      description
      isDeprecated
      version
      realmId
      createUserId
      createTime
      updateUserId
      updateTime
      createGroupId
      parentId
      roleId
    }
  }
}