query Query_user_organization($user_id: StringExpression, $above: OrganizationExpression, $aboveId: IntExpression, $id: StringExpression, $name: StringExpression, $users: UserExpression, $skipNullArguments: Boolean = true) {
  user(id: $user_id) @skipNullArguments(if: $skipNullArguments) {
    age
    createGroupId
    createTime
    createUserId
    disable
    id
    isDeprecated
    login
    name
    organizationId
    password
    phones
    realmId
    sex
    test1
    test2
    updateTime
    updateUserId
    userDetail2
    version
    organization(above: $above aboveId: $aboveId id: $id name: $name users: $users) @skipNullArguments(if: $skipNullArguments) {
      aboveId
      createGroupId
      createTime
      createUserId
      id
      isDeprecated
      name
      orgLevel3
      realmId
      roleDisable
      updateTime
      updateUserId
      version
    }
  }
}