query Query_permission($cond: Conditional, $createGroupId: StringExpression, $createTime: StringExpression, $createUserId: StringExpression, $description: StringExpression, $exs: [PermissionExpression], $id: StringExpression, $includeDeprecated: Boolean, $level: PermissionLevelExpression, $name: StringExpression, $ofTypeName: StringExpression, $realm: RealmExpression, $realmId: StringExpression, $role: RoleExpression, $roleId: IntExpression, $updateTime: StringExpression, $updateUserId: StringExpression, $version: IntExpression, $skipNullArguments: Boolean = true) {
  permission(cond: $cond createGroupId: $createGroupId createTime: $createTime createUserId: $createUserId description: $description exs: $exs id: $id includeDeprecated: $includeDeprecated level: $level name: $name ofTypeName: $ofTypeName realm: $realm realmId: $realmId role: $role roleId: $roleId updateTime: $updateTime updateUserId: $updateUserId version: $version) @skipNullArguments(if: $skipNullArguments) {
    createGroupId
    createTime
    createUserId
    description
    id
    isDeprecated
    level
    name
    ofTypeName
    realmId
    roleId
    updateTime
    updateUserId
    version
  }
}