query Query_userGroup($cond: Conditional, $createGroupId: StringExpression, $createTime: StringExpression, $createUserId: StringExpression, $from: UserExpression, $groupId: IntExpression, $id: StringExpression, $includeDeprecated: Boolean, $realmId: StringExpression, $to: GroupExpression, $updateTime: StringExpression, $updateUserId: StringExpression, $userId: IntExpression, $version: IntExpression, $skipNullArguments: Boolean = true) {
  userGroup(cond: $cond createGroupId: $createGroupId createTime: $createTime createUserId: $createUserId from: $from groupId: $groupId id: $id includeDeprecated: $includeDeprecated realmId: $realmId to: $to updateTime: $updateTime updateUserId: $updateUserId userId: $userId version: $version) @skipNullArguments(if: $skipNullArguments) {
    createGroupId
    createTime
    createUserId
    groupId
    id
    isDeprecated
    realmId
    updateTime
    updateUserId
    userId
    version
  }
}