// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	ui: NamespaceUiTranslation
}

type RootTranslation = {}

export type NamespaceUiTranslation = {
	message: {
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * C​o​n​f​i​r​m
		 */
		confirm: string
		/**
		 * N​o​ ​R​e​s​u​l​t
		 */
		empty: string
	}
	menu: {
		/**
		 * M​e​n​u
		 */
		menu: string
		/**
		 * O​p​e​n​ ​M​e​n​u
		 */
		open: string
		/**
		 * M​o​r​e
		 */
		more: string
	}
	pagination: {
		/**
		 * S​i​z​e
		 */
		size: string
		/**
		 * {​t​o​t​a​l​}​ ​R​e​s​u​l​t​s
		 * @param {number} total
		 */
		total: RequiredParams<'total'>
		/**
		 * P​a​g​e​ ​{​c​u​r​r​e​n​t​}
		 * @param {number} current
		 */
		current: RequiredParams<'current'>
		/**
		 * P​r​e​v​i​o​u​s
		 */
		previous: string
		/**
		 * N​e​x​t
		 */
		next: string
	}
	inputList: {
		/**
		 * A​d​d
		 */
		add: string
		/**
		 * R​e​m​o​v​e
		 */
		remove: string
	}
	button: {
		/**
		 * S​e​a​r​c​h
		 */
		search: string
		/**
		 * R​e​m​o​v​e
		 */
		remove: string
		/**
		 * U​n​b​i​n​d
		 */
		unbind: string
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * C​r​e​a​t​e
		 */
		create: string
		/**
		 * S​e​l​e​c​t
		 */
		select: string
		/**
		 * B​a​c​k
		 */
		back: string
	}
	themeSelect: {
		/**
		 * T​h​e​m​e
		 */
		btn: string
		themes: {
			/**
			 * l​i​g​h​t
			 */
			light: string
			/**
			 * d​a​r​k
			 */
			dark: string
			/**
			 * c​u​p​c​a​k​e
			 */
			cupcake: string
			/**
			 * b​u​m​b​l​e​b​e​e
			 */
			bumblebee: string
			/**
			 * e​m​e​r​a​l​d
			 */
			emerald: string
			/**
			 * c​o​r​p​o​r​a​t​e
			 */
			corporate: string
			/**
			 * s​y​n​t​h​w​a​v​e
			 */
			synthwave: string
			/**
			 * r​e​t​r​o
			 */
			retro: string
			/**
			 * c​y​b​e​r​p​u​n​k
			 */
			cyberpunk: string
			/**
			 * v​a​l​e​n​t​i​n​e
			 */
			valentine: string
			/**
			 * h​a​l​l​o​w​e​e​n
			 */
			halloween: string
			/**
			 * g​a​r​d​e​n
			 */
			garden: string
			/**
			 * f​o​r​e​s​t
			 */
			forest: string
			/**
			 * a​q​u​a
			 */
			aqua: string
			/**
			 * l​o​f​i
			 */
			lofi: string
			/**
			 * p​a​s​t​e​l
			 */
			pastel: string
			/**
			 * f​a​n​t​a​s​y
			 */
			fantasy: string
			/**
			 * w​i​r​e​f​r​a​m​e
			 */
			wireframe: string
			/**
			 * b​l​a​c​k
			 */
			black: string
			/**
			 * l​u​x​u​r​y
			 */
			luxury: string
			/**
			 * d​r​a​c​u​l​a
			 */
			dracula: string
			/**
			 * c​m​y​k
			 */
			cmyk: string
			/**
			 * a​u​t​u​m​n
			 */
			autumn: string
			/**
			 * b​u​s​i​n​e​s​s
			 */
			business: string
			/**
			 * a​c​i​d
			 */
			acid: string
			/**
			 * l​e​m​o​n​a​d​e
			 */
			lemonade: string
			/**
			 * n​i​g​h​t
			 */
			night: string
			/**
			 * c​o​f​f​e​e
			 */
			coffee: string
			/**
			 * w​i​n​t​e​r
			 */
			winter: string
		}
	}
}

export type Namespaces =
	| 'ui'

type DisallowNamespaces = {
	/**
	 * reserved for 'ui'-namespace\
	 * you need to use the `./ui/index.ts` file instead
	 */
	ui?: "[typesafe-i18n] reserved for 'ui'-namespace. You need to use the `./ui/index.ts` file instead."
}

export type TranslationFunctions = {
	ui: {
		message: {
			/**
			 * Cancel
			 */
			cancel: () => LocalizedString
			/**
			 * Confirm
			 */
			confirm: () => LocalizedString
			/**
			 * No Result
			 */
			empty: () => LocalizedString
		}
		menu: {
			/**
			 * Menu
			 */
			menu: () => LocalizedString
			/**
			 * Open Menu
			 */
			open: () => LocalizedString
			/**
			 * More
			 */
			more: () => LocalizedString
		}
		pagination: {
			/**
			 * Size
			 */
			size: () => LocalizedString
			/**
			 * {total} Results
			 */
			total: (arg: { total: number }) => LocalizedString
			/**
			 * Page {current}
			 */
			current: (arg: { current: number }) => LocalizedString
			/**
			 * Previous
			 */
			previous: () => LocalizedString
			/**
			 * Next
			 */
			next: () => LocalizedString
		}
		inputList: {
			/**
			 * Add
			 */
			add: () => LocalizedString
			/**
			 * Remove
			 */
			remove: () => LocalizedString
		}
		button: {
			/**
			 * Search
			 */
			search: () => LocalizedString
			/**
			 * Remove
			 */
			remove: () => LocalizedString
			/**
			 * Unbind
			 */
			unbind: () => LocalizedString
			/**
			 * Save
			 */
			save: () => LocalizedString
			/**
			 * Create
			 */
			create: () => LocalizedString
			/**
			 * Select
			 */
			select: () => LocalizedString
			/**
			 * Back
			 */
			back: () => LocalizedString
		}
		themeSelect: {
			/**
			 * Theme
			 */
			btn: () => LocalizedString
			themes: {
				/**
				 * light
				 */
				light: () => LocalizedString
				/**
				 * dark
				 */
				dark: () => LocalizedString
				/**
				 * cupcake
				 */
				cupcake: () => LocalizedString
				/**
				 * bumblebee
				 */
				bumblebee: () => LocalizedString
				/**
				 * emerald
				 */
				emerald: () => LocalizedString
				/**
				 * corporate
				 */
				corporate: () => LocalizedString
				/**
				 * synthwave
				 */
				synthwave: () => LocalizedString
				/**
				 * retro
				 */
				retro: () => LocalizedString
				/**
				 * cyberpunk
				 */
				cyberpunk: () => LocalizedString
				/**
				 * valentine
				 */
				valentine: () => LocalizedString
				/**
				 * halloween
				 */
				halloween: () => LocalizedString
				/**
				 * garden
				 */
				garden: () => LocalizedString
				/**
				 * forest
				 */
				forest: () => LocalizedString
				/**
				 * aqua
				 */
				aqua: () => LocalizedString
				/**
				 * lofi
				 */
				lofi: () => LocalizedString
				/**
				 * pastel
				 */
				pastel: () => LocalizedString
				/**
				 * fantasy
				 */
				fantasy: () => LocalizedString
				/**
				 * wireframe
				 */
				wireframe: () => LocalizedString
				/**
				 * black
				 */
				black: () => LocalizedString
				/**
				 * luxury
				 */
				luxury: () => LocalizedString
				/**
				 * dracula
				 */
				dracula: () => LocalizedString
				/**
				 * cmyk
				 */
				cmyk: () => LocalizedString
				/**
				 * autumn
				 */
				autumn: () => LocalizedString
				/**
				 * business
				 */
				business: () => LocalizedString
				/**
				 * acid
				 */
				acid: () => LocalizedString
				/**
				 * lemonade
				 */
				lemonade: () => LocalizedString
				/**
				 * night
				 */
				night: () => LocalizedString
				/**
				 * coffee
				 */
				coffee: () => LocalizedString
				/**
				 * winter
				 */
				winter: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
