// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	ui_graphql: NamespaceUiGraphqlTranslation
}

type RootTranslation = {}

export type NamespaceUiGraphqlTranslation = {
	table: {
		/**
		 * R​e​m​o​v​e​ ​r​o​w​?
		 */
		removeModalTitle: string
		/**
		 * E​d​i​t
		 */
		editBtn: string
		/**
		 * R​e​m​o​v​e
		 */
		removeBtn: string
		/**
		 * C​a​n​c​e​l
		 */
		cancelBtn: string
		th: {
			/**
			 * f​i​l​t​e​r
			 */
			filter: string
			/**
			 * c​a​n​c​e​l
			 */
			cancel: string
			/**
			 * N​o​ ​S​o​r​t
			 */
			noSort: string
			/**
			 * A​S​C
			 */
			asc: string
			/**
			 * D​E​S​C
			 */
			desc: string
			/**
			 * E​q​u​a​l​s
			 */
			eq: string
			/**
			 * N​o​t​ ​E​q​u​a​l​s
			 */
			neq: string
			/**
			 * L​i​k​e
			 */
			lk: string
			/**
			 * N​o​t​ ​L​i​k​e
			 */
			nlk: string
			/**
			 * G​r​e​a​t​e​r​ ​T​h​a​n
			 */
			gt: string
			/**
			 * G​r​e​a​t​e​r​ ​E​q​u​a​l​s
			 */
			gte: string
			/**
			 * L​e​s​s​ ​T​h​a​n
			 */
			lt: string
			/**
			 * L​e​s​s​ ​E​q​u​a​l​s
			 */
			lte: string
			/**
			 * I​s​ ​N​u​l​l
			 */
			nil: string
			/**
			 * N​o​t​ ​N​u​l​l
			 */
			nnil: string
			/**
			 * I​n
			 */
			'in': string
			/**
			 * N​o​t​ ​I​n
			 */
			nin: string
			/**
			 * B​e​t​w​e​e​n
			 */
			bt: string
			/**
			 * N​o​t​ ​B​e​t​w​e​e​n
			 */
			nbt: string
			/**
			 * F​i​l​t​e​r​.​.
			 */
			filterPlaceholder: string
		}
		td: {
			/**
			 * s​a​v​e
			 */
			save: string
			/**
			 * c​l​e​a​r
			 */
			clear: string
		}
	}
	grid: {
		buttons: {
			/**
			 * R​e​f​r​e​s​h
			 */
			refresh: string
			/**
			 * S​a​v​e
			 */
			save: string
			/**
			 * N​e​w
			 */
			'new': string
			/**
			 * A​p​p​e​n​d
			 */
			append: string
			/**
			 * R​e​m​o​v​e
			 */
			remove: string
			/**
			 * o​k
			 */
			ok: string
			/**
			 * C​a​n​e​l
			 */
			canel: string
			/**
			 * E​x​p​o​r​t
			 */
			'export': string
			/**
			 * I​m​p​o​r​t
			 */
			'import': string
		}
	}
}

export type Namespaces =
	| 'ui_graphql'

type DisallowNamespaces = {
	/**
	 * reserved for 'ui_graphql'-namespace\
	 * you need to use the `./ui_graphql/index.ts` file instead
	 */
	ui_graphql?: "[typesafe-i18n] reserved for 'ui_graphql'-namespace. You need to use the `./ui_graphql/index.ts` file instead."
}

export type TranslationFunctions = {
	ui_graphql: {
		table: {
			/**
			 * Remove row?
			 */
			removeModalTitle: () => LocalizedString
			/**
			 * Edit
			 */
			editBtn: () => LocalizedString
			/**
			 * Remove
			 */
			removeBtn: () => LocalizedString
			/**
			 * Cancel
			 */
			cancelBtn: () => LocalizedString
			th: {
				/**
				 * filter
				 */
				filter: () => LocalizedString
				/**
				 * cancel
				 */
				cancel: () => LocalizedString
				/**
				 * No Sort
				 */
				noSort: () => LocalizedString
				/**
				 * ASC
				 */
				asc: () => LocalizedString
				/**
				 * DESC
				 */
				desc: () => LocalizedString
				/**
				 * Equals
				 */
				eq: () => LocalizedString
				/**
				 * Not Equals
				 */
				neq: () => LocalizedString
				/**
				 * Like
				 */
				lk: () => LocalizedString
				/**
				 * Not Like
				 */
				nlk: () => LocalizedString
				/**
				 * Greater Than
				 */
				gt: () => LocalizedString
				/**
				 * Greater Equals
				 */
				gte: () => LocalizedString
				/**
				 * Less Than
				 */
				lt: () => LocalizedString
				/**
				 * Less Equals
				 */
				lte: () => LocalizedString
				/**
				 * Is Null
				 */
				nil: () => LocalizedString
				/**
				 * Not Null
				 */
				nnil: () => LocalizedString
				/**
				 * In
				 */
				'in': () => LocalizedString
				/**
				 * Not In
				 */
				nin: () => LocalizedString
				/**
				 * Between
				 */
				bt: () => LocalizedString
				/**
				 * Not Between
				 */
				nbt: () => LocalizedString
				/**
				 * Filter..
				 */
				filterPlaceholder: () => LocalizedString
			}
			td: {
				/**
				 * save
				 */
				save: () => LocalizedString
				/**
				 * clear
				 */
				clear: () => LocalizedString
			}
		}
		grid: {
			buttons: {
				/**
				 * Refresh
				 */
				refresh: () => LocalizedString
				/**
				 * Save
				 */
				save: () => LocalizedString
				/**
				 * New
				 */
				'new': () => LocalizedString
				/**
				 * Append
				 */
				append: () => LocalizedString
				/**
				 * Remove
				 */
				remove: () => LocalizedString
				/**
				 * ok
				 */
				ok: () => LocalizedString
				/**
				 * Canel
				 */
				canel: () => LocalizedString
				/**
				 * Export
				 */
				'export': () => LocalizedString
				/**
				 * Import
				 */
				'import': () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
