// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	errors: NamespaceErrorsTranslation,
	graphence: NamespaceGraphenceTranslation,
	graphql: NamespaceGraphqlTranslation,
	ui: NamespaceUiTranslation,
	ui_graphql: NamespaceUiGraphqlTranslation
}

type RootTranslation = {}

export type NamespaceErrorsTranslation = {
	code: {
		/**
		 * A​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​f​a​i​l​e​d
		 */
		'-40101': string
		/**
		 * R​e​s​o​u​r​c​e​ ​h​a​s​ ​b​e​e​n​ ​u​p​d​a​t​e​d
		 */
		'-40900': string
		/**
		 * E​x​i​s​t​e​d​ ​u​n​i​q​u​e​ ​v​a​l​u​e​s
		 */
		'-40901': string
		/**
		 * R​e​q​u​e​t​ ​e​r​r​o​r
		 */
		'-99999': string
	}
}

export type NamespaceGraphenceTranslation = {
	login: {
		/**
		 * F​u​l​l​-​s​t​a​c​k​ ​G​r​a​p​h​Q​L​ ​d​e​v​e​l​o​p​m​e​n​t​ ​p​l​a​t​f​o​r​m​,​ ​p​o​w​e​r​e​d​ ​b​y​ ​G​r​a​p​h​Q​L​ ​S​v​e​l​t​e​ ​a​n​d​ ​R​e​a​c​t​o​r​ ​J​a​v​a
		 */
		detail: string
		/**
		 * A​c​c​o​u​n​t
		 */
		account: string
		/**
		 * L​o​g​i​n
		 */
		login: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		password: string
		/**
		 * F​o​r​g​o​t​ ​p​a​s​s​w​o​r​d​?
		 */
		forgot: string
	}
	message: {
		/**
		 * S​a​v​e​ ​s​u​c​c​e​s​s
		 */
		saveSuccess: string
		/**
		 * C​r​e​a​t​e​ ​s​u​c​c​e​s​s
		 */
		createSuccess: string
		/**
		 * R​e​m​o​v​e​ ​s​u​c​c​e​s​s
		 */
		removeSuccess: string
		/**
		 * U​n​b​i​n​d​ ​s​u​c​c​e​s​s
		 */
		unbindSuccess: string
		/**
		 * R​e​q​u​e​s​t​ ​f​a​i​l​e​d
		 */
		requestFailed: string
		/**
		 * S​a​v​e​ ​f​a​i​l​e​d
		 */
		saveFailed: string
		/**
		 * C​r​e​a​t​e​ ​f​a​i​l​e​d
		 */
		createFailed: string
		/**
		 * R​e​m​o​v​e​ ​f​a​i​l​e​d
		 */
		removeFailed: string
		/**
		 * U​n​b​i​n​d​ ​f​a​i​l​e​d
		 */
		unbindFailed: string
	}
	path: {
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * C​r​e​a​t​e​ ​{​n​a​m​e​}
		 * @param {string} name
		 */
		create: RequiredParams<'name'>
		/**
		 * S​e​l​e​c​t​ ​{​n​a​m​e​}
		 * @param {string} name
		 */
		select: RequiredParams<'name'>
	}
	components: {
		search: {
			/**
			 * S​e​a​r​c​h
			 */
			label: string
		}
		table: {
			/**
			 * R​e​m​o​v​e​ ​r​o​w​?
			 */
			removeModalTitle: string
			/**
			 * U​n​b​i​n​d​ ​r​o​w​?
			 */
			unbindModalTitle: string
			/**
			 * E​d​i​t
			 */
			editBtn: string
			/**
			 * R​e​m​o​v​e
			 */
			removeBtn: string
			/**
			 * U​n​b​i​n​d
			 */
			unbindBtn: string
			/**
			 * S​e​l​e​c​t
			 */
			selectBtn: string
		}
		sideBarMenu: {
			/**
			 * M​o​d​u​l​e​s
			 */
			modules: string
			/**
			 * S​t​a​t​i​s​t​i​c​s
			 */
			statistics: string
			/**
			 * G​r​i​d
			 */
			grid: string
			/**
			 * T​a​b​l​e
			 */
			table: string
			/**
			 * B​a​r
			 */
			bar: string
			/**
			 * L​i​n​e
			 */
			line: string
			/**
			 * P​i​e
			 */
			pie: string
			/**
			 * E​d​i​t
			 */
			mutation: string
		}
		userMenu: {
			/**
			 * P​r​o​f​i​l​e
			 */
			profile: string
			/**
			 * R​e​s​e​t​ ​p​a​s​s​w​o​r​d
			 */
			password: string
			/**
			 * L​o​g​o​u​t
			 */
			logout: string
		}
		resetPassword: {
			/**
			 * O​r​i​g​i​n​a​l​ ​p​a​s​s​w​o​r​d
			 */
			password: string
			/**
			 * N​e​w​ ​p​a​s​s​w​o​r​d
			 */
			newPassword: string
			/**
			 * R​e​p​e​a​t​ ​n​e​w​ ​P​a​s​s​w​o​r​d
			 */
			repeatNewPassword: string
			/**
			 * I​n​c​o​n​s​i​s​t​e​n​t
			 */
			inconsistent: string
		}
		agg: {
			/**
			 * C​o​l​u​m​n​s
			 */
			columns: string
			/**
			 * G​r​o​u​p​ ​B​y
			 */
			groupBy: string
			/**
			 * O​r​d​e​r​ ​B​y
			 */
			orderBy: string
			/**
			 * O​p​t​i​o​n​s
			 */
			option: string
			/**
			 * F​i​l​t​e​r
			 */
			filter: string
			/**
			 * B​o​o​k​m​a​r​k
			 */
			bookmark: string
		}
		query: {
			/**
			 * C​o​l​u​m​n​s
			 */
			columns: string
			/**
			 * J​o​i​n
			 */
			join: string
			/**
			 * J​o​i​n​ ​C​o​l​u​m​n​s
			 */
			joinColumns: string
			/**
			 * O​r​d​e​r​ ​B​y
			 */
			orderBy: string
			/**
			 * O​p​t​i​o​n​s
			 */
			option: string
			/**
			 * F​i​l​t​e​r
			 */
			filter: string
			/**
			 * B​o​o​k​m​a​r​k
			 */
			bookmark: string
		}
		grid: {
			boolean: {
				/**
				 * Y​e​s
				 */
				'true': string
				/**
				 * N​o
				 */
				'false': string
			}
			captions: {
				/**
				 * F​i​l​t​e​r
				 */
				title: string
				/**
				 * S​a​v​e
				 */
				save: string
				/**
				 * R​e​s​e​t
				 */
				reset: string
				/**
				 * O​K
				 */
				ok: string
				/**
				 * C​a​n​c​e​l
				 */
				cancel: string
				/**
				 * A​d​d
				 */
				add: string
				/**
				 * E​n​t​e​r​ ​v​a​l​u​e
				 */
				placeholder: string
				/**
				 * A​n​d
				 */
				and: string
				/**
				 * O​r
				 */
				or: string
			}
			filterNames: {
				/**
				 * N​o​n​e
				 */
				none: string
				/**
				 * N​o​t​ ​s​e​t
				 */
				empty: string
				/**
				 * S​e​t
				 */
				notEmpty: string
				/**
				 * E​q​u​a​l
				 */
				eq: string
				/**
				 * N​o​t​ ​e​q​u​a​l
				 */
				notEq: string
				/**
				 * B​e​g​i​n​s​ ​w​i​t​h
				 */
				begins: string
				/**
				 * C​o​n​t​a​i​n​s
				 */
				contains: string
				/**
				 * D​o​e​s​ ​n​o​t​ ​c​o​n​t​a​i​n
				 */
				notContains: string
				/**
				 * =
				 */
				eqN: string
				/**
				 * !​=
				 */
				neqN: string
				/**
				 * >
				 */
				gt: string
				/**
				 * >​=
				 */
				gte: string
				/**
				 * <
				 */
				lt: string
				/**
				 * <​=
				 */
				lte: string
			}
		}
	}
}

export type NamespaceGraphqlTranslation = {
	objects: {
		Current: {
			/**
			 * C​u​r​r​e​n​t
			 */
			name: string
			fields: {
				id: {
					/**
					 * i​d
					 */
					name: string
				}
				name: {
					/**
					 * n​a​m​e
					 */
					name: string
				}
				lastName: {
					/**
					 * l​a​s​t​N​a​m​e
					 */
					name: string
				}
				login: {
					/**
					 * l​o​g​i​n
					 */
					name: string
				}
				realmId: {
					/**
					 * r​e​a​l​m​I​d
					 */
					name: string
				}
				groups: {
					/**
					 * g​r​o​u​p​s
					 */
					name: string
				}
				roles: {
					/**
					 * r​o​l​e​s
					 */
					name: string
				}
			}
		}
		Group: {
			/**
			 * G​r​o​u​p
			 */
			name: string
			fields: {
				id: {
					/**
					 * i​d
					 */
					name: string
				}
				name: {
					/**
					 * n​a​m​e
					 */
					name: string
				}
				description: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n
					 */
					name: string
				}
				path: {
					/**
					 * p​a​t​h
					 */
					name: string
				}
				deep: {
					/**
					 * d​e​e​p
					 */
					name: string
				}
				parentId: {
					/**
					 * p​a​r​e​n​t​I​d
					 */
					name: string
				}
				parent: {
					/**
					 * p​a​r​e​n​t
					 */
					name: string
				}
				subGroups: {
					/**
					 * s​u​b​G​r​o​u​p​s
					 */
					name: string
				}
				users: {
					/**
					 * u​s​e​r​s
					 */
					name: string
				}
				roles: {
					/**
					 * r​o​l​e​s
					 */
					name: string
				}
				realm: {
					/**
					 * r​e​a​l​m
					 */
					name: string
				}
				isDeprecated: {
					/**
					 * i​s​D​e​p​r​e​c​a​t​e​d
					 */
					name: string
				}
				version: {
					/**
					 * v​e​r​s​i​o​n
					 */
					name: string
				}
				realmId: {
					/**
					 * r​e​a​l​m​I​d
					 */
					name: string
				}
				createUserId: {
					/**
					 * c​r​e​a​t​e​U​s​e​r​I​d
					 */
					name: string
				}
				createTime: {
					/**
					 * c​r​e​a​t​e​T​i​m​e
					 */
					name: string
				}
				updateUserId: {
					/**
					 * u​p​d​a​t​e​U​s​e​r​I​d
					 */
					name: string
				}
				updateTime: {
					/**
					 * u​p​d​a​t​e​T​i​m​e
					 */
					name: string
				}
				createGroupId: {
					/**
					 * c​r​e​a​t​e​G​r​o​u​p​I​d
					 */
					name: string
				}
				groupUserRelation: {
					/**
					 * g​r​o​u​p​U​s​e​r​R​e​l​a​t​i​o​n
					 */
					name: string
				}
				groupRoleRelation: {
					/**
					 * g​r​o​u​p​R​o​l​e​R​e​l​a​t​i​o​n
					 */
					name: string
				}
				subGroupsAggregate: {
					/**
					 * s​u​b​G​r​o​u​p​s​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				subGroupsConnection: {
					/**
					 * s​u​b​G​r​o​u​p​s​C​o​n​n​e​c​t​i​o​n
					 */
					name: string
				}
				usersAggregate: {
					/**
					 * u​s​e​r​s​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				usersConnection: {
					/**
					 * u​s​e​r​s​C​o​n​n​e​c​t​i​o​n
					 */
					name: string
				}
				rolesAggregate: {
					/**
					 * r​o​l​e​s​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				rolesConnection: {
					/**
					 * r​o​l​e​s​C​o​n​n​e​c​t​i​o​n
					 */
					name: string
				}
				groupUserRelationAggregate: {
					/**
					 * g​r​o​u​p​U​s​e​r​R​e​l​a​t​i​o​n​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				groupUserRelationConnection: {
					/**
					 * g​r​o​u​p​U​s​e​r​R​e​l​a​t​i​o​n​C​o​n​n​e​c​t​i​o​n
					 */
					name: string
				}
				groupRoleRelationAggregate: {
					/**
					 * g​r​o​u​p​R​o​l​e​R​e​l​a​t​i​o​n​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				groupRoleRelationConnection: {
					/**
					 * g​r​o​u​p​R​o​l​e​R​e​l​a​t​i​o​n​C​o​n​n​e​c​t​i​o​n
					 */
					name: string
				}
				idCount: {
					/**
					 * i​d​C​o​u​n​t
					 */
					name: string
				}
				idMax: {
					/**
					 * i​d​M​a​x
					 */
					name: string
				}
				idMin: {
					/**
					 * i​d​M​i​n
					 */
					name: string
				}
				nameCount: {
					/**
					 * n​a​m​e​C​o​u​n​t
					 */
					name: string
				}
				nameMax: {
					/**
					 * n​a​m​e​M​a​x
					 */
					name: string
				}
				nameMin: {
					/**
					 * n​a​m​e​M​i​n
					 */
					name: string
				}
				descriptionCount: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​C​o​u​n​t
					 */
					name: string
				}
				descriptionMax: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​M​a​x
					 */
					name: string
				}
				descriptionMin: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​M​i​n
					 */
					name: string
				}
				pathCount: {
					/**
					 * p​a​t​h​C​o​u​n​t
					 */
					name: string
				}
				pathMax: {
					/**
					 * p​a​t​h​M​a​x
					 */
					name: string
				}
				pathMin: {
					/**
					 * p​a​t​h​M​i​n
					 */
					name: string
				}
				parentIdCount: {
					/**
					 * p​a​r​e​n​t​I​d​C​o​u​n​t
					 */
					name: string
				}
				parentIdMax: {
					/**
					 * p​a​r​e​n​t​I​d​M​a​x
					 */
					name: string
				}
				parentIdMin: {
					/**
					 * p​a​r​e​n​t​I​d​M​i​n
					 */
					name: string
				}
				deepCount: {
					/**
					 * d​e​e​p​C​o​u​n​t
					 */
					name: string
				}
				deepSum: {
					/**
					 * d​e​e​p​S​u​m
					 */
					name: string
				}
				deepAvg: {
					/**
					 * d​e​e​p​A​v​g
					 */
					name: string
				}
				deepMax: {
					/**
					 * d​e​e​p​M​a​x
					 */
					name: string
				}
				deepMin: {
					/**
					 * d​e​e​p​M​i​n
					 */
					name: string
				}
				syncGroupPolicy: {
					/**
					 * s​y​n​c​G​r​o​u​p​P​o​l​i​c​y
					 */
					name: string
				}
			}
		}
		GroupRoleRelation: {
			/**
			 * G​r​o​u​p​R​o​l​e​R​e​l​a​t​i​o​n
			 */
			name: string
			fields: {
				id: {
					/**
					 * i​d
					 */
					name: string
				}
				roleRef: {
					/**
					 * r​o​l​e​R​e​f
					 */
					name: string
				}
				role: {
					/**
					 * r​o​l​e
					 */
					name: string
				}
				groupRef: {
					/**
					 * g​r​o​u​p​R​e​f
					 */
					name: string
				}
				group: {
					/**
					 * g​r​o​u​p
					 */
					name: string
				}
				isDeprecated: {
					/**
					 * i​s​D​e​p​r​e​c​a​t​e​d
					 */
					name: string
				}
				version: {
					/**
					 * v​e​r​s​i​o​n
					 */
					name: string
				}
				realmId: {
					/**
					 * r​e​a​l​m​I​d
					 */
					name: string
				}
				createUserId: {
					/**
					 * c​r​e​a​t​e​U​s​e​r​I​d
					 */
					name: string
				}
				createTime: {
					/**
					 * c​r​e​a​t​e​T​i​m​e
					 */
					name: string
				}
				updateUserId: {
					/**
					 * u​p​d​a​t​e​U​s​e​r​I​d
					 */
					name: string
				}
				updateTime: {
					/**
					 * u​p​d​a​t​e​T​i​m​e
					 */
					name: string
				}
				createGroupId: {
					/**
					 * c​r​e​a​t​e​G​r​o​u​p​I​d
					 */
					name: string
				}
				idCount: {
					/**
					 * i​d​C​o​u​n​t
					 */
					name: string
				}
				idMax: {
					/**
					 * i​d​M​a​x
					 */
					name: string
				}
				idMin: {
					/**
					 * i​d​M​i​n
					 */
					name: string
				}
				roleRefCount: {
					/**
					 * r​o​l​e​R​e​f​C​o​u​n​t
					 */
					name: string
				}
				roleRefMax: {
					/**
					 * r​o​l​e​R​e​f​M​a​x
					 */
					name: string
				}
				roleRefMin: {
					/**
					 * r​o​l​e​R​e​f​M​i​n
					 */
					name: string
				}
				groupRefCount: {
					/**
					 * g​r​o​u​p​R​e​f​C​o​u​n​t
					 */
					name: string
				}
				groupRefMax: {
					/**
					 * g​r​o​u​p​R​e​f​M​a​x
					 */
					name: string
				}
				groupRefMin: {
					/**
					 * g​r​o​u​p​R​e​f​M​i​n
					 */
					name: string
				}
			}
		}
		GroupUserRelation: {
			/**
			 * G​r​o​u​p​U​s​e​r​R​e​l​a​t​i​o​n
			 */
			name: string
			fields: {
				id: {
					/**
					 * i​d
					 */
					name: string
				}
				userRef: {
					/**
					 * u​s​e​r​R​e​f
					 */
					name: string
				}
				user: {
					/**
					 * u​s​e​r
					 */
					name: string
				}
				groupRef: {
					/**
					 * g​r​o​u​p​R​e​f
					 */
					name: string
				}
				group: {
					/**
					 * g​r​o​u​p
					 */
					name: string
				}
				isDeprecated: {
					/**
					 * i​s​D​e​p​r​e​c​a​t​e​d
					 */
					name: string
				}
				version: {
					/**
					 * v​e​r​s​i​o​n
					 */
					name: string
				}
				realmId: {
					/**
					 * r​e​a​l​m​I​d
					 */
					name: string
				}
				createUserId: {
					/**
					 * c​r​e​a​t​e​U​s​e​r​I​d
					 */
					name: string
				}
				createTime: {
					/**
					 * c​r​e​a​t​e​T​i​m​e
					 */
					name: string
				}
				updateUserId: {
					/**
					 * u​p​d​a​t​e​U​s​e​r​I​d
					 */
					name: string
				}
				updateTime: {
					/**
					 * u​p​d​a​t​e​T​i​m​e
					 */
					name: string
				}
				createGroupId: {
					/**
					 * c​r​e​a​t​e​G​r​o​u​p​I​d
					 */
					name: string
				}
				idCount: {
					/**
					 * i​d​C​o​u​n​t
					 */
					name: string
				}
				idMax: {
					/**
					 * i​d​M​a​x
					 */
					name: string
				}
				idMin: {
					/**
					 * i​d​M​i​n
					 */
					name: string
				}
				userRefCount: {
					/**
					 * u​s​e​r​R​e​f​C​o​u​n​t
					 */
					name: string
				}
				userRefMax: {
					/**
					 * u​s​e​r​R​e​f​M​a​x
					 */
					name: string
				}
				userRefMin: {
					/**
					 * u​s​e​r​R​e​f​M​i​n
					 */
					name: string
				}
				groupRefCount: {
					/**
					 * g​r​o​u​p​R​e​f​C​o​u​n​t
					 */
					name: string
				}
				groupRefMax: {
					/**
					 * g​r​o​u​p​R​e​f​M​a​x
					 */
					name: string
				}
				groupRefMin: {
					/**
					 * g​r​o​u​p​R​e​f​M​i​n
					 */
					name: string
				}
			}
		}
		Permission: {
			/**
			 * P​e​r​m​i​s​s​i​o​n
			 */
			name: string
			fields: {
				name: {
					/**
					 * n​a​m​e
					 */
					name: string
				}
				description: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n
					 */
					name: string
				}
				field: {
					/**
					 * f​i​e​l​d
					 */
					name: string
				}
				type: {
					/**
					 * t​y​p​e
					 */
					name: string
				}
				permissionType: {
					/**
					 * p​e​r​m​i​s​s​i​o​n​T​y​p​e
					 */
					name: string
				}
				roles: {
					/**
					 * r​o​l​e​s
					 */
					name: string
				}
				realm: {
					/**
					 * r​e​a​l​m
					 */
					name: string
				}
				isDeprecated: {
					/**
					 * i​s​D​e​p​r​e​c​a​t​e​d
					 */
					name: string
				}
				version: {
					/**
					 * v​e​r​s​i​o​n
					 */
					name: string
				}
				realmId: {
					/**
					 * r​e​a​l​m​I​d
					 */
					name: string
				}
				createUserId: {
					/**
					 * c​r​e​a​t​e​U​s​e​r​I​d
					 */
					name: string
				}
				createTime: {
					/**
					 * c​r​e​a​t​e​T​i​m​e
					 */
					name: string
				}
				updateUserId: {
					/**
					 * u​p​d​a​t​e​U​s​e​r​I​d
					 */
					name: string
				}
				updateTime: {
					/**
					 * u​p​d​a​t​e​T​i​m​e
					 */
					name: string
				}
				createGroupId: {
					/**
					 * c​r​e​a​t​e​G​r​o​u​p​I​d
					 */
					name: string
				}
				permissionRoleRelation: {
					/**
					 * p​e​r​m​i​s​s​i​o​n​R​o​l​e​R​e​l​a​t​i​o​n
					 */
					name: string
				}
				rolesAggregate: {
					/**
					 * r​o​l​e​s​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				rolesConnection: {
					/**
					 * r​o​l​e​s​C​o​n​n​e​c​t​i​o​n
					 */
					name: string
				}
				permissionRoleRelationAggregate: {
					/**
					 * p​e​r​m​i​s​s​i​o​n​R​o​l​e​R​e​l​a​t​i​o​n​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				permissionRoleRelationConnection: {
					/**
					 * p​e​r​m​i​s​s​i​o​n​R​o​l​e​R​e​l​a​t​i​o​n​C​o​n​n​e​c​t​i​o​n
					 */
					name: string
				}
				nameCount: {
					/**
					 * n​a​m​e​C​o​u​n​t
					 */
					name: string
				}
				nameMax: {
					/**
					 * n​a​m​e​M​a​x
					 */
					name: string
				}
				nameMin: {
					/**
					 * n​a​m​e​M​i​n
					 */
					name: string
				}
				descriptionCount: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​C​o​u​n​t
					 */
					name: string
				}
				descriptionMax: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​M​a​x
					 */
					name: string
				}
				descriptionMin: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​M​i​n
					 */
					name: string
				}
				fieldCount: {
					/**
					 * f​i​e​l​d​C​o​u​n​t
					 */
					name: string
				}
				fieldMax: {
					/**
					 * f​i​e​l​d​M​a​x
					 */
					name: string
				}
				fieldMin: {
					/**
					 * f​i​e​l​d​M​i​n
					 */
					name: string
				}
				typeCount: {
					/**
					 * t​y​p​e​C​o​u​n​t
					 */
					name: string
				}
				typeMax: {
					/**
					 * t​y​p​e​M​a​x
					 */
					name: string
				}
				typeMin: {
					/**
					 * t​y​p​e​M​i​n
					 */
					name: string
				}
				permissionTypeCount: {
					/**
					 * p​e​r​m​i​s​s​i​o​n​T​y​p​e​C​o​u​n​t
					 */
					name: string
				}
				permissionTypeMax: {
					/**
					 * p​e​r​m​i​s​s​i​o​n​T​y​p​e​M​a​x
					 */
					name: string
				}
				permissionTypeMin: {
					/**
					 * p​e​r​m​i​s​s​i​o​n​T​y​p​e​M​i​n
					 */
					name: string
				}
				syncPermissionPolicy: {
					/**
					 * s​y​n​c​P​e​r​m​i​s​s​i​o​n​P​o​l​i​c​y
					 */
					name: string
				}
			}
		}
		PermissionRoleRelation: {
			/**
			 * P​e​r​m​i​s​s​i​o​n​R​o​l​e​R​e​l​a​t​i​o​n
			 */
			name: string
			fields: {
				id: {
					/**
					 * i​d
					 */
					name: string
				}
				roleRef: {
					/**
					 * r​o​l​e​R​e​f
					 */
					name: string
				}
				role: {
					/**
					 * r​o​l​e
					 */
					name: string
				}
				permissionRef: {
					/**
					 * p​e​r​m​i​s​s​i​o​n​R​e​f
					 */
					name: string
				}
				permission: {
					/**
					 * p​e​r​m​i​s​s​i​o​n
					 */
					name: string
				}
				isDeprecated: {
					/**
					 * i​s​D​e​p​r​e​c​a​t​e​d
					 */
					name: string
				}
				version: {
					/**
					 * v​e​r​s​i​o​n
					 */
					name: string
				}
				realmId: {
					/**
					 * r​e​a​l​m​I​d
					 */
					name: string
				}
				createUserId: {
					/**
					 * c​r​e​a​t​e​U​s​e​r​I​d
					 */
					name: string
				}
				createTime: {
					/**
					 * c​r​e​a​t​e​T​i​m​e
					 */
					name: string
				}
				updateUserId: {
					/**
					 * u​p​d​a​t​e​U​s​e​r​I​d
					 */
					name: string
				}
				updateTime: {
					/**
					 * u​p​d​a​t​e​T​i​m​e
					 */
					name: string
				}
				createGroupId: {
					/**
					 * c​r​e​a​t​e​G​r​o​u​p​I​d
					 */
					name: string
				}
				idCount: {
					/**
					 * i​d​C​o​u​n​t
					 */
					name: string
				}
				idMax: {
					/**
					 * i​d​M​a​x
					 */
					name: string
				}
				idMin: {
					/**
					 * i​d​M​i​n
					 */
					name: string
				}
				roleRefCount: {
					/**
					 * r​o​l​e​R​e​f​C​o​u​n​t
					 */
					name: string
				}
				roleRefMax: {
					/**
					 * r​o​l​e​R​e​f​M​a​x
					 */
					name: string
				}
				roleRefMin: {
					/**
					 * r​o​l​e​R​e​f​M​i​n
					 */
					name: string
				}
				permissionRefCount: {
					/**
					 * p​e​r​m​i​s​s​i​o​n​R​e​f​C​o​u​n​t
					 */
					name: string
				}
				permissionRefMax: {
					/**
					 * p​e​r​m​i​s​s​i​o​n​R​e​f​M​a​x
					 */
					name: string
				}
				permissionRefMin: {
					/**
					 * p​e​r​m​i​s​s​i​o​n​R​e​f​M​i​n
					 */
					name: string
				}
			}
		}
		Policy: {
			/**
			 * P​o​l​i​c​y
			 */
			name: string
			fields: {
				id: {
					/**
					 * i​d
					 */
					name: string
				}
				policy: {
					/**
					 * p​o​l​i​c​y
					 */
					name: string
				}
				v0: {
					/**
					 * v​0
					 */
					name: string
				}
				v1: {
					/**
					 * v​1
					 */
					name: string
				}
				v2: {
					/**
					 * v​2
					 */
					name: string
				}
				v3: {
					/**
					 * v​3
					 */
					name: string
				}
				v4: {
					/**
					 * v​4
					 */
					name: string
				}
				v5: {
					/**
					 * v​5
					 */
					name: string
				}
			}
		}
		Realm: {
			/**
			 * R​e​a​l​m
			 */
			name: string
			fields: {
				id: {
					/**
					 * i​d
					 */
					name: string
				}
				name: {
					/**
					 * n​a​m​e
					 */
					name: string
				}
				description: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n
					 */
					name: string
				}
				isDeprecated: {
					/**
					 * i​s​D​e​p​r​e​c​a​t​e​d
					 */
					name: string
				}
				version: {
					/**
					 * v​e​r​s​i​o​n
					 */
					name: string
				}
				realmId: {
					/**
					 * r​e​a​l​m​I​d
					 */
					name: string
				}
				createUserId: {
					/**
					 * c​r​e​a​t​e​U​s​e​r​I​d
					 */
					name: string
				}
				createTime: {
					/**
					 * c​r​e​a​t​e​T​i​m​e
					 */
					name: string
				}
				updateUserId: {
					/**
					 * u​p​d​a​t​e​U​s​e​r​I​d
					 */
					name: string
				}
				updateTime: {
					/**
					 * u​p​d​a​t​e​T​i​m​e
					 */
					name: string
				}
				createGroupId: {
					/**
					 * c​r​e​a​t​e​G​r​o​u​p​I​d
					 */
					name: string
				}
				idCount: {
					/**
					 * i​d​C​o​u​n​t
					 */
					name: string
				}
				idMax: {
					/**
					 * i​d​M​a​x
					 */
					name: string
				}
				idMin: {
					/**
					 * i​d​M​i​n
					 */
					name: string
				}
				nameCount: {
					/**
					 * n​a​m​e​C​o​u​n​t
					 */
					name: string
				}
				nameMax: {
					/**
					 * n​a​m​e​M​a​x
					 */
					name: string
				}
				nameMin: {
					/**
					 * n​a​m​e​M​i​n
					 */
					name: string
				}
				descriptionCount: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​C​o​u​n​t
					 */
					name: string
				}
				descriptionMax: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​M​a​x
					 */
					name: string
				}
				descriptionMin: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​M​i​n
					 */
					name: string
				}
			}
		}
		Role: {
			/**
			 * R​o​l​e
			 */
			name: string
			fields: {
				id: {
					/**
					 * i​d
					 */
					name: string
				}
				name: {
					/**
					 * n​a​m​e
					 */
					name: string
				}
				description: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n
					 */
					name: string
				}
				users: {
					/**
					 * u​s​e​r​s
					 */
					name: string
				}
				groups: {
					/**
					 * g​r​o​u​p​s
					 */
					name: string
				}
				composites: {
					/**
					 * c​o​m​p​o​s​i​t​e​s
					 */
					name: string
				}
				permissions: {
					/**
					 * p​e​r​m​i​s​s​i​o​n​s
					 */
					name: string
				}
				realm: {
					/**
					 * r​e​a​l​m
					 */
					name: string
				}
				isDeprecated: {
					/**
					 * i​s​D​e​p​r​e​c​a​t​e​d
					 */
					name: string
				}
				version: {
					/**
					 * v​e​r​s​i​o​n
					 */
					name: string
				}
				realmId: {
					/**
					 * r​e​a​l​m​I​d
					 */
					name: string
				}
				createUserId: {
					/**
					 * c​r​e​a​t​e​U​s​e​r​I​d
					 */
					name: string
				}
				createTime: {
					/**
					 * c​r​e​a​t​e​T​i​m​e
					 */
					name: string
				}
				updateUserId: {
					/**
					 * u​p​d​a​t​e​U​s​e​r​I​d
					 */
					name: string
				}
				updateTime: {
					/**
					 * u​p​d​a​t​e​T​i​m​e
					 */
					name: string
				}
				createGroupId: {
					/**
					 * c​r​e​a​t​e​G​r​o​u​p​I​d
					 */
					name: string
				}
				roleUserRelation: {
					/**
					 * r​o​l​e​U​s​e​r​R​e​l​a​t​i​o​n
					 */
					name: string
				}
				groupRoleRelation: {
					/**
					 * g​r​o​u​p​R​o​l​e​R​e​l​a​t​i​o​n
					 */
					name: string
				}
				roleCompositeRelation: {
					/**
					 * r​o​l​e​C​o​m​p​o​s​i​t​e​R​e​l​a​t​i​o​n
					 */
					name: string
				}
				permissionRoleRelation: {
					/**
					 * p​e​r​m​i​s​s​i​o​n​R​o​l​e​R​e​l​a​t​i​o​n
					 */
					name: string
				}
				usersAggregate: {
					/**
					 * u​s​e​r​s​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				usersConnection: {
					/**
					 * u​s​e​r​s​C​o​n​n​e​c​t​i​o​n
					 */
					name: string
				}
				groupsAggregate: {
					/**
					 * g​r​o​u​p​s​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				groupsConnection: {
					/**
					 * g​r​o​u​p​s​C​o​n​n​e​c​t​i​o​n
					 */
					name: string
				}
				compositesAggregate: {
					/**
					 * c​o​m​p​o​s​i​t​e​s​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				compositesConnection: {
					/**
					 * c​o​m​p​o​s​i​t​e​s​C​o​n​n​e​c​t​i​o​n
					 */
					name: string
				}
				permissionsAggregate: {
					/**
					 * p​e​r​m​i​s​s​i​o​n​s​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				permissionsConnection: {
					/**
					 * p​e​r​m​i​s​s​i​o​n​s​C​o​n​n​e​c​t​i​o​n
					 */
					name: string
				}
				roleUserRelationAggregate: {
					/**
					 * r​o​l​e​U​s​e​r​R​e​l​a​t​i​o​n​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				roleUserRelationConnection: {
					/**
					 * r​o​l​e​U​s​e​r​R​e​l​a​t​i​o​n​C​o​n​n​e​c​t​i​o​n
					 */
					name: string
				}
				groupRoleRelationAggregate: {
					/**
					 * g​r​o​u​p​R​o​l​e​R​e​l​a​t​i​o​n​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				groupRoleRelationConnection: {
					/**
					 * g​r​o​u​p​R​o​l​e​R​e​l​a​t​i​o​n​C​o​n​n​e​c​t​i​o​n
					 */
					name: string
				}
				roleCompositeRelationAggregate: {
					/**
					 * r​o​l​e​C​o​m​p​o​s​i​t​e​R​e​l​a​t​i​o​n​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				roleCompositeRelationConnection: {
					/**
					 * r​o​l​e​C​o​m​p​o​s​i​t​e​R​e​l​a​t​i​o​n​C​o​n​n​e​c​t​i​o​n
					 */
					name: string
				}
				permissionRoleRelationAggregate: {
					/**
					 * p​e​r​m​i​s​s​i​o​n​R​o​l​e​R​e​l​a​t​i​o​n​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				permissionRoleRelationConnection: {
					/**
					 * p​e​r​m​i​s​s​i​o​n​R​o​l​e​R​e​l​a​t​i​o​n​C​o​n​n​e​c​t​i​o​n
					 */
					name: string
				}
				idCount: {
					/**
					 * i​d​C​o​u​n​t
					 */
					name: string
				}
				idMax: {
					/**
					 * i​d​M​a​x
					 */
					name: string
				}
				idMin: {
					/**
					 * i​d​M​i​n
					 */
					name: string
				}
				nameCount: {
					/**
					 * n​a​m​e​C​o​u​n​t
					 */
					name: string
				}
				nameMax: {
					/**
					 * n​a​m​e​M​a​x
					 */
					name: string
				}
				nameMin: {
					/**
					 * n​a​m​e​M​i​n
					 */
					name: string
				}
				descriptionCount: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​C​o​u​n​t
					 */
					name: string
				}
				descriptionMax: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​M​a​x
					 */
					name: string
				}
				descriptionMin: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​M​i​n
					 */
					name: string
				}
				syncRolePolicy: {
					/**
					 * s​y​n​c​R​o​l​e​P​o​l​i​c​y
					 */
					name: string
				}
			}
		}
		RoleCompositeRelation: {
			/**
			 * R​o​l​e​C​o​m​p​o​s​i​t​e​R​e​l​a​t​i​o​n
			 */
			name: string
			fields: {
				id: {
					/**
					 * i​d
					 */
					name: string
				}
				roleRef: {
					/**
					 * r​o​l​e​R​e​f
					 */
					name: string
				}
				role: {
					/**
					 * r​o​l​e
					 */
					name: string
				}
				compositeRef: {
					/**
					 * c​o​m​p​o​s​i​t​e​R​e​f
					 */
					name: string
				}
				composite: {
					/**
					 * c​o​m​p​o​s​i​t​e
					 */
					name: string
				}
				isDeprecated: {
					/**
					 * i​s​D​e​p​r​e​c​a​t​e​d
					 */
					name: string
				}
				version: {
					/**
					 * v​e​r​s​i​o​n
					 */
					name: string
				}
				realmId: {
					/**
					 * r​e​a​l​m​I​d
					 */
					name: string
				}
				createUserId: {
					/**
					 * c​r​e​a​t​e​U​s​e​r​I​d
					 */
					name: string
				}
				createTime: {
					/**
					 * c​r​e​a​t​e​T​i​m​e
					 */
					name: string
				}
				updateUserId: {
					/**
					 * u​p​d​a​t​e​U​s​e​r​I​d
					 */
					name: string
				}
				updateTime: {
					/**
					 * u​p​d​a​t​e​T​i​m​e
					 */
					name: string
				}
				createGroupId: {
					/**
					 * c​r​e​a​t​e​G​r​o​u​p​I​d
					 */
					name: string
				}
				idCount: {
					/**
					 * i​d​C​o​u​n​t
					 */
					name: string
				}
				idMax: {
					/**
					 * i​d​M​a​x
					 */
					name: string
				}
				idMin: {
					/**
					 * i​d​M​i​n
					 */
					name: string
				}
				roleRefCount: {
					/**
					 * r​o​l​e​R​e​f​C​o​u​n​t
					 */
					name: string
				}
				roleRefMax: {
					/**
					 * r​o​l​e​R​e​f​M​a​x
					 */
					name: string
				}
				roleRefMin: {
					/**
					 * r​o​l​e​R​e​f​M​i​n
					 */
					name: string
				}
				compositeRefCount: {
					/**
					 * c​o​m​p​o​s​i​t​e​R​e​f​C​o​u​n​t
					 */
					name: string
				}
				compositeRefMax: {
					/**
					 * c​o​m​p​o​s​i​t​e​R​e​f​M​a​x
					 */
					name: string
				}
				compositeRefMin: {
					/**
					 * c​o​m​p​o​s​i​t​e​R​e​f​M​i​n
					 */
					name: string
				}
			}
		}
		RoleUserRelation: {
			/**
			 * R​o​l​e​U​s​e​r​R​e​l​a​t​i​o​n
			 */
			name: string
			fields: {
				id: {
					/**
					 * i​d
					 */
					name: string
				}
				userRef: {
					/**
					 * u​s​e​r​R​e​f
					 */
					name: string
				}
				user: {
					/**
					 * u​s​e​r
					 */
					name: string
				}
				roleRef: {
					/**
					 * r​o​l​e​R​e​f
					 */
					name: string
				}
				role: {
					/**
					 * r​o​l​e
					 */
					name: string
				}
				isDeprecated: {
					/**
					 * i​s​D​e​p​r​e​c​a​t​e​d
					 */
					name: string
				}
				version: {
					/**
					 * v​e​r​s​i​o​n
					 */
					name: string
				}
				realmId: {
					/**
					 * r​e​a​l​m​I​d
					 */
					name: string
				}
				createUserId: {
					/**
					 * c​r​e​a​t​e​U​s​e​r​I​d
					 */
					name: string
				}
				createTime: {
					/**
					 * c​r​e​a​t​e​T​i​m​e
					 */
					name: string
				}
				updateUserId: {
					/**
					 * u​p​d​a​t​e​U​s​e​r​I​d
					 */
					name: string
				}
				updateTime: {
					/**
					 * u​p​d​a​t​e​T​i​m​e
					 */
					name: string
				}
				createGroupId: {
					/**
					 * c​r​e​a​t​e​G​r​o​u​p​I​d
					 */
					name: string
				}
				idCount: {
					/**
					 * i​d​C​o​u​n​t
					 */
					name: string
				}
				idMax: {
					/**
					 * i​d​M​a​x
					 */
					name: string
				}
				idMin: {
					/**
					 * i​d​M​i​n
					 */
					name: string
				}
				userRefCount: {
					/**
					 * u​s​e​r​R​e​f​C​o​u​n​t
					 */
					name: string
				}
				userRefMax: {
					/**
					 * u​s​e​r​R​e​f​M​a​x
					 */
					name: string
				}
				userRefMin: {
					/**
					 * u​s​e​r​R​e​f​M​i​n
					 */
					name: string
				}
				roleRefCount: {
					/**
					 * r​o​l​e​R​e​f​C​o​u​n​t
					 */
					name: string
				}
				roleRefMax: {
					/**
					 * r​o​l​e​R​e​f​M​a​x
					 */
					name: string
				}
				roleRefMin: {
					/**
					 * r​o​l​e​R​e​f​M​i​n
					 */
					name: string
				}
			}
		}
		User: {
			/**
			 * U​s​e​r
			 */
			name: string
			fields: {
				id: {
					/**
					 * i​d
					 */
					name: string
				}
				name: {
					/**
					 * n​a​m​e
					 */
					name: string
				}
				description: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n
					 */
					name: string
				}
				lastName: {
					/**
					 * l​a​s​t​N​a​m​e
					 */
					name: string
				}
				login: {
					/**
					 * l​o​g​i​n
					 */
					name: string
				}
				salt: {
					/**
					 * s​a​l​t
					 */
					name: string
				}
				hash: {
					/**
					 * h​a​s​h
					 */
					name: string
				}
				email: {
					/**
					 * e​m​a​i​l
					 */
					name: string
				}
				phones: {
					/**
					 * p​h​o​n​e​s
					 */
					name: string
				}
				disable: {
					/**
					 * d​i​s​a​b​l​e
					 */
					name: string
				}
				groups: {
					/**
					 * g​r​o​u​p​s
					 */
					name: string
				}
				roles: {
					/**
					 * r​o​l​e​s
					 */
					name: string
				}
				realm: {
					/**
					 * r​e​a​l​m
					 */
					name: string
				}
				isDeprecated: {
					/**
					 * i​s​D​e​p​r​e​c​a​t​e​d
					 */
					name: string
				}
				version: {
					/**
					 * v​e​r​s​i​o​n
					 */
					name: string
				}
				realmId: {
					/**
					 * r​e​a​l​m​I​d
					 */
					name: string
				}
				createUserId: {
					/**
					 * c​r​e​a​t​e​U​s​e​r​I​d
					 */
					name: string
				}
				createTime: {
					/**
					 * c​r​e​a​t​e​T​i​m​e
					 */
					name: string
				}
				updateUserId: {
					/**
					 * u​p​d​a​t​e​U​s​e​r​I​d
					 */
					name: string
				}
				updateTime: {
					/**
					 * u​p​d​a​t​e​T​i​m​e
					 */
					name: string
				}
				createGroupId: {
					/**
					 * c​r​e​a​t​e​G​r​o​u​p​I​d
					 */
					name: string
				}
				userPhonesRelation: {
					/**
					 * u​s​e​r​P​h​o​n​e​s​R​e​l​a​t​i​o​n
					 */
					name: string
				}
				groupUserRelation: {
					/**
					 * g​r​o​u​p​U​s​e​r​R​e​l​a​t​i​o​n
					 */
					name: string
				}
				roleUserRelation: {
					/**
					 * r​o​l​e​U​s​e​r​R​e​l​a​t​i​o​n
					 */
					name: string
				}
				groupsAggregate: {
					/**
					 * g​r​o​u​p​s​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				groupsConnection: {
					/**
					 * g​r​o​u​p​s​C​o​n​n​e​c​t​i​o​n
					 */
					name: string
				}
				rolesAggregate: {
					/**
					 * r​o​l​e​s​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				rolesConnection: {
					/**
					 * r​o​l​e​s​C​o​n​n​e​c​t​i​o​n
					 */
					name: string
				}
				userPhonesRelationAggregate: {
					/**
					 * u​s​e​r​P​h​o​n​e​s​R​e​l​a​t​i​o​n​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				userPhonesRelationConnection: {
					/**
					 * u​s​e​r​P​h​o​n​e​s​R​e​l​a​t​i​o​n​C​o​n​n​e​c​t​i​o​n
					 */
					name: string
				}
				groupUserRelationAggregate: {
					/**
					 * g​r​o​u​p​U​s​e​r​R​e​l​a​t​i​o​n​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				groupUserRelationConnection: {
					/**
					 * g​r​o​u​p​U​s​e​r​R​e​l​a​t​i​o​n​C​o​n​n​e​c​t​i​o​n
					 */
					name: string
				}
				roleUserRelationAggregate: {
					/**
					 * r​o​l​e​U​s​e​r​R​e​l​a​t​i​o​n​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				roleUserRelationConnection: {
					/**
					 * r​o​l​e​U​s​e​r​R​e​l​a​t​i​o​n​C​o​n​n​e​c​t​i​o​n
					 */
					name: string
				}
				idCount: {
					/**
					 * i​d​C​o​u​n​t
					 */
					name: string
				}
				idMax: {
					/**
					 * i​d​M​a​x
					 */
					name: string
				}
				idMin: {
					/**
					 * i​d​M​i​n
					 */
					name: string
				}
				nameCount: {
					/**
					 * n​a​m​e​C​o​u​n​t
					 */
					name: string
				}
				nameMax: {
					/**
					 * n​a​m​e​M​a​x
					 */
					name: string
				}
				nameMin: {
					/**
					 * n​a​m​e​M​i​n
					 */
					name: string
				}
				descriptionCount: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​C​o​u​n​t
					 */
					name: string
				}
				descriptionMax: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​M​a​x
					 */
					name: string
				}
				descriptionMin: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​M​i​n
					 */
					name: string
				}
				lastNameCount: {
					/**
					 * l​a​s​t​N​a​m​e​C​o​u​n​t
					 */
					name: string
				}
				lastNameMax: {
					/**
					 * l​a​s​t​N​a​m​e​M​a​x
					 */
					name: string
				}
				lastNameMin: {
					/**
					 * l​a​s​t​N​a​m​e​M​i​n
					 */
					name: string
				}
				loginCount: {
					/**
					 * l​o​g​i​n​C​o​u​n​t
					 */
					name: string
				}
				loginMax: {
					/**
					 * l​o​g​i​n​M​a​x
					 */
					name: string
				}
				loginMin: {
					/**
					 * l​o​g​i​n​M​i​n
					 */
					name: string
				}
				saltCount: {
					/**
					 * s​a​l​t​C​o​u​n​t
					 */
					name: string
				}
				saltMax: {
					/**
					 * s​a​l​t​M​a​x
					 */
					name: string
				}
				saltMin: {
					/**
					 * s​a​l​t​M​i​n
					 */
					name: string
				}
				hashCount: {
					/**
					 * h​a​s​h​C​o​u​n​t
					 */
					name: string
				}
				hashMax: {
					/**
					 * h​a​s​h​M​a​x
					 */
					name: string
				}
				hashMin: {
					/**
					 * h​a​s​h​M​i​n
					 */
					name: string
				}
				emailCount: {
					/**
					 * e​m​a​i​l​C​o​u​n​t
					 */
					name: string
				}
				emailMax: {
					/**
					 * e​m​a​i​l​M​a​x
					 */
					name: string
				}
				emailMin: {
					/**
					 * e​m​a​i​l​M​i​n
					 */
					name: string
				}
				syncUserPolicy: {
					/**
					 * s​y​n​c​U​s​e​r​P​o​l​i​c​y
					 */
					name: string
				}
			}
		}
		UserPhonesRelation: {
			/**
			 * U​s​e​r​P​h​o​n​e​s​R​e​l​a​t​i​o​n
			 */
			name: string
			fields: {
				id: {
					/**
					 * i​d
					 */
					name: string
				}
				userRef: {
					/**
					 * u​s​e​r​R​e​f
					 */
					name: string
				}
				user: {
					/**
					 * u​s​e​r
					 */
					name: string
				}
				phonesRef: {
					/**
					 * p​h​o​n​e​s​R​e​f
					 */
					name: string
				}
				isDeprecated: {
					/**
					 * i​s​D​e​p​r​e​c​a​t​e​d
					 */
					name: string
				}
				version: {
					/**
					 * v​e​r​s​i​o​n
					 */
					name: string
				}
				realmId: {
					/**
					 * r​e​a​l​m​I​d
					 */
					name: string
				}
				createUserId: {
					/**
					 * c​r​e​a​t​e​U​s​e​r​I​d
					 */
					name: string
				}
				createTime: {
					/**
					 * c​r​e​a​t​e​T​i​m​e
					 */
					name: string
				}
				updateUserId: {
					/**
					 * u​p​d​a​t​e​U​s​e​r​I​d
					 */
					name: string
				}
				updateTime: {
					/**
					 * u​p​d​a​t​e​T​i​m​e
					 */
					name: string
				}
				createGroupId: {
					/**
					 * c​r​e​a​t​e​G​r​o​u​p​I​d
					 */
					name: string
				}
				idCount: {
					/**
					 * i​d​C​o​u​n​t
					 */
					name: string
				}
				idMax: {
					/**
					 * i​d​M​a​x
					 */
					name: string
				}
				idMin: {
					/**
					 * i​d​M​i​n
					 */
					name: string
				}
				userRefCount: {
					/**
					 * u​s​e​r​R​e​f​C​o​u​n​t
					 */
					name: string
				}
				userRefMax: {
					/**
					 * u​s​e​r​R​e​f​M​a​x
					 */
					name: string
				}
				userRefMin: {
					/**
					 * u​s​e​r​R​e​f​M​i​n
					 */
					name: string
				}
				phonesRefCount: {
					/**
					 * p​h​o​n​e​s​R​e​f​C​o​u​n​t
					 */
					name: string
				}
				phonesRefMax: {
					/**
					 * p​h​o​n​e​s​R​e​f​M​a​x
					 */
					name: string
				}
				phonesRefMin: {
					/**
					 * p​h​o​n​e​s​R​e​f​M​i​n
					 */
					name: string
				}
			}
		}
	}
	enums: {
		PermissionType: {
			/**
			 * P​e​r​m​i​s​s​i​o​n​T​y​p​e
			 */
			name: string
			values: {
				READ: {
					/**
					 * R​E​A​D
					 */
					name: string
				}
				WRITE: {
					/**
					 * W​R​I​T​E
					 */
					name: string
				}
			}
		}
	}
}

export type NamespaceUiTranslation = {
	menu: {
		/**
		 * M​e​n​u
		 */
		menu: string
		/**
		 * O​p​e​n​ ​M​e​n​u
		 */
		open: string
	}
	cursor: {
		/**
		 * S​i​z​e
		 */
		size: string
		/**
		 * P​r​e​v​i​o​u​s
		 */
		previous: string
		/**
		 * N​e​x​t
		 */
		next: string
	}
	pagination: {
		/**
		 * S​i​z​e
		 */
		size: string
		/**
		 * {​t​o​t​a​l​}​ ​r​e​s​u​l​t​s
		 * @param {number} total
		 */
		total: RequiredParams<'total'>
		/**
		 * P​a​g​e​ ​{​c​u​r​r​e​n​t​}
		 * @param {number} current
		 */
		current: RequiredParams<'current'>
		/**
		 * P​r​e​v​i​o​u​s
		 */
		previous: string
		/**
		 * N​e​x​t
		 */
		next: string
	}
	searchInput: {
		/**
		 * S​e​a​r​c​h
		 */
		placeholder: string
	}
	inputList: {
		/**
		 * A​d​d
		 */
		add: string
		/**
		 * R​e​m​o​v​e
		 */
		remove: string
	}
	table: {
		/**
		 * n​o​ ​r​e​s​u​l​t
		 */
		empty: string
	}
	messageBox: {
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * C​o​n​f​i​r​m
		 */
		confirm: string
	}
	button: {
		/**
		 * S​e​a​r​c​h
		 */
		search: string
		/**
		 * C​r​e​a​t​e
		 */
		create: string
		/**
		 * R​e​m​o​v​e
		 */
		remove: string
		/**
		 * U​n​b​i​n​d
		 */
		unbind: string
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * B​a​c​k
		 */
		back: string
		/**
		 * S​e​l​e​c​t
		 */
		select: string
	}
	themeSelect: {
		/**
		 * T​h​e​m​e
		 */
		btn: string
		themes: {
			/**
			 * l​i​g​h​t
			 */
			light: string
			/**
			 * d​a​r​k
			 */
			dark: string
			/**
			 * c​u​p​c​a​k​e
			 */
			cupcake: string
			/**
			 * b​u​m​b​l​e​b​e​e
			 */
			bumblebee: string
			/**
			 * e​m​e​r​a​l​d
			 */
			emerald: string
			/**
			 * c​o​r​p​o​r​a​t​e
			 */
			corporate: string
			/**
			 * s​y​n​t​h​w​a​v​e
			 */
			synthwave: string
			/**
			 * r​e​t​r​o
			 */
			retro: string
			/**
			 * c​y​b​e​r​p​u​n​k
			 */
			cyberpunk: string
			/**
			 * v​a​l​e​n​t​i​n​e
			 */
			valentine: string
			/**
			 * h​a​l​l​o​w​e​e​n
			 */
			halloween: string
			/**
			 * g​a​r​d​e​n
			 */
			garden: string
			/**
			 * f​o​r​e​s​t
			 */
			forest: string
			/**
			 * a​q​u​a
			 */
			aqua: string
			/**
			 * l​o​f​i
			 */
			lofi: string
			/**
			 * p​a​s​t​e​l
			 */
			pastel: string
			/**
			 * f​a​n​t​a​s​y
			 */
			fantasy: string
			/**
			 * w​i​r​e​f​r​a​m​e
			 */
			wireframe: string
			/**
			 * b​l​a​c​k
			 */
			black: string
			/**
			 * l​u​x​u​r​y
			 */
			luxury: string
			/**
			 * d​r​a​c​u​l​a
			 */
			dracula: string
			/**
			 * c​m​y​k
			 */
			cmyk: string
			/**
			 * a​u​t​u​m​n
			 */
			autumn: string
			/**
			 * b​u​s​i​n​e​s​s
			 */
			business: string
			/**
			 * a​c​i​d
			 */
			acid: string
			/**
			 * l​e​m​o​n​a​d​e
			 */
			lemonade: string
			/**
			 * n​i​g​h​t
			 */
			night: string
			/**
			 * c​o​f​f​e​e
			 */
			coffee: string
			/**
			 * w​i​n​t​e​r
			 */
			winter: string
		}
	}
}

export type NamespaceUiGraphqlTranslation = {
	table: {
		/**
		 * R​e​m​o​v​e​ ​r​o​w​?
		 */
		removeModalTitle: string
		/**
		 * E​d​i​t
		 */
		editBtn: string
		/**
		 * R​e​m​o​v​e
		 */
		removeBtn: string
		/**
		 * C​a​n​c​e​l
		 */
		cancelBtn: string
		th: {
			/**
			 * f​i​l​t​e​r
			 */
			filter: string
			/**
			 * c​a​n​c​e​l
			 */
			cancel: string
			/**
			 * N​o​ ​S​o​r​t
			 */
			noSort: string
			/**
			 * A​S​C
			 */
			asc: string
			/**
			 * D​E​S​C
			 */
			desc: string
			/**
			 * E​q​u​a​l​s
			 */
			eq: string
			/**
			 * N​o​t​ ​E​q​u​a​l​s
			 */
			neq: string
			/**
			 * L​i​k​e
			 */
			lk: string
			/**
			 * N​o​t​ ​L​i​k​e
			 */
			nlk: string
			/**
			 * G​r​e​a​t​e​r​ ​T​h​a​n
			 */
			gt: string
			/**
			 * G​r​e​a​t​e​r​ ​E​q​u​a​l​s
			 */
			gte: string
			/**
			 * L​e​s​s​ ​T​h​a​n
			 */
			lt: string
			/**
			 * L​e​s​s​ ​E​q​u​a​l​s
			 */
			lte: string
			/**
			 * I​s​ ​N​u​l​l
			 */
			nil: string
			/**
			 * N​o​t​ ​N​u​l​l
			 */
			nnil: string
			/**
			 * I​n
			 */
			'in': string
			/**
			 * N​o​t​ ​I​n
			 */
			nin: string
			/**
			 * B​e​t​w​e​e​n
			 */
			bt: string
			/**
			 * N​o​t​ ​B​e​t​w​e​e​n
			 */
			nbt: string
			/**
			 * F​i​l​t​e​r​.​.
			 */
			filterPlaceholder: string
		}
		td: {
			/**
			 * s​a​v​e
			 */
			save: string
			/**
			 * c​l​e​a​r
			 */
			clear: string
		}
	}
	grid: {
		buttons: {
			/**
			 * R​e​f​r​e​s​h
			 */
			refresh: string
			/**
			 * S​a​v​e
			 */
			save: string
			/**
			 * N​e​w
			 */
			'new': string
			/**
			 * A​p​p​e​n​d
			 */
			append: string
			/**
			 * R​e​m​o​v​e
			 */
			remove: string
			/**
			 * o​k
			 */
			ok: string
			/**
			 * C​a​n​e​l
			 */
			canel: string
			/**
			 * E​x​p​o​r​t
			 */
			'export': string
			/**
			 * I​m​p​o​r​t
			 */
			'import': string
		}
	}
}

export type Namespaces =
	| 'errors'
	| 'graphence'
	| 'graphql'
	| 'ui'
	| 'ui_graphql'

type DisallowNamespaces = {
	/**
	 * reserved for 'errors'-namespace\
	 * you need to use the `./errors/index.ts` file instead
	 */
	errors?: "[typesafe-i18n] reserved for 'errors'-namespace. You need to use the `./errors/index.ts` file instead."

	/**
	 * reserved for 'graphence'-namespace\
	 * you need to use the `./graphence/index.ts` file instead
	 */
	graphence?: "[typesafe-i18n] reserved for 'graphence'-namespace. You need to use the `./graphence/index.ts` file instead."

	/**
	 * reserved for 'graphql'-namespace\
	 * you need to use the `./graphql/index.ts` file instead
	 */
	graphql?: "[typesafe-i18n] reserved for 'graphql'-namespace. You need to use the `./graphql/index.ts` file instead."

	/**
	 * reserved for 'ui'-namespace\
	 * you need to use the `./ui/index.ts` file instead
	 */
	ui?: "[typesafe-i18n] reserved for 'ui'-namespace. You need to use the `./ui/index.ts` file instead."

	/**
	 * reserved for 'ui_graphql'-namespace\
	 * you need to use the `./ui_graphql/index.ts` file instead
	 */
	ui_graphql?: "[typesafe-i18n] reserved for 'ui_graphql'-namespace. You need to use the `./ui_graphql/index.ts` file instead."
}

export type TranslationFunctions = {
	errors: {
		code: {
			/**
			 * Authentication failed
			 */
			'-40101': () => LocalizedString
			/**
			 * Resource has been updated
			 */
			'-40900': () => LocalizedString
			/**
			 * Existed unique values
			 */
			'-40901': () => LocalizedString
			/**
			 * Requet error
			 */
			'-99999': () => LocalizedString
		}
	}
	graphence: {
		login: {
			/**
			 * Full-stack GraphQL development platform, powered by GraphQL Svelte and Reactor Java
			 */
			detail: () => LocalizedString
			/**
			 * Account
			 */
			account: () => LocalizedString
			/**
			 * Login
			 */
			login: () => LocalizedString
			/**
			 * Password
			 */
			password: () => LocalizedString
			/**
			 * Forgot password?
			 */
			forgot: () => LocalizedString
		}
		message: {
			/**
			 * Save success
			 */
			saveSuccess: () => LocalizedString
			/**
			 * Create success
			 */
			createSuccess: () => LocalizedString
			/**
			 * Remove success
			 */
			removeSuccess: () => LocalizedString
			/**
			 * Unbind success
			 */
			unbindSuccess: () => LocalizedString
			/**
			 * Request failed
			 */
			requestFailed: () => LocalizedString
			/**
			 * Save failed
			 */
			saveFailed: () => LocalizedString
			/**
			 * Create failed
			 */
			createFailed: () => LocalizedString
			/**
			 * Remove failed
			 */
			removeFailed: () => LocalizedString
			/**
			 * Unbind failed
			 */
			unbindFailed: () => LocalizedString
		}
		path: {
			/**
			 * Home
			 */
			home: () => LocalizedString
			/**
			 * Create {name}
			 */
			create: (arg: { name: string }) => LocalizedString
			/**
			 * Select {name}
			 */
			select: (arg: { name: string }) => LocalizedString
		}
		components: {
			search: {
				/**
				 * Search
				 */
				label: () => LocalizedString
			}
			table: {
				/**
				 * Remove row?
				 */
				removeModalTitle: () => LocalizedString
				/**
				 * Unbind row?
				 */
				unbindModalTitle: () => LocalizedString
				/**
				 * Edit
				 */
				editBtn: () => LocalizedString
				/**
				 * Remove
				 */
				removeBtn: () => LocalizedString
				/**
				 * Unbind
				 */
				unbindBtn: () => LocalizedString
				/**
				 * Select
				 */
				selectBtn: () => LocalizedString
			}
			sideBarMenu: {
				/**
				 * Modules
				 */
				modules: () => LocalizedString
				/**
				 * Statistics
				 */
				statistics: () => LocalizedString
				/**
				 * Grid
				 */
				grid: () => LocalizedString
				/**
				 * Table
				 */
				table: () => LocalizedString
				/**
				 * Bar
				 */
				bar: () => LocalizedString
				/**
				 * Line
				 */
				line: () => LocalizedString
				/**
				 * Pie
				 */
				pie: () => LocalizedString
				/**
				 * Edit
				 */
				mutation: () => LocalizedString
			}
			userMenu: {
				/**
				 * Profile
				 */
				profile: () => LocalizedString
				/**
				 * Reset password
				 */
				password: () => LocalizedString
				/**
				 * Logout
				 */
				logout: () => LocalizedString
			}
			resetPassword: {
				/**
				 * Original password
				 */
				password: () => LocalizedString
				/**
				 * New password
				 */
				newPassword: () => LocalizedString
				/**
				 * Repeat new Password
				 */
				repeatNewPassword: () => LocalizedString
				/**
				 * Inconsistent
				 */
				inconsistent: () => LocalizedString
			}
			agg: {
				/**
				 * Columns
				 */
				columns: () => LocalizedString
				/**
				 * Group By
				 */
				groupBy: () => LocalizedString
				/**
				 * Order By
				 */
				orderBy: () => LocalizedString
				/**
				 * Options
				 */
				option: () => LocalizedString
				/**
				 * Filter
				 */
				filter: () => LocalizedString
				/**
				 * Bookmark
				 */
				bookmark: () => LocalizedString
			}
			query: {
				/**
				 * Columns
				 */
				columns: () => LocalizedString
				/**
				 * Join
				 */
				join: () => LocalizedString
				/**
				 * Join Columns
				 */
				joinColumns: () => LocalizedString
				/**
				 * Order By
				 */
				orderBy: () => LocalizedString
				/**
				 * Options
				 */
				option: () => LocalizedString
				/**
				 * Filter
				 */
				filter: () => LocalizedString
				/**
				 * Bookmark
				 */
				bookmark: () => LocalizedString
			}
			grid: {
				boolean: {
					/**
					 * Yes
					 */
					'true': () => LocalizedString
					/**
					 * No
					 */
					'false': () => LocalizedString
				}
				captions: {
					/**
					 * Filter
					 */
					title: () => LocalizedString
					/**
					 * Save
					 */
					save: () => LocalizedString
					/**
					 * Reset
					 */
					reset: () => LocalizedString
					/**
					 * OK
					 */
					ok: () => LocalizedString
					/**
					 * Cancel
					 */
					cancel: () => LocalizedString
					/**
					 * Add
					 */
					add: () => LocalizedString
					/**
					 * Enter value
					 */
					placeholder: () => LocalizedString
					/**
					 * And
					 */
					and: () => LocalizedString
					/**
					 * Or
					 */
					or: () => LocalizedString
				}
				filterNames: {
					/**
					 * None
					 */
					none: () => LocalizedString
					/**
					 * Not set
					 */
					empty: () => LocalizedString
					/**
					 * Set
					 */
					notEmpty: () => LocalizedString
					/**
					 * Equal
					 */
					eq: () => LocalizedString
					/**
					 * Not equal
					 */
					notEq: () => LocalizedString
					/**
					 * Begins with
					 */
					begins: () => LocalizedString
					/**
					 * Contains
					 */
					contains: () => LocalizedString
					/**
					 * Does not contain
					 */
					notContains: () => LocalizedString
					/**
					 * =
					 */
					eqN: () => LocalizedString
					/**
					 * !=
					 */
					neqN: () => LocalizedString
					/**
					 * >
					 */
					gt: () => LocalizedString
					/**
					 * >=
					 */
					gte: () => LocalizedString
					/**
					 * <
					 */
					lt: () => LocalizedString
					/**
					 * <=
					 */
					lte: () => LocalizedString
				}
			}
		}
	}
	graphql: {
		objects: {
			Current: {
				/**
				 * Current
				 */
				name: () => LocalizedString
				fields: {
					id: {
						/**
						 * id
						 */
						name: () => LocalizedString
					}
					name: {
						/**
						 * name
						 */
						name: () => LocalizedString
					}
					lastName: {
						/**
						 * lastName
						 */
						name: () => LocalizedString
					}
					login: {
						/**
						 * login
						 */
						name: () => LocalizedString
					}
					realmId: {
						/**
						 * realmId
						 */
						name: () => LocalizedString
					}
					groups: {
						/**
						 * groups
						 */
						name: () => LocalizedString
					}
					roles: {
						/**
						 * roles
						 */
						name: () => LocalizedString
					}
				}
			}
			Group: {
				/**
				 * Group
				 */
				name: () => LocalizedString
				fields: {
					id: {
						/**
						 * id
						 */
						name: () => LocalizedString
					}
					name: {
						/**
						 * name
						 */
						name: () => LocalizedString
					}
					description: {
						/**
						 * description
						 */
						name: () => LocalizedString
					}
					path: {
						/**
						 * path
						 */
						name: () => LocalizedString
					}
					deep: {
						/**
						 * deep
						 */
						name: () => LocalizedString
					}
					parentId: {
						/**
						 * parentId
						 */
						name: () => LocalizedString
					}
					parent: {
						/**
						 * parent
						 */
						name: () => LocalizedString
					}
					subGroups: {
						/**
						 * subGroups
						 */
						name: () => LocalizedString
					}
					users: {
						/**
						 * users
						 */
						name: () => LocalizedString
					}
					roles: {
						/**
						 * roles
						 */
						name: () => LocalizedString
					}
					realm: {
						/**
						 * realm
						 */
						name: () => LocalizedString
					}
					isDeprecated: {
						/**
						 * isDeprecated
						 */
						name: () => LocalizedString
					}
					version: {
						/**
						 * version
						 */
						name: () => LocalizedString
					}
					realmId: {
						/**
						 * realmId
						 */
						name: () => LocalizedString
					}
					createUserId: {
						/**
						 * createUserId
						 */
						name: () => LocalizedString
					}
					createTime: {
						/**
						 * createTime
						 */
						name: () => LocalizedString
					}
					updateUserId: {
						/**
						 * updateUserId
						 */
						name: () => LocalizedString
					}
					updateTime: {
						/**
						 * updateTime
						 */
						name: () => LocalizedString
					}
					createGroupId: {
						/**
						 * createGroupId
						 */
						name: () => LocalizedString
					}
					groupUserRelation: {
						/**
						 * groupUserRelation
						 */
						name: () => LocalizedString
					}
					groupRoleRelation: {
						/**
						 * groupRoleRelation
						 */
						name: () => LocalizedString
					}
					subGroupsAggregate: {
						/**
						 * subGroupsAggregate
						 */
						name: () => LocalizedString
					}
					subGroupsConnection: {
						/**
						 * subGroupsConnection
						 */
						name: () => LocalizedString
					}
					usersAggregate: {
						/**
						 * usersAggregate
						 */
						name: () => LocalizedString
					}
					usersConnection: {
						/**
						 * usersConnection
						 */
						name: () => LocalizedString
					}
					rolesAggregate: {
						/**
						 * rolesAggregate
						 */
						name: () => LocalizedString
					}
					rolesConnection: {
						/**
						 * rolesConnection
						 */
						name: () => LocalizedString
					}
					groupUserRelationAggregate: {
						/**
						 * groupUserRelationAggregate
						 */
						name: () => LocalizedString
					}
					groupUserRelationConnection: {
						/**
						 * groupUserRelationConnection
						 */
						name: () => LocalizedString
					}
					groupRoleRelationAggregate: {
						/**
						 * groupRoleRelationAggregate
						 */
						name: () => LocalizedString
					}
					groupRoleRelationConnection: {
						/**
						 * groupRoleRelationConnection
						 */
						name: () => LocalizedString
					}
					idCount: {
						/**
						 * idCount
						 */
						name: () => LocalizedString
					}
					idMax: {
						/**
						 * idMax
						 */
						name: () => LocalizedString
					}
					idMin: {
						/**
						 * idMin
						 */
						name: () => LocalizedString
					}
					nameCount: {
						/**
						 * nameCount
						 */
						name: () => LocalizedString
					}
					nameMax: {
						/**
						 * nameMax
						 */
						name: () => LocalizedString
					}
					nameMin: {
						/**
						 * nameMin
						 */
						name: () => LocalizedString
					}
					descriptionCount: {
						/**
						 * descriptionCount
						 */
						name: () => LocalizedString
					}
					descriptionMax: {
						/**
						 * descriptionMax
						 */
						name: () => LocalizedString
					}
					descriptionMin: {
						/**
						 * descriptionMin
						 */
						name: () => LocalizedString
					}
					pathCount: {
						/**
						 * pathCount
						 */
						name: () => LocalizedString
					}
					pathMax: {
						/**
						 * pathMax
						 */
						name: () => LocalizedString
					}
					pathMin: {
						/**
						 * pathMin
						 */
						name: () => LocalizedString
					}
					parentIdCount: {
						/**
						 * parentIdCount
						 */
						name: () => LocalizedString
					}
					parentIdMax: {
						/**
						 * parentIdMax
						 */
						name: () => LocalizedString
					}
					parentIdMin: {
						/**
						 * parentIdMin
						 */
						name: () => LocalizedString
					}
					deepCount: {
						/**
						 * deepCount
						 */
						name: () => LocalizedString
					}
					deepSum: {
						/**
						 * deepSum
						 */
						name: () => LocalizedString
					}
					deepAvg: {
						/**
						 * deepAvg
						 */
						name: () => LocalizedString
					}
					deepMax: {
						/**
						 * deepMax
						 */
						name: () => LocalizedString
					}
					deepMin: {
						/**
						 * deepMin
						 */
						name: () => LocalizedString
					}
					syncGroupPolicy: {
						/**
						 * syncGroupPolicy
						 */
						name: () => LocalizedString
					}
				}
			}
			GroupRoleRelation: {
				/**
				 * GroupRoleRelation
				 */
				name: () => LocalizedString
				fields: {
					id: {
						/**
						 * id
						 */
						name: () => LocalizedString
					}
					roleRef: {
						/**
						 * roleRef
						 */
						name: () => LocalizedString
					}
					role: {
						/**
						 * role
						 */
						name: () => LocalizedString
					}
					groupRef: {
						/**
						 * groupRef
						 */
						name: () => LocalizedString
					}
					group: {
						/**
						 * group
						 */
						name: () => LocalizedString
					}
					isDeprecated: {
						/**
						 * isDeprecated
						 */
						name: () => LocalizedString
					}
					version: {
						/**
						 * version
						 */
						name: () => LocalizedString
					}
					realmId: {
						/**
						 * realmId
						 */
						name: () => LocalizedString
					}
					createUserId: {
						/**
						 * createUserId
						 */
						name: () => LocalizedString
					}
					createTime: {
						/**
						 * createTime
						 */
						name: () => LocalizedString
					}
					updateUserId: {
						/**
						 * updateUserId
						 */
						name: () => LocalizedString
					}
					updateTime: {
						/**
						 * updateTime
						 */
						name: () => LocalizedString
					}
					createGroupId: {
						/**
						 * createGroupId
						 */
						name: () => LocalizedString
					}
					idCount: {
						/**
						 * idCount
						 */
						name: () => LocalizedString
					}
					idMax: {
						/**
						 * idMax
						 */
						name: () => LocalizedString
					}
					idMin: {
						/**
						 * idMin
						 */
						name: () => LocalizedString
					}
					roleRefCount: {
						/**
						 * roleRefCount
						 */
						name: () => LocalizedString
					}
					roleRefMax: {
						/**
						 * roleRefMax
						 */
						name: () => LocalizedString
					}
					roleRefMin: {
						/**
						 * roleRefMin
						 */
						name: () => LocalizedString
					}
					groupRefCount: {
						/**
						 * groupRefCount
						 */
						name: () => LocalizedString
					}
					groupRefMax: {
						/**
						 * groupRefMax
						 */
						name: () => LocalizedString
					}
					groupRefMin: {
						/**
						 * groupRefMin
						 */
						name: () => LocalizedString
					}
				}
			}
			GroupUserRelation: {
				/**
				 * GroupUserRelation
				 */
				name: () => LocalizedString
				fields: {
					id: {
						/**
						 * id
						 */
						name: () => LocalizedString
					}
					userRef: {
						/**
						 * userRef
						 */
						name: () => LocalizedString
					}
					user: {
						/**
						 * user
						 */
						name: () => LocalizedString
					}
					groupRef: {
						/**
						 * groupRef
						 */
						name: () => LocalizedString
					}
					group: {
						/**
						 * group
						 */
						name: () => LocalizedString
					}
					isDeprecated: {
						/**
						 * isDeprecated
						 */
						name: () => LocalizedString
					}
					version: {
						/**
						 * version
						 */
						name: () => LocalizedString
					}
					realmId: {
						/**
						 * realmId
						 */
						name: () => LocalizedString
					}
					createUserId: {
						/**
						 * createUserId
						 */
						name: () => LocalizedString
					}
					createTime: {
						/**
						 * createTime
						 */
						name: () => LocalizedString
					}
					updateUserId: {
						/**
						 * updateUserId
						 */
						name: () => LocalizedString
					}
					updateTime: {
						/**
						 * updateTime
						 */
						name: () => LocalizedString
					}
					createGroupId: {
						/**
						 * createGroupId
						 */
						name: () => LocalizedString
					}
					idCount: {
						/**
						 * idCount
						 */
						name: () => LocalizedString
					}
					idMax: {
						/**
						 * idMax
						 */
						name: () => LocalizedString
					}
					idMin: {
						/**
						 * idMin
						 */
						name: () => LocalizedString
					}
					userRefCount: {
						/**
						 * userRefCount
						 */
						name: () => LocalizedString
					}
					userRefMax: {
						/**
						 * userRefMax
						 */
						name: () => LocalizedString
					}
					userRefMin: {
						/**
						 * userRefMin
						 */
						name: () => LocalizedString
					}
					groupRefCount: {
						/**
						 * groupRefCount
						 */
						name: () => LocalizedString
					}
					groupRefMax: {
						/**
						 * groupRefMax
						 */
						name: () => LocalizedString
					}
					groupRefMin: {
						/**
						 * groupRefMin
						 */
						name: () => LocalizedString
					}
				}
			}
			Permission: {
				/**
				 * Permission
				 */
				name: () => LocalizedString
				fields: {
					name: {
						/**
						 * name
						 */
						name: () => LocalizedString
					}
					description: {
						/**
						 * description
						 */
						name: () => LocalizedString
					}
					field: {
						/**
						 * field
						 */
						name: () => LocalizedString
					}
					type: {
						/**
						 * type
						 */
						name: () => LocalizedString
					}
					permissionType: {
						/**
						 * permissionType
						 */
						name: () => LocalizedString
					}
					roles: {
						/**
						 * roles
						 */
						name: () => LocalizedString
					}
					realm: {
						/**
						 * realm
						 */
						name: () => LocalizedString
					}
					isDeprecated: {
						/**
						 * isDeprecated
						 */
						name: () => LocalizedString
					}
					version: {
						/**
						 * version
						 */
						name: () => LocalizedString
					}
					realmId: {
						/**
						 * realmId
						 */
						name: () => LocalizedString
					}
					createUserId: {
						/**
						 * createUserId
						 */
						name: () => LocalizedString
					}
					createTime: {
						/**
						 * createTime
						 */
						name: () => LocalizedString
					}
					updateUserId: {
						/**
						 * updateUserId
						 */
						name: () => LocalizedString
					}
					updateTime: {
						/**
						 * updateTime
						 */
						name: () => LocalizedString
					}
					createGroupId: {
						/**
						 * createGroupId
						 */
						name: () => LocalizedString
					}
					permissionRoleRelation: {
						/**
						 * permissionRoleRelation
						 */
						name: () => LocalizedString
					}
					rolesAggregate: {
						/**
						 * rolesAggregate
						 */
						name: () => LocalizedString
					}
					rolesConnection: {
						/**
						 * rolesConnection
						 */
						name: () => LocalizedString
					}
					permissionRoleRelationAggregate: {
						/**
						 * permissionRoleRelationAggregate
						 */
						name: () => LocalizedString
					}
					permissionRoleRelationConnection: {
						/**
						 * permissionRoleRelationConnection
						 */
						name: () => LocalizedString
					}
					nameCount: {
						/**
						 * nameCount
						 */
						name: () => LocalizedString
					}
					nameMax: {
						/**
						 * nameMax
						 */
						name: () => LocalizedString
					}
					nameMin: {
						/**
						 * nameMin
						 */
						name: () => LocalizedString
					}
					descriptionCount: {
						/**
						 * descriptionCount
						 */
						name: () => LocalizedString
					}
					descriptionMax: {
						/**
						 * descriptionMax
						 */
						name: () => LocalizedString
					}
					descriptionMin: {
						/**
						 * descriptionMin
						 */
						name: () => LocalizedString
					}
					fieldCount: {
						/**
						 * fieldCount
						 */
						name: () => LocalizedString
					}
					fieldMax: {
						/**
						 * fieldMax
						 */
						name: () => LocalizedString
					}
					fieldMin: {
						/**
						 * fieldMin
						 */
						name: () => LocalizedString
					}
					typeCount: {
						/**
						 * typeCount
						 */
						name: () => LocalizedString
					}
					typeMax: {
						/**
						 * typeMax
						 */
						name: () => LocalizedString
					}
					typeMin: {
						/**
						 * typeMin
						 */
						name: () => LocalizedString
					}
					permissionTypeCount: {
						/**
						 * permissionTypeCount
						 */
						name: () => LocalizedString
					}
					permissionTypeMax: {
						/**
						 * permissionTypeMax
						 */
						name: () => LocalizedString
					}
					permissionTypeMin: {
						/**
						 * permissionTypeMin
						 */
						name: () => LocalizedString
					}
					syncPermissionPolicy: {
						/**
						 * syncPermissionPolicy
						 */
						name: () => LocalizedString
					}
				}
			}
			PermissionRoleRelation: {
				/**
				 * PermissionRoleRelation
				 */
				name: () => LocalizedString
				fields: {
					id: {
						/**
						 * id
						 */
						name: () => LocalizedString
					}
					roleRef: {
						/**
						 * roleRef
						 */
						name: () => LocalizedString
					}
					role: {
						/**
						 * role
						 */
						name: () => LocalizedString
					}
					permissionRef: {
						/**
						 * permissionRef
						 */
						name: () => LocalizedString
					}
					permission: {
						/**
						 * permission
						 */
						name: () => LocalizedString
					}
					isDeprecated: {
						/**
						 * isDeprecated
						 */
						name: () => LocalizedString
					}
					version: {
						/**
						 * version
						 */
						name: () => LocalizedString
					}
					realmId: {
						/**
						 * realmId
						 */
						name: () => LocalizedString
					}
					createUserId: {
						/**
						 * createUserId
						 */
						name: () => LocalizedString
					}
					createTime: {
						/**
						 * createTime
						 */
						name: () => LocalizedString
					}
					updateUserId: {
						/**
						 * updateUserId
						 */
						name: () => LocalizedString
					}
					updateTime: {
						/**
						 * updateTime
						 */
						name: () => LocalizedString
					}
					createGroupId: {
						/**
						 * createGroupId
						 */
						name: () => LocalizedString
					}
					idCount: {
						/**
						 * idCount
						 */
						name: () => LocalizedString
					}
					idMax: {
						/**
						 * idMax
						 */
						name: () => LocalizedString
					}
					idMin: {
						/**
						 * idMin
						 */
						name: () => LocalizedString
					}
					roleRefCount: {
						/**
						 * roleRefCount
						 */
						name: () => LocalizedString
					}
					roleRefMax: {
						/**
						 * roleRefMax
						 */
						name: () => LocalizedString
					}
					roleRefMin: {
						/**
						 * roleRefMin
						 */
						name: () => LocalizedString
					}
					permissionRefCount: {
						/**
						 * permissionRefCount
						 */
						name: () => LocalizedString
					}
					permissionRefMax: {
						/**
						 * permissionRefMax
						 */
						name: () => LocalizedString
					}
					permissionRefMin: {
						/**
						 * permissionRefMin
						 */
						name: () => LocalizedString
					}
				}
			}
			Policy: {
				/**
				 * Policy
				 */
				name: () => LocalizedString
				fields: {
					id: {
						/**
						 * id
						 */
						name: () => LocalizedString
					}
					policy: {
						/**
						 * policy
						 */
						name: () => LocalizedString
					}
					v0: {
						/**
						 * v0
						 */
						name: () => LocalizedString
					}
					v1: {
						/**
						 * v1
						 */
						name: () => LocalizedString
					}
					v2: {
						/**
						 * v2
						 */
						name: () => LocalizedString
					}
					v3: {
						/**
						 * v3
						 */
						name: () => LocalizedString
					}
					v4: {
						/**
						 * v4
						 */
						name: () => LocalizedString
					}
					v5: {
						/**
						 * v5
						 */
						name: () => LocalizedString
					}
				}
			}
			Realm: {
				/**
				 * Realm
				 */
				name: () => LocalizedString
				fields: {
					id: {
						/**
						 * id
						 */
						name: () => LocalizedString
					}
					name: {
						/**
						 * name
						 */
						name: () => LocalizedString
					}
					description: {
						/**
						 * description
						 */
						name: () => LocalizedString
					}
					isDeprecated: {
						/**
						 * isDeprecated
						 */
						name: () => LocalizedString
					}
					version: {
						/**
						 * version
						 */
						name: () => LocalizedString
					}
					realmId: {
						/**
						 * realmId
						 */
						name: () => LocalizedString
					}
					createUserId: {
						/**
						 * createUserId
						 */
						name: () => LocalizedString
					}
					createTime: {
						/**
						 * createTime
						 */
						name: () => LocalizedString
					}
					updateUserId: {
						/**
						 * updateUserId
						 */
						name: () => LocalizedString
					}
					updateTime: {
						/**
						 * updateTime
						 */
						name: () => LocalizedString
					}
					createGroupId: {
						/**
						 * createGroupId
						 */
						name: () => LocalizedString
					}
					idCount: {
						/**
						 * idCount
						 */
						name: () => LocalizedString
					}
					idMax: {
						/**
						 * idMax
						 */
						name: () => LocalizedString
					}
					idMin: {
						/**
						 * idMin
						 */
						name: () => LocalizedString
					}
					nameCount: {
						/**
						 * nameCount
						 */
						name: () => LocalizedString
					}
					nameMax: {
						/**
						 * nameMax
						 */
						name: () => LocalizedString
					}
					nameMin: {
						/**
						 * nameMin
						 */
						name: () => LocalizedString
					}
					descriptionCount: {
						/**
						 * descriptionCount
						 */
						name: () => LocalizedString
					}
					descriptionMax: {
						/**
						 * descriptionMax
						 */
						name: () => LocalizedString
					}
					descriptionMin: {
						/**
						 * descriptionMin
						 */
						name: () => LocalizedString
					}
				}
			}
			Role: {
				/**
				 * Role
				 */
				name: () => LocalizedString
				fields: {
					id: {
						/**
						 * id
						 */
						name: () => LocalizedString
					}
					name: {
						/**
						 * name
						 */
						name: () => LocalizedString
					}
					description: {
						/**
						 * description
						 */
						name: () => LocalizedString
					}
					users: {
						/**
						 * users
						 */
						name: () => LocalizedString
					}
					groups: {
						/**
						 * groups
						 */
						name: () => LocalizedString
					}
					composites: {
						/**
						 * composites
						 */
						name: () => LocalizedString
					}
					permissions: {
						/**
						 * permissions
						 */
						name: () => LocalizedString
					}
					realm: {
						/**
						 * realm
						 */
						name: () => LocalizedString
					}
					isDeprecated: {
						/**
						 * isDeprecated
						 */
						name: () => LocalizedString
					}
					version: {
						/**
						 * version
						 */
						name: () => LocalizedString
					}
					realmId: {
						/**
						 * realmId
						 */
						name: () => LocalizedString
					}
					createUserId: {
						/**
						 * createUserId
						 */
						name: () => LocalizedString
					}
					createTime: {
						/**
						 * createTime
						 */
						name: () => LocalizedString
					}
					updateUserId: {
						/**
						 * updateUserId
						 */
						name: () => LocalizedString
					}
					updateTime: {
						/**
						 * updateTime
						 */
						name: () => LocalizedString
					}
					createGroupId: {
						/**
						 * createGroupId
						 */
						name: () => LocalizedString
					}
					roleUserRelation: {
						/**
						 * roleUserRelation
						 */
						name: () => LocalizedString
					}
					groupRoleRelation: {
						/**
						 * groupRoleRelation
						 */
						name: () => LocalizedString
					}
					roleCompositeRelation: {
						/**
						 * roleCompositeRelation
						 */
						name: () => LocalizedString
					}
					permissionRoleRelation: {
						/**
						 * permissionRoleRelation
						 */
						name: () => LocalizedString
					}
					usersAggregate: {
						/**
						 * usersAggregate
						 */
						name: () => LocalizedString
					}
					usersConnection: {
						/**
						 * usersConnection
						 */
						name: () => LocalizedString
					}
					groupsAggregate: {
						/**
						 * groupsAggregate
						 */
						name: () => LocalizedString
					}
					groupsConnection: {
						/**
						 * groupsConnection
						 */
						name: () => LocalizedString
					}
					compositesAggregate: {
						/**
						 * compositesAggregate
						 */
						name: () => LocalizedString
					}
					compositesConnection: {
						/**
						 * compositesConnection
						 */
						name: () => LocalizedString
					}
					permissionsAggregate: {
						/**
						 * permissionsAggregate
						 */
						name: () => LocalizedString
					}
					permissionsConnection: {
						/**
						 * permissionsConnection
						 */
						name: () => LocalizedString
					}
					roleUserRelationAggregate: {
						/**
						 * roleUserRelationAggregate
						 */
						name: () => LocalizedString
					}
					roleUserRelationConnection: {
						/**
						 * roleUserRelationConnection
						 */
						name: () => LocalizedString
					}
					groupRoleRelationAggregate: {
						/**
						 * groupRoleRelationAggregate
						 */
						name: () => LocalizedString
					}
					groupRoleRelationConnection: {
						/**
						 * groupRoleRelationConnection
						 */
						name: () => LocalizedString
					}
					roleCompositeRelationAggregate: {
						/**
						 * roleCompositeRelationAggregate
						 */
						name: () => LocalizedString
					}
					roleCompositeRelationConnection: {
						/**
						 * roleCompositeRelationConnection
						 */
						name: () => LocalizedString
					}
					permissionRoleRelationAggregate: {
						/**
						 * permissionRoleRelationAggregate
						 */
						name: () => LocalizedString
					}
					permissionRoleRelationConnection: {
						/**
						 * permissionRoleRelationConnection
						 */
						name: () => LocalizedString
					}
					idCount: {
						/**
						 * idCount
						 */
						name: () => LocalizedString
					}
					idMax: {
						/**
						 * idMax
						 */
						name: () => LocalizedString
					}
					idMin: {
						/**
						 * idMin
						 */
						name: () => LocalizedString
					}
					nameCount: {
						/**
						 * nameCount
						 */
						name: () => LocalizedString
					}
					nameMax: {
						/**
						 * nameMax
						 */
						name: () => LocalizedString
					}
					nameMin: {
						/**
						 * nameMin
						 */
						name: () => LocalizedString
					}
					descriptionCount: {
						/**
						 * descriptionCount
						 */
						name: () => LocalizedString
					}
					descriptionMax: {
						/**
						 * descriptionMax
						 */
						name: () => LocalizedString
					}
					descriptionMin: {
						/**
						 * descriptionMin
						 */
						name: () => LocalizedString
					}
					syncRolePolicy: {
						/**
						 * syncRolePolicy
						 */
						name: () => LocalizedString
					}
				}
			}
			RoleCompositeRelation: {
				/**
				 * RoleCompositeRelation
				 */
				name: () => LocalizedString
				fields: {
					id: {
						/**
						 * id
						 */
						name: () => LocalizedString
					}
					roleRef: {
						/**
						 * roleRef
						 */
						name: () => LocalizedString
					}
					role: {
						/**
						 * role
						 */
						name: () => LocalizedString
					}
					compositeRef: {
						/**
						 * compositeRef
						 */
						name: () => LocalizedString
					}
					composite: {
						/**
						 * composite
						 */
						name: () => LocalizedString
					}
					isDeprecated: {
						/**
						 * isDeprecated
						 */
						name: () => LocalizedString
					}
					version: {
						/**
						 * version
						 */
						name: () => LocalizedString
					}
					realmId: {
						/**
						 * realmId
						 */
						name: () => LocalizedString
					}
					createUserId: {
						/**
						 * createUserId
						 */
						name: () => LocalizedString
					}
					createTime: {
						/**
						 * createTime
						 */
						name: () => LocalizedString
					}
					updateUserId: {
						/**
						 * updateUserId
						 */
						name: () => LocalizedString
					}
					updateTime: {
						/**
						 * updateTime
						 */
						name: () => LocalizedString
					}
					createGroupId: {
						/**
						 * createGroupId
						 */
						name: () => LocalizedString
					}
					idCount: {
						/**
						 * idCount
						 */
						name: () => LocalizedString
					}
					idMax: {
						/**
						 * idMax
						 */
						name: () => LocalizedString
					}
					idMin: {
						/**
						 * idMin
						 */
						name: () => LocalizedString
					}
					roleRefCount: {
						/**
						 * roleRefCount
						 */
						name: () => LocalizedString
					}
					roleRefMax: {
						/**
						 * roleRefMax
						 */
						name: () => LocalizedString
					}
					roleRefMin: {
						/**
						 * roleRefMin
						 */
						name: () => LocalizedString
					}
					compositeRefCount: {
						/**
						 * compositeRefCount
						 */
						name: () => LocalizedString
					}
					compositeRefMax: {
						/**
						 * compositeRefMax
						 */
						name: () => LocalizedString
					}
					compositeRefMin: {
						/**
						 * compositeRefMin
						 */
						name: () => LocalizedString
					}
				}
			}
			RoleUserRelation: {
				/**
				 * RoleUserRelation
				 */
				name: () => LocalizedString
				fields: {
					id: {
						/**
						 * id
						 */
						name: () => LocalizedString
					}
					userRef: {
						/**
						 * userRef
						 */
						name: () => LocalizedString
					}
					user: {
						/**
						 * user
						 */
						name: () => LocalizedString
					}
					roleRef: {
						/**
						 * roleRef
						 */
						name: () => LocalizedString
					}
					role: {
						/**
						 * role
						 */
						name: () => LocalizedString
					}
					isDeprecated: {
						/**
						 * isDeprecated
						 */
						name: () => LocalizedString
					}
					version: {
						/**
						 * version
						 */
						name: () => LocalizedString
					}
					realmId: {
						/**
						 * realmId
						 */
						name: () => LocalizedString
					}
					createUserId: {
						/**
						 * createUserId
						 */
						name: () => LocalizedString
					}
					createTime: {
						/**
						 * createTime
						 */
						name: () => LocalizedString
					}
					updateUserId: {
						/**
						 * updateUserId
						 */
						name: () => LocalizedString
					}
					updateTime: {
						/**
						 * updateTime
						 */
						name: () => LocalizedString
					}
					createGroupId: {
						/**
						 * createGroupId
						 */
						name: () => LocalizedString
					}
					idCount: {
						/**
						 * idCount
						 */
						name: () => LocalizedString
					}
					idMax: {
						/**
						 * idMax
						 */
						name: () => LocalizedString
					}
					idMin: {
						/**
						 * idMin
						 */
						name: () => LocalizedString
					}
					userRefCount: {
						/**
						 * userRefCount
						 */
						name: () => LocalizedString
					}
					userRefMax: {
						/**
						 * userRefMax
						 */
						name: () => LocalizedString
					}
					userRefMin: {
						/**
						 * userRefMin
						 */
						name: () => LocalizedString
					}
					roleRefCount: {
						/**
						 * roleRefCount
						 */
						name: () => LocalizedString
					}
					roleRefMax: {
						/**
						 * roleRefMax
						 */
						name: () => LocalizedString
					}
					roleRefMin: {
						/**
						 * roleRefMin
						 */
						name: () => LocalizedString
					}
				}
			}
			User: {
				/**
				 * User
				 */
				name: () => LocalizedString
				fields: {
					id: {
						/**
						 * id
						 */
						name: () => LocalizedString
					}
					name: {
						/**
						 * name
						 */
						name: () => LocalizedString
					}
					description: {
						/**
						 * description
						 */
						name: () => LocalizedString
					}
					lastName: {
						/**
						 * lastName
						 */
						name: () => LocalizedString
					}
					login: {
						/**
						 * login
						 */
						name: () => LocalizedString
					}
					salt: {
						/**
						 * salt
						 */
						name: () => LocalizedString
					}
					hash: {
						/**
						 * hash
						 */
						name: () => LocalizedString
					}
					email: {
						/**
						 * email
						 */
						name: () => LocalizedString
					}
					phones: {
						/**
						 * phones
						 */
						name: () => LocalizedString
					}
					disable: {
						/**
						 * disable
						 */
						name: () => LocalizedString
					}
					groups: {
						/**
						 * groups
						 */
						name: () => LocalizedString
					}
					roles: {
						/**
						 * roles
						 */
						name: () => LocalizedString
					}
					realm: {
						/**
						 * realm
						 */
						name: () => LocalizedString
					}
					isDeprecated: {
						/**
						 * isDeprecated
						 */
						name: () => LocalizedString
					}
					version: {
						/**
						 * version
						 */
						name: () => LocalizedString
					}
					realmId: {
						/**
						 * realmId
						 */
						name: () => LocalizedString
					}
					createUserId: {
						/**
						 * createUserId
						 */
						name: () => LocalizedString
					}
					createTime: {
						/**
						 * createTime
						 */
						name: () => LocalizedString
					}
					updateUserId: {
						/**
						 * updateUserId
						 */
						name: () => LocalizedString
					}
					updateTime: {
						/**
						 * updateTime
						 */
						name: () => LocalizedString
					}
					createGroupId: {
						/**
						 * createGroupId
						 */
						name: () => LocalizedString
					}
					userPhonesRelation: {
						/**
						 * userPhonesRelation
						 */
						name: () => LocalizedString
					}
					groupUserRelation: {
						/**
						 * groupUserRelation
						 */
						name: () => LocalizedString
					}
					roleUserRelation: {
						/**
						 * roleUserRelation
						 */
						name: () => LocalizedString
					}
					groupsAggregate: {
						/**
						 * groupsAggregate
						 */
						name: () => LocalizedString
					}
					groupsConnection: {
						/**
						 * groupsConnection
						 */
						name: () => LocalizedString
					}
					rolesAggregate: {
						/**
						 * rolesAggregate
						 */
						name: () => LocalizedString
					}
					rolesConnection: {
						/**
						 * rolesConnection
						 */
						name: () => LocalizedString
					}
					userPhonesRelationAggregate: {
						/**
						 * userPhonesRelationAggregate
						 */
						name: () => LocalizedString
					}
					userPhonesRelationConnection: {
						/**
						 * userPhonesRelationConnection
						 */
						name: () => LocalizedString
					}
					groupUserRelationAggregate: {
						/**
						 * groupUserRelationAggregate
						 */
						name: () => LocalizedString
					}
					groupUserRelationConnection: {
						/**
						 * groupUserRelationConnection
						 */
						name: () => LocalizedString
					}
					roleUserRelationAggregate: {
						/**
						 * roleUserRelationAggregate
						 */
						name: () => LocalizedString
					}
					roleUserRelationConnection: {
						/**
						 * roleUserRelationConnection
						 */
						name: () => LocalizedString
					}
					idCount: {
						/**
						 * idCount
						 */
						name: () => LocalizedString
					}
					idMax: {
						/**
						 * idMax
						 */
						name: () => LocalizedString
					}
					idMin: {
						/**
						 * idMin
						 */
						name: () => LocalizedString
					}
					nameCount: {
						/**
						 * nameCount
						 */
						name: () => LocalizedString
					}
					nameMax: {
						/**
						 * nameMax
						 */
						name: () => LocalizedString
					}
					nameMin: {
						/**
						 * nameMin
						 */
						name: () => LocalizedString
					}
					descriptionCount: {
						/**
						 * descriptionCount
						 */
						name: () => LocalizedString
					}
					descriptionMax: {
						/**
						 * descriptionMax
						 */
						name: () => LocalizedString
					}
					descriptionMin: {
						/**
						 * descriptionMin
						 */
						name: () => LocalizedString
					}
					lastNameCount: {
						/**
						 * lastNameCount
						 */
						name: () => LocalizedString
					}
					lastNameMax: {
						/**
						 * lastNameMax
						 */
						name: () => LocalizedString
					}
					lastNameMin: {
						/**
						 * lastNameMin
						 */
						name: () => LocalizedString
					}
					loginCount: {
						/**
						 * loginCount
						 */
						name: () => LocalizedString
					}
					loginMax: {
						/**
						 * loginMax
						 */
						name: () => LocalizedString
					}
					loginMin: {
						/**
						 * loginMin
						 */
						name: () => LocalizedString
					}
					saltCount: {
						/**
						 * saltCount
						 */
						name: () => LocalizedString
					}
					saltMax: {
						/**
						 * saltMax
						 */
						name: () => LocalizedString
					}
					saltMin: {
						/**
						 * saltMin
						 */
						name: () => LocalizedString
					}
					hashCount: {
						/**
						 * hashCount
						 */
						name: () => LocalizedString
					}
					hashMax: {
						/**
						 * hashMax
						 */
						name: () => LocalizedString
					}
					hashMin: {
						/**
						 * hashMin
						 */
						name: () => LocalizedString
					}
					emailCount: {
						/**
						 * emailCount
						 */
						name: () => LocalizedString
					}
					emailMax: {
						/**
						 * emailMax
						 */
						name: () => LocalizedString
					}
					emailMin: {
						/**
						 * emailMin
						 */
						name: () => LocalizedString
					}
					syncUserPolicy: {
						/**
						 * syncUserPolicy
						 */
						name: () => LocalizedString
					}
				}
			}
			UserPhonesRelation: {
				/**
				 * UserPhonesRelation
				 */
				name: () => LocalizedString
				fields: {
					id: {
						/**
						 * id
						 */
						name: () => LocalizedString
					}
					userRef: {
						/**
						 * userRef
						 */
						name: () => LocalizedString
					}
					user: {
						/**
						 * user
						 */
						name: () => LocalizedString
					}
					phonesRef: {
						/**
						 * phonesRef
						 */
						name: () => LocalizedString
					}
					isDeprecated: {
						/**
						 * isDeprecated
						 */
						name: () => LocalizedString
					}
					version: {
						/**
						 * version
						 */
						name: () => LocalizedString
					}
					realmId: {
						/**
						 * realmId
						 */
						name: () => LocalizedString
					}
					createUserId: {
						/**
						 * createUserId
						 */
						name: () => LocalizedString
					}
					createTime: {
						/**
						 * createTime
						 */
						name: () => LocalizedString
					}
					updateUserId: {
						/**
						 * updateUserId
						 */
						name: () => LocalizedString
					}
					updateTime: {
						/**
						 * updateTime
						 */
						name: () => LocalizedString
					}
					createGroupId: {
						/**
						 * createGroupId
						 */
						name: () => LocalizedString
					}
					idCount: {
						/**
						 * idCount
						 */
						name: () => LocalizedString
					}
					idMax: {
						/**
						 * idMax
						 */
						name: () => LocalizedString
					}
					idMin: {
						/**
						 * idMin
						 */
						name: () => LocalizedString
					}
					userRefCount: {
						/**
						 * userRefCount
						 */
						name: () => LocalizedString
					}
					userRefMax: {
						/**
						 * userRefMax
						 */
						name: () => LocalizedString
					}
					userRefMin: {
						/**
						 * userRefMin
						 */
						name: () => LocalizedString
					}
					phonesRefCount: {
						/**
						 * phonesRefCount
						 */
						name: () => LocalizedString
					}
					phonesRefMax: {
						/**
						 * phonesRefMax
						 */
						name: () => LocalizedString
					}
					phonesRefMin: {
						/**
						 * phonesRefMin
						 */
						name: () => LocalizedString
					}
				}
			}
		}
		enums: {
			PermissionType: {
				/**
				 * PermissionType
				 */
				name: () => LocalizedString
				values: {
					READ: {
						/**
						 * READ
						 */
						name: () => LocalizedString
					}
					WRITE: {
						/**
						 * WRITE
						 */
						name: () => LocalizedString
					}
				}
			}
		}
	}
	ui: {
		menu: {
			/**
			 * Menu
			 */
			menu: () => LocalizedString
			/**
			 * Open Menu
			 */
			open: () => LocalizedString
		}
		cursor: {
			/**
			 * Size
			 */
			size: () => LocalizedString
			/**
			 * Previous
			 */
			previous: () => LocalizedString
			/**
			 * Next
			 */
			next: () => LocalizedString
		}
		pagination: {
			/**
			 * Size
			 */
			size: () => LocalizedString
			/**
			 * {total} results
			 */
			total: (arg: { total: number }) => LocalizedString
			/**
			 * Page {current}
			 */
			current: (arg: { current: number }) => LocalizedString
			/**
			 * Previous
			 */
			previous: () => LocalizedString
			/**
			 * Next
			 */
			next: () => LocalizedString
		}
		searchInput: {
			/**
			 * Search
			 */
			placeholder: () => LocalizedString
		}
		inputList: {
			/**
			 * Add
			 */
			add: () => LocalizedString
			/**
			 * Remove
			 */
			remove: () => LocalizedString
		}
		table: {
			/**
			 * no result
			 */
			empty: () => LocalizedString
		}
		messageBox: {
			/**
			 * Cancel
			 */
			cancel: () => LocalizedString
			/**
			 * Confirm
			 */
			confirm: () => LocalizedString
		}
		button: {
			/**
			 * Search
			 */
			search: () => LocalizedString
			/**
			 * Create
			 */
			create: () => LocalizedString
			/**
			 * Remove
			 */
			remove: () => LocalizedString
			/**
			 * Unbind
			 */
			unbind: () => LocalizedString
			/**
			 * Save
			 */
			save: () => LocalizedString
			/**
			 * Back
			 */
			back: () => LocalizedString
			/**
			 * Select
			 */
			select: () => LocalizedString
		}
		themeSelect: {
			/**
			 * Theme
			 */
			btn: () => LocalizedString
			themes: {
				/**
				 * light
				 */
				light: () => LocalizedString
				/**
				 * dark
				 */
				dark: () => LocalizedString
				/**
				 * cupcake
				 */
				cupcake: () => LocalizedString
				/**
				 * bumblebee
				 */
				bumblebee: () => LocalizedString
				/**
				 * emerald
				 */
				emerald: () => LocalizedString
				/**
				 * corporate
				 */
				corporate: () => LocalizedString
				/**
				 * synthwave
				 */
				synthwave: () => LocalizedString
				/**
				 * retro
				 */
				retro: () => LocalizedString
				/**
				 * cyberpunk
				 */
				cyberpunk: () => LocalizedString
				/**
				 * valentine
				 */
				valentine: () => LocalizedString
				/**
				 * halloween
				 */
				halloween: () => LocalizedString
				/**
				 * garden
				 */
				garden: () => LocalizedString
				/**
				 * forest
				 */
				forest: () => LocalizedString
				/**
				 * aqua
				 */
				aqua: () => LocalizedString
				/**
				 * lofi
				 */
				lofi: () => LocalizedString
				/**
				 * pastel
				 */
				pastel: () => LocalizedString
				/**
				 * fantasy
				 */
				fantasy: () => LocalizedString
				/**
				 * wireframe
				 */
				wireframe: () => LocalizedString
				/**
				 * black
				 */
				black: () => LocalizedString
				/**
				 * luxury
				 */
				luxury: () => LocalizedString
				/**
				 * dracula
				 */
				dracula: () => LocalizedString
				/**
				 * cmyk
				 */
				cmyk: () => LocalizedString
				/**
				 * autumn
				 */
				autumn: () => LocalizedString
				/**
				 * business
				 */
				business: () => LocalizedString
				/**
				 * acid
				 */
				acid: () => LocalizedString
				/**
				 * lemonade
				 */
				lemonade: () => LocalizedString
				/**
				 * night
				 */
				night: () => LocalizedString
				/**
				 * coffee
				 */
				coffee: () => LocalizedString
				/**
				 * winter
				 */
				winter: () => LocalizedString
			}
		}
	}
	ui_graphql: {
		table: {
			/**
			 * Remove row?
			 */
			removeModalTitle: () => LocalizedString
			/**
			 * Edit
			 */
			editBtn: () => LocalizedString
			/**
			 * Remove
			 */
			removeBtn: () => LocalizedString
			/**
			 * Cancel
			 */
			cancelBtn: () => LocalizedString
			th: {
				/**
				 * filter
				 */
				filter: () => LocalizedString
				/**
				 * cancel
				 */
				cancel: () => LocalizedString
				/**
				 * No Sort
				 */
				noSort: () => LocalizedString
				/**
				 * ASC
				 */
				asc: () => LocalizedString
				/**
				 * DESC
				 */
				desc: () => LocalizedString
				/**
				 * Equals
				 */
				eq: () => LocalizedString
				/**
				 * Not Equals
				 */
				neq: () => LocalizedString
				/**
				 * Like
				 */
				lk: () => LocalizedString
				/**
				 * Not Like
				 */
				nlk: () => LocalizedString
				/**
				 * Greater Than
				 */
				gt: () => LocalizedString
				/**
				 * Greater Equals
				 */
				gte: () => LocalizedString
				/**
				 * Less Than
				 */
				lt: () => LocalizedString
				/**
				 * Less Equals
				 */
				lte: () => LocalizedString
				/**
				 * Is Null
				 */
				nil: () => LocalizedString
				/**
				 * Not Null
				 */
				nnil: () => LocalizedString
				/**
				 * In
				 */
				'in': () => LocalizedString
				/**
				 * Not In
				 */
				nin: () => LocalizedString
				/**
				 * Between
				 */
				bt: () => LocalizedString
				/**
				 * Not Between
				 */
				nbt: () => LocalizedString
				/**
				 * Filter..
				 */
				filterPlaceholder: () => LocalizedString
			}
			td: {
				/**
				 * save
				 */
				save: () => LocalizedString
				/**
				 * clear
				 */
				clear: () => LocalizedString
			}
		}
		grid: {
			buttons: {
				/**
				 * Refresh
				 */
				refresh: () => LocalizedString
				/**
				 * Save
				 */
				save: () => LocalizedString
				/**
				 * New
				 */
				'new': () => LocalizedString
				/**
				 * Append
				 */
				append: () => LocalizedString
				/**
				 * Remove
				 */
				remove: () => LocalizedString
				/**
				 * ok
				 */
				ok: () => LocalizedString
				/**
				 * Canel
				 */
				canel: () => LocalizedString
				/**
				 * Export
				 */
				'export': () => LocalizedString
				/**
				 * Import
				 */
				'import': () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
