// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	errors: NamespaceErrorsTranslation,
	graphence: NamespaceGraphenceTranslation,
	graphql: NamespaceGraphqlTranslation,
	ui: NamespaceUiTranslation,
	uiGraphql: NamespaceUiGraphqlTranslation
}

type RootTranslation = {}

export type NamespaceErrorsTranslation = {
	code: {
		/**
		 * A​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​f​a​i​l​e​d
		 */
		'-40101': string
		/**
		 * R​e​s​o​u​r​c​e​ ​h​a​s​ ​b​e​e​n​ ​u​p​d​a​t​e​d
		 */
		'-40900': string
		/**
		 * E​x​i​s​t​e​d​ ​u​n​i​q​u​e​ ​v​a​l​u​e​s
		 */
		'-40901': string
		/**
		 * R​e​q​u​e​t​ ​e​r​r​o​r
		 */
		'-99999': string
	}
}

export type NamespaceGraphenceTranslation = {
	login: {
		/**
		 * F​u​l​l​-​s​t​a​c​k​ ​G​r​a​p​h​Q​L​ ​d​e​v​e​l​o​p​m​e​n​t​ ​p​l​a​t​f​o​r​m​,​ ​p​o​w​e​r​e​d​ ​b​y​ ​G​r​a​p​h​Q​L​ ​S​v​e​l​t​e​ ​a​n​d​ ​R​e​a​c​t​o​r​ ​J​a​v​a
		 */
		detail: string
		/**
		 * A​c​c​o​u​n​t
		 */
		account: string
		/**
		 * L​o​g​i​n
		 */
		login: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		password: string
		/**
		 * F​o​r​g​o​t​ ​p​a​s​s​w​o​r​d​?
		 */
		forgot: string
	}
	message: {
		/**
		 * S​a​v​e​ ​s​u​c​c​e​s​s
		 */
		saveSuccess: string
		/**
		 * C​r​e​a​t​e​ ​s​u​c​c​e​s​s
		 */
		createSuccess: string
		/**
		 * R​e​m​o​v​e​ ​s​u​c​c​e​s​s
		 */
		removeSuccess: string
		/**
		 * U​n​b​i​n​d​ ​s​u​c​c​e​s​s
		 */
		unbindSuccess: string
		/**
		 * R​e​q​u​e​s​t​ ​f​a​i​l​e​d
		 */
		requestFailed: string
		/**
		 * S​a​v​e​ ​f​a​i​l​e​d
		 */
		saveFailed: string
		/**
		 * C​r​e​a​t​e​ ​f​a​i​l​e​d
		 */
		createFailed: string
		/**
		 * R​e​m​o​v​e​ ​f​a​i​l​e​d
		 */
		removeFailed: string
		/**
		 * U​n​b​i​n​d​ ​f​a​i​l​e​d
		 */
		unbindFailed: string
	}
	path: {
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * C​r​e​a​t​e​ ​{​n​a​m​e​}
		 * @param {string} name
		 */
		create: RequiredParams<'name'>
		/**
		 * S​e​l​e​c​t​ ​{​n​a​m​e​}
		 * @param {string} name
		 */
		select: RequiredParams<'name'>
	}
	components: {
		search: {
			/**
			 * S​e​a​r​c​h
			 */
			label: string
		}
		table: {
			/**
			 * R​e​m​o​v​e​ ​r​o​w​?
			 */
			removeModalTitle: string
			/**
			 * U​n​b​i​n​d​ ​r​o​w​?
			 */
			unbindModalTitle: string
			/**
			 * E​d​i​t
			 */
			editBtn: string
			/**
			 * R​e​m​o​v​e
			 */
			removeBtn: string
			/**
			 * U​n​b​i​n​d
			 */
			unbindBtn: string
			/**
			 * S​e​l​e​c​t
			 */
			selectBtn: string
		}
		sideBarMenu: {
			/**
			 * M​o​d​u​l​e​s
			 */
			modules: string
		}
		userMenu: {
			/**
			 * P​r​o​f​i​l​e
			 */
			profile: string
			/**
			 * R​e​s​e​t​ ​p​a​s​s​w​o​r​d
			 */
			password: string
			/**
			 * L​o​g​o​u​t
			 */
			logout: string
		}
		resetPassword: {
			/**
			 * O​r​i​g​i​n​a​l​ ​p​a​s​s​w​o​r​d
			 */
			password: string
			/**
			 * N​e​w​ ​p​a​s​s​w​o​r​d
			 */
			newPassword: string
			/**
			 * R​e​p​e​a​t​ ​n​e​w​ ​P​a​s​s​w​o​r​d
			 */
			repeatNewPassword: string
			/**
			 * I​n​c​o​n​s​i​s​t​e​n​t
			 */
			inconsistent: string
		}
		agg: {
			/**
			 * C​o​l​u​m​n​s
			 */
			columns: string
			/**
			 * G​r​o​u​p​ ​B​y
			 */
			groupBy: string
			/**
			 * O​r​d​e​r​ ​B​y
			 */
			orderBy: string
			/**
			 * O​p​t​i​o​n​s
			 */
			option: string
			/**
			 * F​i​l​t​e​r
			 */
			filter: string
		}
	}
}

export type NamespaceGraphqlTranslation = {
	objects: {
		CurrentUser: {
			/**
			 * C​u​r​r​e​n​t​U​s​e​r
			 */
			name: string
			fields: {
				name: {
					/**
					 * n​a​m​e
					 */
					name: string
				}
				lastName: {
					/**
					 * l​a​s​t​N​a​m​e
					 */
					name: string
				}
				login: {
					/**
					 * l​o​g​i​n
					 */
					name: string
				}
				groups: {
					/**
					 * g​r​o​u​p​s
					 */
					name: string
				}
				roles: {
					/**
					 * r​o​l​e​s
					 */
					name: string
				}
			}
		}
		File: {
			/**
			 * F​i​l​e
			 */
			name: string
			fields: {
				name: {
					/**
					 * n​a​m​e
					 */
					name: string
				}
				contentType: {
					/**
					 * c​o​n​t​e​n​t​T​y​p​e
					 */
					name: string
				}
				content: {
					/**
					 * c​o​n​t​e​n​t
					 */
					name: string
				}
				url: {
					/**
					 * u​r​l
					 */
					name: string
				}
				idCount: {
					/**
					 * i​d​C​o​u​n​t
					 */
					name: string
				}
				idMax: {
					/**
					 * i​d​M​a​x
					 */
					name: string
				}
				idMin: {
					/**
					 * i​d​M​i​n
					 */
					name: string
				}
				nameCount: {
					/**
					 * n​a​m​e​C​o​u​n​t
					 */
					name: string
				}
				nameMax: {
					/**
					 * n​a​m​e​M​a​x
					 */
					name: string
				}
				nameMin: {
					/**
					 * n​a​m​e​M​i​n
					 */
					name: string
				}
				contentTypeCount: {
					/**
					 * c​o​n​t​e​n​t​T​y​p​e​C​o​u​n​t
					 */
					name: string
				}
				contentTypeMax: {
					/**
					 * c​o​n​t​e​n​t​T​y​p​e​M​a​x
					 */
					name: string
				}
				contentTypeMin: {
					/**
					 * c​o​n​t​e​n​t​T​y​p​e​M​i​n
					 */
					name: string
				}
				contentCount: {
					/**
					 * c​o​n​t​e​n​t​C​o​u​n​t
					 */
					name: string
				}
				contentMax: {
					/**
					 * c​o​n​t​e​n​t​M​a​x
					 */
					name: string
				}
				contentMin: {
					/**
					 * c​o​n​t​e​n​t​M​i​n
					 */
					name: string
				}
				urlCount: {
					/**
					 * u​r​l​C​o​u​n​t
					 */
					name: string
				}
				urlMax: {
					/**
					 * u​r​l​M​a​x
					 */
					name: string
				}
				urlMin: {
					/**
					 * u​r​l​M​i​n
					 */
					name: string
				}
			}
		}
		Group: {
			/**
			 * G​r​o​u​p
			 */
			name: string
			fields: {
				name: {
					/**
					 * n​a​m​e
					 */
					name: string
				}
				description: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n
					 */
					name: string
				}
				path: {
					/**
					 * p​a​t​h
					 */
					name: string
				}
				deep: {
					/**
					 * d​e​e​p
					 */
					name: string
				}
				parentId: {
					/**
					 * p​a​r​e​n​t​I​d
					 */
					name: string
				}
				parent: {
					/**
					 * p​a​r​e​n​t
					 */
					name: string
				}
				subGroups: {
					/**
					 * s​u​b​G​r​o​u​p​s
					 */
					name: string
				}
				users: {
					/**
					 * u​s​e​r​s
					 */
					name: string
				}
				roles: {
					/**
					 * r​o​l​e​s
					 */
					name: string
				}
				realm: {
					/**
					 * r​e​a​l​m
					 */
					name: string
				}
				subGroupsAggregate: {
					/**
					 * s​u​b​G​r​o​u​p​s​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				usersAggregate: {
					/**
					 * u​s​e​r​s​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				rolesAggregate: {
					/**
					 * r​o​l​e​s​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				idCount: {
					/**
					 * i​d​C​o​u​n​t
					 */
					name: string
				}
				idMax: {
					/**
					 * i​d​M​a​x
					 */
					name: string
				}
				idMin: {
					/**
					 * i​d​M​i​n
					 */
					name: string
				}
				nameCount: {
					/**
					 * n​a​m​e​C​o​u​n​t
					 */
					name: string
				}
				nameMax: {
					/**
					 * n​a​m​e​M​a​x
					 */
					name: string
				}
				nameMin: {
					/**
					 * n​a​m​e​M​i​n
					 */
					name: string
				}
				descriptionCount: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​C​o​u​n​t
					 */
					name: string
				}
				descriptionMax: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​M​a​x
					 */
					name: string
				}
				descriptionMin: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​M​i​n
					 */
					name: string
				}
				pathCount: {
					/**
					 * p​a​t​h​C​o​u​n​t
					 */
					name: string
				}
				pathMax: {
					/**
					 * p​a​t​h​M​a​x
					 */
					name: string
				}
				pathMin: {
					/**
					 * p​a​t​h​M​i​n
					 */
					name: string
				}
				parentIdCount: {
					/**
					 * p​a​r​e​n​t​I​d​C​o​u​n​t
					 */
					name: string
				}
				parentIdMax: {
					/**
					 * p​a​r​e​n​t​I​d​M​a​x
					 */
					name: string
				}
				parentIdMin: {
					/**
					 * p​a​r​e​n​t​I​d​M​i​n
					 */
					name: string
				}
				deepCount: {
					/**
					 * d​e​e​p​C​o​u​n​t
					 */
					name: string
				}
				deepSum: {
					/**
					 * d​e​e​p​S​u​m
					 */
					name: string
				}
				deepAvg: {
					/**
					 * d​e​e​p​A​v​g
					 */
					name: string
				}
				deepMax: {
					/**
					 * d​e​e​p​M​a​x
					 */
					name: string
				}
				deepMin: {
					/**
					 * d​e​e​p​M​i​n
					 */
					name: string
				}
			}
		}
		Permission: {
			/**
			 * P​e​r​m​i​s​s​i​o​n
			 */
			name: string
			fields: {
				name: {
					/**
					 * n​a​m​e
					 */
					name: string
				}
				description: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n
					 */
					name: string
				}
				field: {
					/**
					 * f​i​e​l​d
					 */
					name: string
				}
				type: {
					/**
					 * t​y​p​e
					 */
					name: string
				}
				permissionType: {
					/**
					 * p​e​r​m​i​s​s​i​o​n​T​y​p​e
					 */
					name: string
				}
				roles: {
					/**
					 * r​o​l​e​s
					 */
					name: string
				}
				realm: {
					/**
					 * r​e​a​l​m
					 */
					name: string
				}
				rolesAggregate: {
					/**
					 * r​o​l​e​s​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				nameCount: {
					/**
					 * n​a​m​e​C​o​u​n​t
					 */
					name: string
				}
				nameMax: {
					/**
					 * n​a​m​e​M​a​x
					 */
					name: string
				}
				nameMin: {
					/**
					 * n​a​m​e​M​i​n
					 */
					name: string
				}
				descriptionCount: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​C​o​u​n​t
					 */
					name: string
				}
				descriptionMax: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​M​a​x
					 */
					name: string
				}
				descriptionMin: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​M​i​n
					 */
					name: string
				}
				fieldCount: {
					/**
					 * f​i​e​l​d​C​o​u​n​t
					 */
					name: string
				}
				fieldMax: {
					/**
					 * f​i​e​l​d​M​a​x
					 */
					name: string
				}
				fieldMin: {
					/**
					 * f​i​e​l​d​M​i​n
					 */
					name: string
				}
				typeCount: {
					/**
					 * t​y​p​e​C​o​u​n​t
					 */
					name: string
				}
				typeMax: {
					/**
					 * t​y​p​e​M​a​x
					 */
					name: string
				}
				typeMin: {
					/**
					 * t​y​p​e​M​i​n
					 */
					name: string
				}
			}
		}
		Policy: {
			/**
			 * P​o​l​i​c​y
			 */
			name: string
			fields: {
				ptype: {
					/**
					 * p​t​y​p​e
					 */
					name: string
				}
				v0: {
					/**
					 * v​0
					 */
					name: string
				}
				v1: {
					/**
					 * v​1
					 */
					name: string
				}
				v2: {
					/**
					 * v​2
					 */
					name: string
				}
				v3: {
					/**
					 * v​3
					 */
					name: string
				}
				v4: {
					/**
					 * v​4
					 */
					name: string
				}
				v5: {
					/**
					 * v​5
					 */
					name: string
				}
			}
		}
		Realm: {
			/**
			 * R​e​a​l​m
			 */
			name: string
			fields: {
				name: {
					/**
					 * n​a​m​e
					 */
					name: string
				}
				description: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n
					 */
					name: string
				}
				idCount: {
					/**
					 * i​d​C​o​u​n​t
					 */
					name: string
				}
				idMax: {
					/**
					 * i​d​M​a​x
					 */
					name: string
				}
				idMin: {
					/**
					 * i​d​M​i​n
					 */
					name: string
				}
				nameCount: {
					/**
					 * n​a​m​e​C​o​u​n​t
					 */
					name: string
				}
				nameMax: {
					/**
					 * n​a​m​e​M​a​x
					 */
					name: string
				}
				nameMin: {
					/**
					 * n​a​m​e​M​i​n
					 */
					name: string
				}
				descriptionCount: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​C​o​u​n​t
					 */
					name: string
				}
				descriptionMax: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​M​a​x
					 */
					name: string
				}
				descriptionMin: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​M​i​n
					 */
					name: string
				}
			}
		}
		Role: {
			/**
			 * R​o​l​e
			 */
			name: string
			fields: {
				name: {
					/**
					 * n​a​m​e
					 */
					name: string
				}
				description: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n
					 */
					name: string
				}
				users: {
					/**
					 * u​s​e​r​s
					 */
					name: string
				}
				groups: {
					/**
					 * g​r​o​u​p​s
					 */
					name: string
				}
				composites: {
					/**
					 * c​o​m​p​o​s​i​t​e​s
					 */
					name: string
				}
				permissions: {
					/**
					 * p​e​r​m​i​s​s​i​o​n​s
					 */
					name: string
				}
				realm: {
					/**
					 * r​e​a​l​m
					 */
					name: string
				}
				usersAggregate: {
					/**
					 * u​s​e​r​s​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				groupsAggregate: {
					/**
					 * g​r​o​u​p​s​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				compositesAggregate: {
					/**
					 * c​o​m​p​o​s​i​t​e​s​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				permissionsAggregate: {
					/**
					 * p​e​r​m​i​s​s​i​o​n​s​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				idCount: {
					/**
					 * i​d​C​o​u​n​t
					 */
					name: string
				}
				idMax: {
					/**
					 * i​d​M​a​x
					 */
					name: string
				}
				idMin: {
					/**
					 * i​d​M​i​n
					 */
					name: string
				}
				nameCount: {
					/**
					 * n​a​m​e​C​o​u​n​t
					 */
					name: string
				}
				nameMax: {
					/**
					 * n​a​m​e​M​a​x
					 */
					name: string
				}
				nameMin: {
					/**
					 * n​a​m​e​M​i​n
					 */
					name: string
				}
				descriptionCount: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​C​o​u​n​t
					 */
					name: string
				}
				descriptionMax: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​M​a​x
					 */
					name: string
				}
				descriptionMin: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​M​i​n
					 */
					name: string
				}
			}
		}
		User: {
			/**
			 * U​s​e​r
			 */
			name: string
			fields: {
				name: {
					/**
					 * n​a​m​e
					 */
					name: string
				}
				description: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n
					 */
					name: string
				}
				lastName: {
					/**
					 * l​a​s​t​N​a​m​e
					 */
					name: string
				}
				login: {
					/**
					 * l​o​g​i​n
					 */
					name: string
				}
				email: {
					/**
					 * e​m​a​i​l
					 */
					name: string
				}
				files: {
					/**
					 * f​i​l​e​s
					 */
					name: string
				}
				phones: {
					/**
					 * p​h​o​n​e​s
					 */
					name: string
				}
				disable: {
					/**
					 * d​i​s​a​b​l​e
					 */
					name: string
				}
				groups: {
					/**
					 * g​r​o​u​p​s
					 */
					name: string
				}
				roles: {
					/**
					 * r​o​l​e​s
					 */
					name: string
				}
				realm: {
					/**
					 * r​e​a​l​m
					 */
					name: string
				}
				groupsAggregate: {
					/**
					 * g​r​o​u​p​s​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				rolesAggregate: {
					/**
					 * r​o​l​e​s​A​g​g​r​e​g​a​t​e
					 */
					name: string
				}
				idCount: {
					/**
					 * i​d​C​o​u​n​t
					 */
					name: string
				}
				idMax: {
					/**
					 * i​d​M​a​x
					 */
					name: string
				}
				idMin: {
					/**
					 * i​d​M​i​n
					 */
					name: string
				}
				nameCount: {
					/**
					 * n​a​m​e​C​o​u​n​t
					 */
					name: string
				}
				nameMax: {
					/**
					 * n​a​m​e​M​a​x
					 */
					name: string
				}
				nameMin: {
					/**
					 * n​a​m​e​M​i​n
					 */
					name: string
				}
				descriptionCount: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​C​o​u​n​t
					 */
					name: string
				}
				descriptionMax: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​M​a​x
					 */
					name: string
				}
				descriptionMin: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n​M​i​n
					 */
					name: string
				}
				lastNameCount: {
					/**
					 * l​a​s​t​N​a​m​e​C​o​u​n​t
					 */
					name: string
				}
				lastNameMax: {
					/**
					 * l​a​s​t​N​a​m​e​M​a​x
					 */
					name: string
				}
				lastNameMin: {
					/**
					 * l​a​s​t​N​a​m​e​M​i​n
					 */
					name: string
				}
				loginCount: {
					/**
					 * l​o​g​i​n​C​o​u​n​t
					 */
					name: string
				}
				loginMax: {
					/**
					 * l​o​g​i​n​M​a​x
					 */
					name: string
				}
				loginMin: {
					/**
					 * l​o​g​i​n​M​i​n
					 */
					name: string
				}
				saltCount: {
					/**
					 * s​a​l​t​C​o​u​n​t
					 */
					name: string
				}
				saltMax: {
					/**
					 * s​a​l​t​M​a​x
					 */
					name: string
				}
				saltMin: {
					/**
					 * s​a​l​t​M​i​n
					 */
					name: string
				}
				hashCount: {
					/**
					 * h​a​s​h​C​o​u​n​t
					 */
					name: string
				}
				hashMax: {
					/**
					 * h​a​s​h​M​a​x
					 */
					name: string
				}
				hashMin: {
					/**
					 * h​a​s​h​M​i​n
					 */
					name: string
				}
				emailCount: {
					/**
					 * e​m​a​i​l​C​o​u​n​t
					 */
					name: string
				}
				emailMax: {
					/**
					 * e​m​a​i​l​M​a​x
					 */
					name: string
				}
				emailMin: {
					/**
					 * e​m​a​i​l​M​i​n
					 */
					name: string
				}
			}
		}
	}
	enums: {
		PermissionType: {
			/**
			 * P​e​r​m​i​s​s​i​o​n​T​y​p​e
			 */
			name: string
			values: {
				READ: {
					/**
					 * R​E​A​D
					 */
					name: string
				}
				WRITE: {
					/**
					 * W​R​I​T​E
					 */
					name: string
				}
			}
		}
	}
}

export type NamespaceUiTranslation = {
	menu: {
		/**
		 * M​e​n​u
		 */
		menu: string
		/**
		 * O​p​e​n​ ​M​e​n​u
		 */
		open: string
	}
	cursor: {
		/**
		 * S​i​z​e
		 */
		size: string
		/**
		 * P​r​e​v​i​o​u​s
		 */
		previous: string
		/**
		 * N​e​x​t
		 */
		next: string
	}
	pagination: {
		/**
		 * S​i​z​e
		 */
		size: string
		/**
		 * {​t​o​t​a​l​}​ ​r​e​s​u​l​t​s
		 * @param {number} total
		 */
		total: RequiredParams<'total'>
		/**
		 * P​a​g​e​ ​{​c​u​r​r​e​n​t​}
		 * @param {number} current
		 */
		current: RequiredParams<'current'>
		/**
		 * P​r​e​v​i​o​u​s
		 */
		previous: string
		/**
		 * N​e​x​t
		 */
		next: string
	}
	searchInput: {
		/**
		 * S​e​a​r​c​h
		 */
		placeholder: string
	}
	inputList: {
		/**
		 * A​d​d
		 */
		add: string
		/**
		 * R​e​m​o​v​e
		 */
		remove: string
	}
	table: {
		/**
		 * n​o​ ​r​e​s​u​l​t
		 */
		empty: string
	}
	messageBox: {
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * C​o​n​f​i​r​m
		 */
		confirm: string
	}
	button: {
		/**
		 * S​e​a​r​c​h
		 */
		search: string
		/**
		 * C​r​e​a​t​e
		 */
		create: string
		/**
		 * R​e​m​o​v​e
		 */
		remove: string
		/**
		 * U​n​b​i​n​d
		 */
		unbind: string
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * B​a​c​k
		 */
		back: string
		/**
		 * S​e​l​e​c​t
		 */
		select: string
	}
	themeSelect: {
		/**
		 * T​h​e​m​e
		 */
		btn: string
		themes: {
			/**
			 * l​i​g​h​t
			 */
			light: string
			/**
			 * d​a​r​k
			 */
			dark: string
			/**
			 * c​u​p​c​a​k​e
			 */
			cupcake: string
			/**
			 * b​u​m​b​l​e​b​e​e
			 */
			bumblebee: string
			/**
			 * e​m​e​r​a​l​d
			 */
			emerald: string
			/**
			 * c​o​r​p​o​r​a​t​e
			 */
			corporate: string
			/**
			 * s​y​n​t​h​w​a​v​e
			 */
			synthwave: string
			/**
			 * r​e​t​r​o
			 */
			retro: string
			/**
			 * c​y​b​e​r​p​u​n​k
			 */
			cyberpunk: string
			/**
			 * v​a​l​e​n​t​i​n​e
			 */
			valentine: string
			/**
			 * h​a​l​l​o​w​e​e​n
			 */
			halloween: string
			/**
			 * g​a​r​d​e​n
			 */
			garden: string
			/**
			 * f​o​r​e​s​t
			 */
			forest: string
			/**
			 * a​q​u​a
			 */
			aqua: string
			/**
			 * l​o​f​i
			 */
			lofi: string
			/**
			 * p​a​s​t​e​l
			 */
			pastel: string
			/**
			 * f​a​n​t​a​s​y
			 */
			fantasy: string
			/**
			 * w​i​r​e​f​r​a​m​e
			 */
			wireframe: string
			/**
			 * b​l​a​c​k
			 */
			black: string
			/**
			 * l​u​x​u​r​y
			 */
			luxury: string
			/**
			 * d​r​a​c​u​l​a
			 */
			dracula: string
			/**
			 * c​m​y​k
			 */
			cmyk: string
			/**
			 * a​u​t​u​m​n
			 */
			autumn: string
			/**
			 * b​u​s​i​n​e​s​s
			 */
			business: string
			/**
			 * a​c​i​d
			 */
			acid: string
			/**
			 * l​e​m​o​n​a​d​e
			 */
			lemonade: string
			/**
			 * n​i​g​h​t
			 */
			night: string
			/**
			 * c​o​f​f​e​e
			 */
			coffee: string
			/**
			 * w​i​n​t​e​r
			 */
			winter: string
		}
	}
}

export type NamespaceUiGraphqlTranslation = {
	table: {
		/**
		 * R​e​m​o​v​e​ ​r​o​w​?
		 */
		removeModalTitle: string
		/**
		 * E​d​i​t
		 */
		editBtn: string
		/**
		 * R​e​m​o​v​e
		 */
		removeBtn: string
		/**
		 * C​a​n​c​e​l
		 */
		cancelBtn: string
		th: {
			/**
			 * f​i​l​t​e​r
			 */
			filter: string
			/**
			 * c​a​n​c​e​l
			 */
			cancel: string
			/**
			 * N​o​ ​S​o​r​t
			 */
			noSort: string
			/**
			 * A​S​C
			 */
			asc: string
			/**
			 * D​E​S​C
			 */
			desc: string
			/**
			 * E​q​u​a​l​s
			 */
			eq: string
			/**
			 * N​o​t​ ​E​q​u​a​l​s
			 */
			neq: string
			/**
			 * L​i​k​e
			 */
			lk: string
			/**
			 * N​o​t​ ​L​i​k​e
			 */
			nlk: string
			/**
			 * G​r​e​a​t​e​r​ ​T​h​a​n
			 */
			gt: string
			/**
			 * G​r​e​a​t​e​r​ ​E​q​u​a​l​s
			 */
			gte: string
			/**
			 * L​e​s​s​ ​T​h​a​n
			 */
			lt: string
			/**
			 * L​e​s​s​ ​E​q​u​a​l​s
			 */
			lte: string
			/**
			 * I​s​ ​N​u​l​l
			 */
			nil: string
			/**
			 * N​o​t​ ​N​u​l​l
			 */
			nnil: string
			/**
			 * I​n
			 */
			'in': string
			/**
			 * N​o​t​ ​I​n
			 */
			nin: string
			/**
			 * B​e​t​w​e​e​n
			 */
			bt: string
			/**
			 * N​o​t​ ​B​e​t​w​e​e​n
			 */
			nbt: string
			/**
			 * F​i​l​t​e​r​.​.
			 */
			filterPlaceholder: string
		}
		td: {
			/**
			 * s​a​v​e
			 */
			save: string
			/**
			 * c​l​e​a​r
			 */
			clear: string
		}
	}
}

export type Namespaces =
	| 'errors'
	| 'graphence'
	| 'graphql'
	| 'ui'
	| 'uiGraphql'

type DisallowNamespaces = {
	/**
	 * reserved for 'errors'-namespace\
	 * you need to use the `./errors/index.ts` file instead
	 */
	errors?: "[typesafe-i18n] reserved for 'errors'-namespace. You need to use the `./errors/index.ts` file instead."

	/**
	 * reserved for 'graphence'-namespace\
	 * you need to use the `./graphence/index.ts` file instead
	 */
	graphence?: "[typesafe-i18n] reserved for 'graphence'-namespace. You need to use the `./graphence/index.ts` file instead."

	/**
	 * reserved for 'graphql'-namespace\
	 * you need to use the `./graphql/index.ts` file instead
	 */
	graphql?: "[typesafe-i18n] reserved for 'graphql'-namespace. You need to use the `./graphql/index.ts` file instead."

	/**
	 * reserved for 'ui'-namespace\
	 * you need to use the `./ui/index.ts` file instead
	 */
	ui?: "[typesafe-i18n] reserved for 'ui'-namespace. You need to use the `./ui/index.ts` file instead."

	/**
	 * reserved for 'uiGraphql'-namespace\
	 * you need to use the `./uiGraphql/index.ts` file instead
	 */
	uiGraphql?: "[typesafe-i18n] reserved for 'uiGraphql'-namespace. You need to use the `./uiGraphql/index.ts` file instead."
}

export type TranslationFunctions = {
	errors: {
		code: {
			/**
			 * Authentication failed
			 */
			'-40101': () => LocalizedString
			/**
			 * Resource has been updated
			 */
			'-40900': () => LocalizedString
			/**
			 * Existed unique values
			 */
			'-40901': () => LocalizedString
			/**
			 * Requet error
			 */
			'-99999': () => LocalizedString
		}
	}
	graphence: {
		login: {
			/**
			 * Full-stack GraphQL development platform, powered by GraphQL Svelte and Reactor Java
			 */
			detail: () => LocalizedString
			/**
			 * Account
			 */
			account: () => LocalizedString
			/**
			 * Login
			 */
			login: () => LocalizedString
			/**
			 * Password
			 */
			password: () => LocalizedString
			/**
			 * Forgot password?
			 */
			forgot: () => LocalizedString
		}
		message: {
			/**
			 * Save success
			 */
			saveSuccess: () => LocalizedString
			/**
			 * Create success
			 */
			createSuccess: () => LocalizedString
			/**
			 * Remove success
			 */
			removeSuccess: () => LocalizedString
			/**
			 * Unbind success
			 */
			unbindSuccess: () => LocalizedString
			/**
			 * Request failed
			 */
			requestFailed: () => LocalizedString
			/**
			 * Save failed
			 */
			saveFailed: () => LocalizedString
			/**
			 * Create failed
			 */
			createFailed: () => LocalizedString
			/**
			 * Remove failed
			 */
			removeFailed: () => LocalizedString
			/**
			 * Unbind failed
			 */
			unbindFailed: () => LocalizedString
		}
		path: {
			/**
			 * Home
			 */
			home: () => LocalizedString
			/**
			 * Create {name}
			 */
			create: (arg: { name: string }) => LocalizedString
			/**
			 * Select {name}
			 */
			select: (arg: { name: string }) => LocalizedString
		}
		components: {
			search: {
				/**
				 * Search
				 */
				label: () => LocalizedString
			}
			table: {
				/**
				 * Remove row?
				 */
				removeModalTitle: () => LocalizedString
				/**
				 * Unbind row?
				 */
				unbindModalTitle: () => LocalizedString
				/**
				 * Edit
				 */
				editBtn: () => LocalizedString
				/**
				 * Remove
				 */
				removeBtn: () => LocalizedString
				/**
				 * Unbind
				 */
				unbindBtn: () => LocalizedString
				/**
				 * Select
				 */
				selectBtn: () => LocalizedString
			}
			sideBarMenu: {
				/**
				 * Modules
				 */
				modules: () => LocalizedString
			}
			userMenu: {
				/**
				 * Profile
				 */
				profile: () => LocalizedString
				/**
				 * Reset password
				 */
				password: () => LocalizedString
				/**
				 * Logout
				 */
				logout: () => LocalizedString
			}
			resetPassword: {
				/**
				 * Original password
				 */
				password: () => LocalizedString
				/**
				 * New password
				 */
				newPassword: () => LocalizedString
				/**
				 * Repeat new Password
				 */
				repeatNewPassword: () => LocalizedString
				/**
				 * Inconsistent
				 */
				inconsistent: () => LocalizedString
			}
			agg: {
				/**
				 * Columns
				 */
				columns: () => LocalizedString
				/**
				 * Group By
				 */
				groupBy: () => LocalizedString
				/**
				 * Order By
				 */
				orderBy: () => LocalizedString
				/**
				 * Options
				 */
				option: () => LocalizedString
				/**
				 * Filter
				 */
				filter: () => LocalizedString
			}
		}
	}
	graphql: {
		objects: {
			CurrentUser: {
				/**
				 * CurrentUser
				 */
				name: () => LocalizedString
				fields: {
					name: {
						/**
						 * name
						 */
						name: () => LocalizedString
					}
					lastName: {
						/**
						 * lastName
						 */
						name: () => LocalizedString
					}
					login: {
						/**
						 * login
						 */
						name: () => LocalizedString
					}
					groups: {
						/**
						 * groups
						 */
						name: () => LocalizedString
					}
					roles: {
						/**
						 * roles
						 */
						name: () => LocalizedString
					}
				}
			}
			File: {
				/**
				 * File
				 */
				name: () => LocalizedString
				fields: {
					name: {
						/**
						 * name
						 */
						name: () => LocalizedString
					}
					contentType: {
						/**
						 * contentType
						 */
						name: () => LocalizedString
					}
					content: {
						/**
						 * content
						 */
						name: () => LocalizedString
					}
					url: {
						/**
						 * url
						 */
						name: () => LocalizedString
					}
					idCount: {
						/**
						 * idCount
						 */
						name: () => LocalizedString
					}
					idMax: {
						/**
						 * idMax
						 */
						name: () => LocalizedString
					}
					idMin: {
						/**
						 * idMin
						 */
						name: () => LocalizedString
					}
					nameCount: {
						/**
						 * nameCount
						 */
						name: () => LocalizedString
					}
					nameMax: {
						/**
						 * nameMax
						 */
						name: () => LocalizedString
					}
					nameMin: {
						/**
						 * nameMin
						 */
						name: () => LocalizedString
					}
					contentTypeCount: {
						/**
						 * contentTypeCount
						 */
						name: () => LocalizedString
					}
					contentTypeMax: {
						/**
						 * contentTypeMax
						 */
						name: () => LocalizedString
					}
					contentTypeMin: {
						/**
						 * contentTypeMin
						 */
						name: () => LocalizedString
					}
					contentCount: {
						/**
						 * contentCount
						 */
						name: () => LocalizedString
					}
					contentMax: {
						/**
						 * contentMax
						 */
						name: () => LocalizedString
					}
					contentMin: {
						/**
						 * contentMin
						 */
						name: () => LocalizedString
					}
					urlCount: {
						/**
						 * urlCount
						 */
						name: () => LocalizedString
					}
					urlMax: {
						/**
						 * urlMax
						 */
						name: () => LocalizedString
					}
					urlMin: {
						/**
						 * urlMin
						 */
						name: () => LocalizedString
					}
				}
			}
			Group: {
				/**
				 * Group
				 */
				name: () => LocalizedString
				fields: {
					name: {
						/**
						 * name
						 */
						name: () => LocalizedString
					}
					description: {
						/**
						 * description
						 */
						name: () => LocalizedString
					}
					path: {
						/**
						 * path
						 */
						name: () => LocalizedString
					}
					deep: {
						/**
						 * deep
						 */
						name: () => LocalizedString
					}
					parentId: {
						/**
						 * parentId
						 */
						name: () => LocalizedString
					}
					parent: {
						/**
						 * parent
						 */
						name: () => LocalizedString
					}
					subGroups: {
						/**
						 * subGroups
						 */
						name: () => LocalizedString
					}
					users: {
						/**
						 * users
						 */
						name: () => LocalizedString
					}
					roles: {
						/**
						 * roles
						 */
						name: () => LocalizedString
					}
					realm: {
						/**
						 * realm
						 */
						name: () => LocalizedString
					}
					subGroupsAggregate: {
						/**
						 * subGroupsAggregate
						 */
						name: () => LocalizedString
					}
					usersAggregate: {
						/**
						 * usersAggregate
						 */
						name: () => LocalizedString
					}
					rolesAggregate: {
						/**
						 * rolesAggregate
						 */
						name: () => LocalizedString
					}
					idCount: {
						/**
						 * idCount
						 */
						name: () => LocalizedString
					}
					idMax: {
						/**
						 * idMax
						 */
						name: () => LocalizedString
					}
					idMin: {
						/**
						 * idMin
						 */
						name: () => LocalizedString
					}
					nameCount: {
						/**
						 * nameCount
						 */
						name: () => LocalizedString
					}
					nameMax: {
						/**
						 * nameMax
						 */
						name: () => LocalizedString
					}
					nameMin: {
						/**
						 * nameMin
						 */
						name: () => LocalizedString
					}
					descriptionCount: {
						/**
						 * descriptionCount
						 */
						name: () => LocalizedString
					}
					descriptionMax: {
						/**
						 * descriptionMax
						 */
						name: () => LocalizedString
					}
					descriptionMin: {
						/**
						 * descriptionMin
						 */
						name: () => LocalizedString
					}
					pathCount: {
						/**
						 * pathCount
						 */
						name: () => LocalizedString
					}
					pathMax: {
						/**
						 * pathMax
						 */
						name: () => LocalizedString
					}
					pathMin: {
						/**
						 * pathMin
						 */
						name: () => LocalizedString
					}
					parentIdCount: {
						/**
						 * parentIdCount
						 */
						name: () => LocalizedString
					}
					parentIdMax: {
						/**
						 * parentIdMax
						 */
						name: () => LocalizedString
					}
					parentIdMin: {
						/**
						 * parentIdMin
						 */
						name: () => LocalizedString
					}
					deepCount: {
						/**
						 * deepCount
						 */
						name: () => LocalizedString
					}
					deepSum: {
						/**
						 * deepSum
						 */
						name: () => LocalizedString
					}
					deepAvg: {
						/**
						 * deepAvg
						 */
						name: () => LocalizedString
					}
					deepMax: {
						/**
						 * deepMax
						 */
						name: () => LocalizedString
					}
					deepMin: {
						/**
						 * deepMin
						 */
						name: () => LocalizedString
					}
				}
			}
			Permission: {
				/**
				 * Permission
				 */
				name: () => LocalizedString
				fields: {
					name: {
						/**
						 * name
						 */
						name: () => LocalizedString
					}
					description: {
						/**
						 * description
						 */
						name: () => LocalizedString
					}
					field: {
						/**
						 * field
						 */
						name: () => LocalizedString
					}
					type: {
						/**
						 * type
						 */
						name: () => LocalizedString
					}
					permissionType: {
						/**
						 * permissionType
						 */
						name: () => LocalizedString
					}
					roles: {
						/**
						 * roles
						 */
						name: () => LocalizedString
					}
					realm: {
						/**
						 * realm
						 */
						name: () => LocalizedString
					}
					rolesAggregate: {
						/**
						 * rolesAggregate
						 */
						name: () => LocalizedString
					}
					nameCount: {
						/**
						 * nameCount
						 */
						name: () => LocalizedString
					}
					nameMax: {
						/**
						 * nameMax
						 */
						name: () => LocalizedString
					}
					nameMin: {
						/**
						 * nameMin
						 */
						name: () => LocalizedString
					}
					descriptionCount: {
						/**
						 * descriptionCount
						 */
						name: () => LocalizedString
					}
					descriptionMax: {
						/**
						 * descriptionMax
						 */
						name: () => LocalizedString
					}
					descriptionMin: {
						/**
						 * descriptionMin
						 */
						name: () => LocalizedString
					}
					fieldCount: {
						/**
						 * fieldCount
						 */
						name: () => LocalizedString
					}
					fieldMax: {
						/**
						 * fieldMax
						 */
						name: () => LocalizedString
					}
					fieldMin: {
						/**
						 * fieldMin
						 */
						name: () => LocalizedString
					}
					typeCount: {
						/**
						 * typeCount
						 */
						name: () => LocalizedString
					}
					typeMax: {
						/**
						 * typeMax
						 */
						name: () => LocalizedString
					}
					typeMin: {
						/**
						 * typeMin
						 */
						name: () => LocalizedString
					}
				}
			}
			Policy: {
				/**
				 * Policy
				 */
				name: () => LocalizedString
				fields: {
					ptype: {
						/**
						 * ptype
						 */
						name: () => LocalizedString
					}
					v0: {
						/**
						 * v0
						 */
						name: () => LocalizedString
					}
					v1: {
						/**
						 * v1
						 */
						name: () => LocalizedString
					}
					v2: {
						/**
						 * v2
						 */
						name: () => LocalizedString
					}
					v3: {
						/**
						 * v3
						 */
						name: () => LocalizedString
					}
					v4: {
						/**
						 * v4
						 */
						name: () => LocalizedString
					}
					v5: {
						/**
						 * v5
						 */
						name: () => LocalizedString
					}
				}
			}
			Realm: {
				/**
				 * Realm
				 */
				name: () => LocalizedString
				fields: {
					name: {
						/**
						 * name
						 */
						name: () => LocalizedString
					}
					description: {
						/**
						 * description
						 */
						name: () => LocalizedString
					}
					idCount: {
						/**
						 * idCount
						 */
						name: () => LocalizedString
					}
					idMax: {
						/**
						 * idMax
						 */
						name: () => LocalizedString
					}
					idMin: {
						/**
						 * idMin
						 */
						name: () => LocalizedString
					}
					nameCount: {
						/**
						 * nameCount
						 */
						name: () => LocalizedString
					}
					nameMax: {
						/**
						 * nameMax
						 */
						name: () => LocalizedString
					}
					nameMin: {
						/**
						 * nameMin
						 */
						name: () => LocalizedString
					}
					descriptionCount: {
						/**
						 * descriptionCount
						 */
						name: () => LocalizedString
					}
					descriptionMax: {
						/**
						 * descriptionMax
						 */
						name: () => LocalizedString
					}
					descriptionMin: {
						/**
						 * descriptionMin
						 */
						name: () => LocalizedString
					}
				}
			}
			Role: {
				/**
				 * Role
				 */
				name: () => LocalizedString
				fields: {
					name: {
						/**
						 * name
						 */
						name: () => LocalizedString
					}
					description: {
						/**
						 * description
						 */
						name: () => LocalizedString
					}
					users: {
						/**
						 * users
						 */
						name: () => LocalizedString
					}
					groups: {
						/**
						 * groups
						 */
						name: () => LocalizedString
					}
					composites: {
						/**
						 * composites
						 */
						name: () => LocalizedString
					}
					permissions: {
						/**
						 * permissions
						 */
						name: () => LocalizedString
					}
					realm: {
						/**
						 * realm
						 */
						name: () => LocalizedString
					}
					usersAggregate: {
						/**
						 * usersAggregate
						 */
						name: () => LocalizedString
					}
					groupsAggregate: {
						/**
						 * groupsAggregate
						 */
						name: () => LocalizedString
					}
					compositesAggregate: {
						/**
						 * compositesAggregate
						 */
						name: () => LocalizedString
					}
					permissionsAggregate: {
						/**
						 * permissionsAggregate
						 */
						name: () => LocalizedString
					}
					idCount: {
						/**
						 * idCount
						 */
						name: () => LocalizedString
					}
					idMax: {
						/**
						 * idMax
						 */
						name: () => LocalizedString
					}
					idMin: {
						/**
						 * idMin
						 */
						name: () => LocalizedString
					}
					nameCount: {
						/**
						 * nameCount
						 */
						name: () => LocalizedString
					}
					nameMax: {
						/**
						 * nameMax
						 */
						name: () => LocalizedString
					}
					nameMin: {
						/**
						 * nameMin
						 */
						name: () => LocalizedString
					}
					descriptionCount: {
						/**
						 * descriptionCount
						 */
						name: () => LocalizedString
					}
					descriptionMax: {
						/**
						 * descriptionMax
						 */
						name: () => LocalizedString
					}
					descriptionMin: {
						/**
						 * descriptionMin
						 */
						name: () => LocalizedString
					}
				}
			}
			User: {
				/**
				 * User
				 */
				name: () => LocalizedString
				fields: {
					name: {
						/**
						 * name
						 */
						name: () => LocalizedString
					}
					description: {
						/**
						 * description
						 */
						name: () => LocalizedString
					}
					lastName: {
						/**
						 * lastName
						 */
						name: () => LocalizedString
					}
					login: {
						/**
						 * login
						 */
						name: () => LocalizedString
					}
					email: {
						/**
						 * email
						 */
						name: () => LocalizedString
					}
					files: {
						/**
						 * files
						 */
						name: () => LocalizedString
					}
					phones: {
						/**
						 * phones
						 */
						name: () => LocalizedString
					}
					disable: {
						/**
						 * disable
						 */
						name: () => LocalizedString
					}
					groups: {
						/**
						 * groups
						 */
						name: () => LocalizedString
					}
					roles: {
						/**
						 * roles
						 */
						name: () => LocalizedString
					}
					realm: {
						/**
						 * realm
						 */
						name: () => LocalizedString
					}
					groupsAggregate: {
						/**
						 * groupsAggregate
						 */
						name: () => LocalizedString
					}
					rolesAggregate: {
						/**
						 * rolesAggregate
						 */
						name: () => LocalizedString
					}
					idCount: {
						/**
						 * idCount
						 */
						name: () => LocalizedString
					}
					idMax: {
						/**
						 * idMax
						 */
						name: () => LocalizedString
					}
					idMin: {
						/**
						 * idMin
						 */
						name: () => LocalizedString
					}
					nameCount: {
						/**
						 * nameCount
						 */
						name: () => LocalizedString
					}
					nameMax: {
						/**
						 * nameMax
						 */
						name: () => LocalizedString
					}
					nameMin: {
						/**
						 * nameMin
						 */
						name: () => LocalizedString
					}
					descriptionCount: {
						/**
						 * descriptionCount
						 */
						name: () => LocalizedString
					}
					descriptionMax: {
						/**
						 * descriptionMax
						 */
						name: () => LocalizedString
					}
					descriptionMin: {
						/**
						 * descriptionMin
						 */
						name: () => LocalizedString
					}
					lastNameCount: {
						/**
						 * lastNameCount
						 */
						name: () => LocalizedString
					}
					lastNameMax: {
						/**
						 * lastNameMax
						 */
						name: () => LocalizedString
					}
					lastNameMin: {
						/**
						 * lastNameMin
						 */
						name: () => LocalizedString
					}
					loginCount: {
						/**
						 * loginCount
						 */
						name: () => LocalizedString
					}
					loginMax: {
						/**
						 * loginMax
						 */
						name: () => LocalizedString
					}
					loginMin: {
						/**
						 * loginMin
						 */
						name: () => LocalizedString
					}
					saltCount: {
						/**
						 * saltCount
						 */
						name: () => LocalizedString
					}
					saltMax: {
						/**
						 * saltMax
						 */
						name: () => LocalizedString
					}
					saltMin: {
						/**
						 * saltMin
						 */
						name: () => LocalizedString
					}
					hashCount: {
						/**
						 * hashCount
						 */
						name: () => LocalizedString
					}
					hashMax: {
						/**
						 * hashMax
						 */
						name: () => LocalizedString
					}
					hashMin: {
						/**
						 * hashMin
						 */
						name: () => LocalizedString
					}
					emailCount: {
						/**
						 * emailCount
						 */
						name: () => LocalizedString
					}
					emailMax: {
						/**
						 * emailMax
						 */
						name: () => LocalizedString
					}
					emailMin: {
						/**
						 * emailMin
						 */
						name: () => LocalizedString
					}
				}
			}
		}
		enums: {
			PermissionType: {
				/**
				 * PermissionType
				 */
				name: () => LocalizedString
				values: {
					READ: {
						/**
						 * READ
						 */
						name: () => LocalizedString
					}
					WRITE: {
						/**
						 * WRITE
						 */
						name: () => LocalizedString
					}
				}
			}
		}
	}
	ui: {
		menu: {
			/**
			 * Menu
			 */
			menu: () => LocalizedString
			/**
			 * Open Menu
			 */
			open: () => LocalizedString
		}
		cursor: {
			/**
			 * Size
			 */
			size: () => LocalizedString
			/**
			 * Previous
			 */
			previous: () => LocalizedString
			/**
			 * Next
			 */
			next: () => LocalizedString
		}
		pagination: {
			/**
			 * Size
			 */
			size: () => LocalizedString
			/**
			 * {total} results
			 */
			total: (arg: { total: number }) => LocalizedString
			/**
			 * Page {current}
			 */
			current: (arg: { current: number }) => LocalizedString
			/**
			 * Previous
			 */
			previous: () => LocalizedString
			/**
			 * Next
			 */
			next: () => LocalizedString
		}
		searchInput: {
			/**
			 * Search
			 */
			placeholder: () => LocalizedString
		}
		inputList: {
			/**
			 * Add
			 */
			add: () => LocalizedString
			/**
			 * Remove
			 */
			remove: () => LocalizedString
		}
		table: {
			/**
			 * no result
			 */
			empty: () => LocalizedString
		}
		messageBox: {
			/**
			 * Cancel
			 */
			cancel: () => LocalizedString
			/**
			 * Confirm
			 */
			confirm: () => LocalizedString
		}
		button: {
			/**
			 * Search
			 */
			search: () => LocalizedString
			/**
			 * Create
			 */
			create: () => LocalizedString
			/**
			 * Remove
			 */
			remove: () => LocalizedString
			/**
			 * Unbind
			 */
			unbind: () => LocalizedString
			/**
			 * Save
			 */
			save: () => LocalizedString
			/**
			 * Back
			 */
			back: () => LocalizedString
			/**
			 * Select
			 */
			select: () => LocalizedString
		}
		themeSelect: {
			/**
			 * Theme
			 */
			btn: () => LocalizedString
			themes: {
				/**
				 * light
				 */
				light: () => LocalizedString
				/**
				 * dark
				 */
				dark: () => LocalizedString
				/**
				 * cupcake
				 */
				cupcake: () => LocalizedString
				/**
				 * bumblebee
				 */
				bumblebee: () => LocalizedString
				/**
				 * emerald
				 */
				emerald: () => LocalizedString
				/**
				 * corporate
				 */
				corporate: () => LocalizedString
				/**
				 * synthwave
				 */
				synthwave: () => LocalizedString
				/**
				 * retro
				 */
				retro: () => LocalizedString
				/**
				 * cyberpunk
				 */
				cyberpunk: () => LocalizedString
				/**
				 * valentine
				 */
				valentine: () => LocalizedString
				/**
				 * halloween
				 */
				halloween: () => LocalizedString
				/**
				 * garden
				 */
				garden: () => LocalizedString
				/**
				 * forest
				 */
				forest: () => LocalizedString
				/**
				 * aqua
				 */
				aqua: () => LocalizedString
				/**
				 * lofi
				 */
				lofi: () => LocalizedString
				/**
				 * pastel
				 */
				pastel: () => LocalizedString
				/**
				 * fantasy
				 */
				fantasy: () => LocalizedString
				/**
				 * wireframe
				 */
				wireframe: () => LocalizedString
				/**
				 * black
				 */
				black: () => LocalizedString
				/**
				 * luxury
				 */
				luxury: () => LocalizedString
				/**
				 * dracula
				 */
				dracula: () => LocalizedString
				/**
				 * cmyk
				 */
				cmyk: () => LocalizedString
				/**
				 * autumn
				 */
				autumn: () => LocalizedString
				/**
				 * business
				 */
				business: () => LocalizedString
				/**
				 * acid
				 */
				acid: () => LocalizedString
				/**
				 * lemonade
				 */
				lemonade: () => LocalizedString
				/**
				 * night
				 */
				night: () => LocalizedString
				/**
				 * coffee
				 */
				coffee: () => LocalizedString
				/**
				 * winter
				 */
				winter: () => LocalizedString
			}
		}
	}
	uiGraphql: {
		table: {
			/**
			 * Remove row?
			 */
			removeModalTitle: () => LocalizedString
			/**
			 * Edit
			 */
			editBtn: () => LocalizedString
			/**
			 * Remove
			 */
			removeBtn: () => LocalizedString
			/**
			 * Cancel
			 */
			cancelBtn: () => LocalizedString
			th: {
				/**
				 * filter
				 */
				filter: () => LocalizedString
				/**
				 * cancel
				 */
				cancel: () => LocalizedString
				/**
				 * No Sort
				 */
				noSort: () => LocalizedString
				/**
				 * ASC
				 */
				asc: () => LocalizedString
				/**
				 * DESC
				 */
				desc: () => LocalizedString
				/**
				 * Equals
				 */
				eq: () => LocalizedString
				/**
				 * Not Equals
				 */
				neq: () => LocalizedString
				/**
				 * Like
				 */
				lk: () => LocalizedString
				/**
				 * Not Like
				 */
				nlk: () => LocalizedString
				/**
				 * Greater Than
				 */
				gt: () => LocalizedString
				/**
				 * Greater Equals
				 */
				gte: () => LocalizedString
				/**
				 * Less Than
				 */
				lt: () => LocalizedString
				/**
				 * Less Equals
				 */
				lte: () => LocalizedString
				/**
				 * Is Null
				 */
				nil: () => LocalizedString
				/**
				 * Not Null
				 */
				nnil: () => LocalizedString
				/**
				 * In
				 */
				'in': () => LocalizedString
				/**
				 * Not In
				 */
				nin: () => LocalizedString
				/**
				 * Between
				 */
				bt: () => LocalizedString
				/**
				 * Not Between
				 */
				nbt: () => LocalizedString
				/**
				 * Filter..
				 */
				filterPlaceholder: () => LocalizedString
			}
			td: {
				/**
				 * save
				 */
				save: () => LocalizedString
				/**
				 * clear
				 */
				clear: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
