// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters'
import type { Locales, Translations } from './i18n-types'
import { loadedFormatters, loadedLocales, locales } from './i18n-util'

import en from './en'
import zh from './zh'

import en_graphql from './en/graphql'
import en_ui from './en/ui'
import en_uiGraphql from './en/uiGraphql'
import en_web from './en/web'
import zh_graphql from './zh/graphql'
import zh_ui from './zh/ui'
import zh_uiGraphql from './zh/uiGraphql'
import zh_web from './zh/web'

const localeTranslations = {
	en: {
		...en,
		graphql: en_graphql,
		ui: en_ui,
		uiGraphql: en_uiGraphql,
		web: en_web
	},
	zh: {
		...zh,
		graphql: zh_graphql,
		ui: zh_ui,
		uiGraphql: zh_uiGraphql,
		web: zh_web
	},
}

export const loadLocale = (locale: Locales): void => {
	if (loadedLocales[locale]) return

	loadedLocales[locale] = localeTranslations[locale] as unknown as Translations
	loadFormatters(locale)
}

export const loadAllLocales = (): void => locales.forEach(loadLocale)

export const loadFormatters = (locale: Locales): void =>
	void (loadedFormatters[locale] = initFormatters(locale))
