// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	graphql: NamespaceGraphqlTranslation,
	ui: NamespaceUiTranslation,
	uiGraphql: NamespaceUiGraphqlTranslation,
	web: NamespaceWebTranslation
}

type RootTranslation = {}

export type NamespaceGraphqlTranslation = {
	objects: {
		CurrentUser: {
			/**
			 * C​u​r​r​e​n​t​U​s​e​r
			 */
			name: string
			fields: {
				name: {
					/**
					 * n​a​m​e
					 */
					name: string
				}
				lastName: {
					/**
					 * l​a​s​t​N​a​m​e
					 */
					name: string
				}
				login: {
					/**
					 * l​o​g​i​n
					 */
					name: string
				}
				groups: {
					/**
					 * g​r​o​u​p​s
					 */
					name: string
				}
				roles: {
					/**
					 * r​o​l​e​s
					 */
					name: string
				}
			}
		}
		Group: {
			/**
			 * G​r​o​u​p
			 */
			name: string
			fields: {
				name: {
					/**
					 * n​a​m​e
					 */
					name: string
				}
				path: {
					/**
					 * p​a​t​h
					 */
					name: string
				}
				deep: {
					/**
					 * d​e​e​p
					 */
					name: string
				}
				parent: {
					/**
					 * p​a​r​e​n​t
					 */
					name: string
				}
				subGroups: {
					/**
					 * s​u​b​G​r​o​u​p​s
					 */
					name: string
				}
				users: {
					/**
					 * u​s​e​r​s
					 */
					name: string
				}
				roles: {
					/**
					 * r​o​l​e​s
					 */
					name: string
				}
				realm: {
					/**
					 * r​e​a​l​m
					 */
					name: string
				}
			}
		}
		Mutation: {
			/**
			 * M​u​t​a​t​i​o​n
			 */
			name: string
			fields: {
				user: {
					/**
					 * u​s​e​r
					 */
					name: string
				}
				userList: {
					/**
					 * u​s​e​r​L​i​s​t
					 */
					name: string
				}
				role: {
					/**
					 * r​o​l​e
					 */
					name: string
				}
				roleList: {
					/**
					 * r​o​l​e​L​i​s​t
					 */
					name: string
				}
				group: {
					/**
					 * g​r​o​u​p
					 */
					name: string
				}
				groupList: {
					/**
					 * g​r​o​u​p​L​i​s​t
					 */
					name: string
				}
				realm: {
					/**
					 * r​e​a​l​m
					 */
					name: string
				}
				realmList: {
					/**
					 * r​e​a​l​m​L​i​s​t
					 */
					name: string
				}
				permission: {
					/**
					 * p​e​r​m​i​s​s​i​o​n
					 */
					name: string
				}
				permissionList: {
					/**
					 * p​e​r​m​i​s​s​i​o​n​L​i​s​t
					 */
					name: string
				}
				login: {
					/**
					 * l​o​g​i​n
					 */
					name: string
				}
			}
		}
		Permission: {
			/**
			 * P​e​r​m​i​s​s​i​o​n
			 */
			name: string
			fields: {
				name: {
					/**
					 * n​a​m​e
					 */
					name: string
				}
				field: {
					/**
					 * f​i​e​l​d
					 */
					name: string
				}
				type: {
					/**
					 * t​y​p​e
					 */
					name: string
				}
				permissionType: {
					/**
					 * p​e​r​m​i​s​s​i​o​n​T​y​p​e
					 */
					name: string
				}
				description: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n
					 */
					name: string
				}
				roles: {
					/**
					 * r​o​l​e​s
					 */
					name: string
				}
				realm: {
					/**
					 * r​e​a​l​m
					 */
					name: string
				}
			}
		}
		Query: {
			/**
			 * Q​u​e​r​y
			 */
			name: string
			fields: {
				user: {
					/**
					 * u​s​e​r
					 */
					name: string
				}
				userList: {
					/**
					 * u​s​e​r​L​i​s​t
					 */
					name: string
				}
				role: {
					/**
					 * r​o​l​e
					 */
					name: string
				}
				roleList: {
					/**
					 * r​o​l​e​L​i​s​t
					 */
					name: string
				}
				group: {
					/**
					 * g​r​o​u​p
					 */
					name: string
				}
				groupList: {
					/**
					 * g​r​o​u​p​L​i​s​t
					 */
					name: string
				}
				realm: {
					/**
					 * r​e​a​l​m
					 */
					name: string
				}
				realmList: {
					/**
					 * r​e​a​l​m​L​i​s​t
					 */
					name: string
				}
				permission: {
					/**
					 * p​e​r​m​i​s​s​i​o​n
					 */
					name: string
				}
				permissionList: {
					/**
					 * p​e​r​m​i​s​s​i​o​n​L​i​s​t
					 */
					name: string
				}
				current: {
					/**
					 * c​u​r​r​e​n​t
					 */
					name: string
				}
				currentPermissionList: {
					/**
					 * c​u​r​r​e​n​t​P​e​r​m​i​s​s​i​o​n​L​i​s​t
					 */
					name: string
				}
			}
		}
		Realm: {
			/**
			 * R​e​a​l​m
			 */
			name: string
			fields: {
				name: {
					/**
					 * n​a​m​e
					 */
					name: string
				}
			}
		}
		Role: {
			/**
			 * R​o​l​e
			 */
			name: string
			fields: {
				name: {
					/**
					 * n​a​m​e
					 */
					name: string
				}
				description: {
					/**
					 * d​e​s​c​r​i​p​t​i​o​n
					 */
					name: string
				}
				users: {
					/**
					 * u​s​e​r​s
					 */
					name: string
				}
				groups: {
					/**
					 * g​r​o​u​p​s
					 */
					name: string
				}
				composites: {
					/**
					 * c​o​m​p​o​s​i​t​e​s
					 */
					name: string
				}
				permissions: {
					/**
					 * p​e​r​m​i​s​s​i​o​n​s
					 */
					name: string
				}
				realm: {
					/**
					 * r​e​a​l​m
					 */
					name: string
				}
			}
		}
		Subscription: {
			/**
			 * S​u​b​s​c​r​i​p​t​i​o​n
			 */
			name: string
			fields: {
				user: {
					/**
					 * u​s​e​r
					 */
					name: string
				}
				userList: {
					/**
					 * u​s​e​r​L​i​s​t
					 */
					name: string
				}
				role: {
					/**
					 * r​o​l​e
					 */
					name: string
				}
				roleList: {
					/**
					 * r​o​l​e​L​i​s​t
					 */
					name: string
				}
				group: {
					/**
					 * g​r​o​u​p
					 */
					name: string
				}
				groupList: {
					/**
					 * g​r​o​u​p​L​i​s​t
					 */
					name: string
				}
				realm: {
					/**
					 * r​e​a​l​m
					 */
					name: string
				}
				realmList: {
					/**
					 * r​e​a​l​m​L​i​s​t
					 */
					name: string
				}
				permission: {
					/**
					 * p​e​r​m​i​s​s​i​o​n
					 */
					name: string
				}
				permissionList: {
					/**
					 * p​e​r​m​i​s​s​i​o​n​L​i​s​t
					 */
					name: string
				}
			}
		}
		User: {
			/**
			 * U​s​e​r
			 */
			name: string
			fields: {
				name: {
					/**
					 * n​a​m​e
					 */
					name: string
				}
				lastName: {
					/**
					 * l​a​s​t​N​a​m​e
					 */
					name: string
				}
				login: {
					/**
					 * l​o​g​i​n
					 */
					name: string
				}
				email: {
					/**
					 * e​m​a​i​l
					 */
					name: string
				}
				phones: {
					/**
					 * p​h​o​n​e​s
					 */
					name: string
				}
				disable: {
					/**
					 * d​i​s​a​b​l​e
					 */
					name: string
				}
				groups: {
					/**
					 * g​r​o​u​p​s
					 */
					name: string
				}
				roles: {
					/**
					 * r​o​l​e​s
					 */
					name: string
				}
				realm: {
					/**
					 * r​e​a​l​m
					 */
					name: string
				}
			}
		}
	}
	enums: {
		PermissionType: {
			/**
			 * P​e​r​m​i​s​s​i​o​n​T​y​p​e
			 */
			name: string
			values: {
				READ: {
					/**
					 * R​E​A​D
					 */
					name: string
				}
				WRITE: {
					/**
					 * W​R​I​T​E
					 */
					name: string
				}
			}
		}
	}
}

export type NamespaceUiTranslation = {
	menu: {
		/**
		 * M​e​n​u
		 */
		menu: string
		/**
		 * O​p​e​n​ ​M​e​n​u
		 */
		open: string
	}
	cursor: {
		/**
		 * S​i​z​e
		 */
		size: string
		/**
		 * P​r​e​v​i​o​u​s
		 */
		previous: string
		/**
		 * N​e​x​t
		 */
		next: string
	}
	pagination: {
		/**
		 * S​i​z​e
		 */
		size: string
		/**
		 * {​t​o​t​a​l​}​ ​r​e​s​u​l​t​s
		 * @param {number} total
		 */
		total: RequiredParams<'total'>
		/**
		 * P​a​g​e​ ​{​c​u​r​r​e​n​t​}
		 * @param {number} current
		 */
		current: RequiredParams<'current'>
		/**
		 * P​r​e​v​i​o​u​s
		 */
		previous: string
		/**
		 * N​e​x​t
		 */
		next: string
	}
	searchInput: {
		/**
		 * S​e​a​r​c​h
		 */
		placeholder: string
	}
	inputList: {
		/**
		 * A​d​d
		 */
		add: string
		/**
		 * R​e​m​o​v​e
		 */
		remove: string
	}
	table: {
		/**
		 * n​o​ ​r​e​s​u​l​t
		 */
		empty: string
	}
	messageBox: {
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * C​o​n​f​i​r​m
		 */
		confirm: string
	}
	button: {
		/**
		 * S​e​a​r​c​h
		 */
		search: string
		/**
		 * C​r​e​a​t​e
		 */
		create: string
		/**
		 * R​e​m​o​v​e
		 */
		remove: string
		/**
		 * U​n​b​i​n​d
		 */
		unbind: string
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * B​a​c​k
		 */
		back: string
		/**
		 * S​e​l​e​c​t
		 */
		select: string
	}
}

export type NamespaceUiGraphqlTranslation = {
	table: {
		/**
		 * R​e​m​o​v​e​ ​r​o​w​?
		 */
		removeModalTitle: string
		/**
		 * E​d​i​t
		 */
		editBtn: string
		/**
		 * R​e​m​o​v​e
		 */
		removeBtn: string
		/**
		 * C​a​n​c​e​l
		 */
		cancelBtn: string
		th: {
			/**
			 * f​i​l​t​e​r
			 */
			filter: string
			/**
			 * c​a​n​c​e​l
			 */
			cancel: string
			/**
			 * N​o​ ​S​o​r​t
			 */
			noSort: string
			/**
			 * A​S​C
			 */
			asc: string
			/**
			 * D​E​S​C
			 */
			desc: string
			/**
			 * E​q​u​a​l​s
			 */
			eq: string
			/**
			 * N​o​t​ ​E​q​u​a​l​s
			 */
			neq: string
			/**
			 * L​i​k​e
			 */
			lk: string
			/**
			 * N​o​t​ ​L​i​k​e
			 */
			nlk: string
			/**
			 * G​r​e​a​t​e​r​ ​T​h​a​n
			 */
			gt: string
			/**
			 * G​r​e​a​t​e​r​ ​E​q​u​a​l​s
			 */
			gte: string
			/**
			 * L​e​s​s​ ​T​h​a​n
			 */
			lt: string
			/**
			 * L​e​s​s​ ​E​q​u​a​l​s
			 */
			lte: string
			/**
			 * I​s​ ​N​u​l​l
			 */
			nil: string
			/**
			 * N​o​t​ ​N​u​l​l
			 */
			nnil: string
			/**
			 * I​n
			 */
			'in': string
			/**
			 * N​o​t​ ​I​n
			 */
			nin: string
			/**
			 * B​e​t​w​e​e​n
			 */
			bt: string
			/**
			 * N​o​t​ ​B​e​t​w​e​e​n
			 */
			nbt: string
			/**
			 * F​i​l​t​e​r​.​.
			 */
			filterPlaceholder: string
		}
		td: {
			/**
			 * s​a​v​e
			 */
			save: string
			/**
			 * c​l​e​a​r
			 */
			clear: string
		}
	}
}

export type NamespaceWebTranslation = {
	/**
	 * W​e​l​c​o​m​e​ ​t​o​ ​{​n​a​m​e​}
	 * @param {string} name
	 */
	welcome: RequiredParams<'name'>
	login: {
		/**
		 * F​u​l​l​-​s​t​a​c​k​ ​G​r​a​p​h​Q​L​ ​d​e​v​e​l​o​p​m​e​n​t​ ​p​l​a​t​f​o​r​m​,​ ​p​o​w​e​r​e​d​ ​b​y​ ​G​r​a​p​h​Q​L​ ​S​v​e​l​t​e​ ​a​n​d​ ​R​e​a​c​t​o​r​ ​J​a​v​a
		 */
		detail: string
		/**
		 * A​c​c​o​u​n​t
		 */
		account: string
		/**
		 * L​o​g​i​n
		 */
		login: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		password: string
		/**
		 * F​o​r​g​o​t​ ​p​a​s​s​w​o​r​d​?
		 */
		forgot: string
	}
	localeName: {
		/**
		 * E​n​g​l​i​s​h
		 */
		en: string
		/**
		 * C​h​i​n​e​s​e
		 */
		zh: string
	}
	message: {
		/**
		 * S​a​v​e​ ​s​u​c​c​e​s​s
		 */
		saveSuccess: string
		/**
		 * C​r​e​a​t​e​ ​s​u​c​c​e​s​s
		 */
		createSuccess: string
		/**
		 * R​e​m​o​v​e​ ​s​u​c​c​e​s​s
		 */
		removeSuccess: string
		/**
		 * U​n​b​i​n​d​ ​s​u​c​c​e​s​s
		 */
		unbindSuccess: string
		/**
		 * R​e​q​u​e​s​t​ ​f​a​i​l​e​d
		 */
		requestFailed: string
		/**
		 * S​a​v​e​ ​f​a​i​l​e​d
		 */
		saveFailed: string
		/**
		 * C​r​e​a​t​e​ ​f​a​i​l​e​d
		 */
		createFailed: string
		/**
		 * R​e​m​o​v​e​ ​f​a​i​l​e​d
		 */
		removeFailed: string
		/**
		 * U​n​b​i​n​d​ ​f​a​i​l​e​d
		 */
		unbindFailed: string
	}
	path: {
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * C​r​e​a​t​e​ ​{​n​a​m​e​}
		 * @param {string} name
		 */
		create: RequiredParams<'name'>
		/**
		 * S​e​l​e​c​t​ ​{​n​a​m​e​}
		 * @param {string} name
		 */
		select: RequiredParams<'name'>
	}
	components: {
		search: {
			/**
			 * S​e​a​r​c​h
			 */
			label: string
		}
		themeSelect: {
			/**
			 * T​h​e​m​e
			 */
			btn: string
			themes: {
				/**
				 * l​i​g​h​t
				 */
				light: string
				/**
				 * d​a​r​k
				 */
				dark: string
				/**
				 * c​u​p​c​a​k​e
				 */
				cupcake: string
				/**
				 * b​u​m​b​l​e​b​e​e
				 */
				bumblebee: string
				/**
				 * e​m​e​r​a​l​d
				 */
				emerald: string
				/**
				 * c​o​r​p​o​r​a​t​e
				 */
				corporate: string
				/**
				 * s​y​n​t​h​w​a​v​e
				 */
				synthwave: string
				/**
				 * r​e​t​r​o
				 */
				retro: string
				/**
				 * c​y​b​e​r​p​u​n​k
				 */
				cyberpunk: string
				/**
				 * v​a​l​e​n​t​i​n​e
				 */
				valentine: string
				/**
				 * h​a​l​l​o​w​e​e​n
				 */
				halloween: string
				/**
				 * g​a​r​d​e​n
				 */
				garden: string
				/**
				 * f​o​r​e​s​t
				 */
				forest: string
				/**
				 * a​q​u​a
				 */
				aqua: string
				/**
				 * l​o​f​i
				 */
				lofi: string
				/**
				 * p​a​s​t​e​l
				 */
				pastel: string
				/**
				 * f​a​n​t​a​s​y
				 */
				fantasy: string
				/**
				 * w​i​r​e​f​r​a​m​e
				 */
				wireframe: string
				/**
				 * b​l​a​c​k
				 */
				black: string
				/**
				 * l​u​x​u​r​y
				 */
				luxury: string
				/**
				 * d​r​a​c​u​l​a
				 */
				dracula: string
				/**
				 * c​m​y​k
				 */
				cmyk: string
				/**
				 * a​u​t​u​m​n
				 */
				autumn: string
				/**
				 * b​u​s​i​n​e​s​s
				 */
				business: string
				/**
				 * a​c​i​d
				 */
				acid: string
				/**
				 * l​e​m​o​n​a​d​e
				 */
				lemonade: string
				/**
				 * n​i​g​h​t
				 */
				night: string
				/**
				 * c​o​f​f​e​e
				 */
				coffee: string
				/**
				 * w​i​n​t​e​r
				 */
				winter: string
			}
		}
		table: {
			/**
			 * R​e​m​o​v​e​ ​r​o​w​?
			 */
			removeModalTitle: string
			/**
			 * U​n​b​i​n​d​ ​r​o​w​?
			 */
			unbindModalTitle: string
			/**
			 * E​d​i​t
			 */
			editBtn: string
			/**
			 * R​e​m​o​v​e
			 */
			removeBtn: string
			/**
			 * U​n​b​i​n​d
			 */
			unbindBtn: string
			/**
			 * S​e​l​e​c​t
			 */
			selectBtn: string
		}
		userMenu: {
			/**
			 * P​r​o​f​i​l​e
			 */
			profile: string
			/**
			 * S​e​t​t​i​n​g​s
			 */
			settings: string
			/**
			 * L​o​g​o​u​t
			 */
			logout: string
		}
	}
	errors: {
		/**
		 * A​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​f​a​i​l​e​d
		 */
		'-40101': string
	}
}

export type Namespaces =
	| 'graphql'
	| 'ui'
	| 'uiGraphql'
	| 'web'

type DisallowNamespaces = {
	/**
	 * reserved for 'graphql'-namespace\
	 * you need to use the `./graphql/index.ts` file instead
	 */
	graphql?: "[typesafe-i18n] reserved for 'graphql'-namespace. You need to use the `./graphql/index.ts` file instead."

	/**
	 * reserved for 'ui'-namespace\
	 * you need to use the `./ui/index.ts` file instead
	 */
	ui?: "[typesafe-i18n] reserved for 'ui'-namespace. You need to use the `./ui/index.ts` file instead."

	/**
	 * reserved for 'uiGraphql'-namespace\
	 * you need to use the `./uiGraphql/index.ts` file instead
	 */
	uiGraphql?: "[typesafe-i18n] reserved for 'uiGraphql'-namespace. You need to use the `./uiGraphql/index.ts` file instead."

	/**
	 * reserved for 'web'-namespace\
	 * you need to use the `./web/index.ts` file instead
	 */
	web?: "[typesafe-i18n] reserved for 'web'-namespace. You need to use the `./web/index.ts` file instead."
}

export type TranslationFunctions = {
	graphql: {
		objects: {
			CurrentUser: {
				/**
				 * CurrentUser
				 */
				name: () => LocalizedString
				fields: {
					name: {
						/**
						 * name
						 */
						name: () => LocalizedString
					}
					lastName: {
						/**
						 * lastName
						 */
						name: () => LocalizedString
					}
					login: {
						/**
						 * login
						 */
						name: () => LocalizedString
					}
					groups: {
						/**
						 * groups
						 */
						name: () => LocalizedString
					}
					roles: {
						/**
						 * roles
						 */
						name: () => LocalizedString
					}
				}
			}
			Group: {
				/**
				 * Group
				 */
				name: () => LocalizedString
				fields: {
					name: {
						/**
						 * name
						 */
						name: () => LocalizedString
					}
					path: {
						/**
						 * path
						 */
						name: () => LocalizedString
					}
					deep: {
						/**
						 * deep
						 */
						name: () => LocalizedString
					}
					parent: {
						/**
						 * parent
						 */
						name: () => LocalizedString
					}
					subGroups: {
						/**
						 * subGroups
						 */
						name: () => LocalizedString
					}
					users: {
						/**
						 * users
						 */
						name: () => LocalizedString
					}
					roles: {
						/**
						 * roles
						 */
						name: () => LocalizedString
					}
					realm: {
						/**
						 * realm
						 */
						name: () => LocalizedString
					}
				}
			}
			Mutation: {
				/**
				 * Mutation
				 */
				name: () => LocalizedString
				fields: {
					user: {
						/**
						 * user
						 */
						name: () => LocalizedString
					}
					userList: {
						/**
						 * userList
						 */
						name: () => LocalizedString
					}
					role: {
						/**
						 * role
						 */
						name: () => LocalizedString
					}
					roleList: {
						/**
						 * roleList
						 */
						name: () => LocalizedString
					}
					group: {
						/**
						 * group
						 */
						name: () => LocalizedString
					}
					groupList: {
						/**
						 * groupList
						 */
						name: () => LocalizedString
					}
					realm: {
						/**
						 * realm
						 */
						name: () => LocalizedString
					}
					realmList: {
						/**
						 * realmList
						 */
						name: () => LocalizedString
					}
					permission: {
						/**
						 * permission
						 */
						name: () => LocalizedString
					}
					permissionList: {
						/**
						 * permissionList
						 */
						name: () => LocalizedString
					}
					login: {
						/**
						 * login
						 */
						name: () => LocalizedString
					}
				}
			}
			Permission: {
				/**
				 * Permission
				 */
				name: () => LocalizedString
				fields: {
					name: {
						/**
						 * name
						 */
						name: () => LocalizedString
					}
					field: {
						/**
						 * field
						 */
						name: () => LocalizedString
					}
					type: {
						/**
						 * type
						 */
						name: () => LocalizedString
					}
					permissionType: {
						/**
						 * permissionType
						 */
						name: () => LocalizedString
					}
					description: {
						/**
						 * description
						 */
						name: () => LocalizedString
					}
					roles: {
						/**
						 * roles
						 */
						name: () => LocalizedString
					}
					realm: {
						/**
						 * realm
						 */
						name: () => LocalizedString
					}
				}
			}
			Query: {
				/**
				 * Query
				 */
				name: () => LocalizedString
				fields: {
					user: {
						/**
						 * user
						 */
						name: () => LocalizedString
					}
					userList: {
						/**
						 * userList
						 */
						name: () => LocalizedString
					}
					role: {
						/**
						 * role
						 */
						name: () => LocalizedString
					}
					roleList: {
						/**
						 * roleList
						 */
						name: () => LocalizedString
					}
					group: {
						/**
						 * group
						 */
						name: () => LocalizedString
					}
					groupList: {
						/**
						 * groupList
						 */
						name: () => LocalizedString
					}
					realm: {
						/**
						 * realm
						 */
						name: () => LocalizedString
					}
					realmList: {
						/**
						 * realmList
						 */
						name: () => LocalizedString
					}
					permission: {
						/**
						 * permission
						 */
						name: () => LocalizedString
					}
					permissionList: {
						/**
						 * permissionList
						 */
						name: () => LocalizedString
					}
					current: {
						/**
						 * current
						 */
						name: () => LocalizedString
					}
					currentPermissionList: {
						/**
						 * currentPermissionList
						 */
						name: () => LocalizedString
					}
				}
			}
			Realm: {
				/**
				 * Realm
				 */
				name: () => LocalizedString
				fields: {
					name: {
						/**
						 * name
						 */
						name: () => LocalizedString
					}
				}
			}
			Role: {
				/**
				 * Role
				 */
				name: () => LocalizedString
				fields: {
					name: {
						/**
						 * name
						 */
						name: () => LocalizedString
					}
					description: {
						/**
						 * description
						 */
						name: () => LocalizedString
					}
					users: {
						/**
						 * users
						 */
						name: () => LocalizedString
					}
					groups: {
						/**
						 * groups
						 */
						name: () => LocalizedString
					}
					composites: {
						/**
						 * composites
						 */
						name: () => LocalizedString
					}
					permissions: {
						/**
						 * permissions
						 */
						name: () => LocalizedString
					}
					realm: {
						/**
						 * realm
						 */
						name: () => LocalizedString
					}
				}
			}
			Subscription: {
				/**
				 * Subscription
				 */
				name: () => LocalizedString
				fields: {
					user: {
						/**
						 * user
						 */
						name: () => LocalizedString
					}
					userList: {
						/**
						 * userList
						 */
						name: () => LocalizedString
					}
					role: {
						/**
						 * role
						 */
						name: () => LocalizedString
					}
					roleList: {
						/**
						 * roleList
						 */
						name: () => LocalizedString
					}
					group: {
						/**
						 * group
						 */
						name: () => LocalizedString
					}
					groupList: {
						/**
						 * groupList
						 */
						name: () => LocalizedString
					}
					realm: {
						/**
						 * realm
						 */
						name: () => LocalizedString
					}
					realmList: {
						/**
						 * realmList
						 */
						name: () => LocalizedString
					}
					permission: {
						/**
						 * permission
						 */
						name: () => LocalizedString
					}
					permissionList: {
						/**
						 * permissionList
						 */
						name: () => LocalizedString
					}
				}
			}
			User: {
				/**
				 * User
				 */
				name: () => LocalizedString
				fields: {
					name: {
						/**
						 * name
						 */
						name: () => LocalizedString
					}
					lastName: {
						/**
						 * lastName
						 */
						name: () => LocalizedString
					}
					login: {
						/**
						 * login
						 */
						name: () => LocalizedString
					}
					email: {
						/**
						 * email
						 */
						name: () => LocalizedString
					}
					phones: {
						/**
						 * phones
						 */
						name: () => LocalizedString
					}
					disable: {
						/**
						 * disable
						 */
						name: () => LocalizedString
					}
					groups: {
						/**
						 * groups
						 */
						name: () => LocalizedString
					}
					roles: {
						/**
						 * roles
						 */
						name: () => LocalizedString
					}
					realm: {
						/**
						 * realm
						 */
						name: () => LocalizedString
					}
				}
			}
		}
		enums: {
			PermissionType: {
				/**
				 * PermissionType
				 */
				name: () => LocalizedString
				values: {
					READ: {
						/**
						 * READ
						 */
						name: () => LocalizedString
					}
					WRITE: {
						/**
						 * WRITE
						 */
						name: () => LocalizedString
					}
				}
			}
		}
	}
	ui: {
		menu: {
			/**
			 * Menu
			 */
			menu: () => LocalizedString
			/**
			 * Open Menu
			 */
			open: () => LocalizedString
		}
		cursor: {
			/**
			 * Size
			 */
			size: () => LocalizedString
			/**
			 * Previous
			 */
			previous: () => LocalizedString
			/**
			 * Next
			 */
			next: () => LocalizedString
		}
		pagination: {
			/**
			 * Size
			 */
			size: () => LocalizedString
			/**
			 * {total} results
			 */
			total: (arg: { total: number }) => LocalizedString
			/**
			 * Page {current}
			 */
			current: (arg: { current: number }) => LocalizedString
			/**
			 * Previous
			 */
			previous: () => LocalizedString
			/**
			 * Next
			 */
			next: () => LocalizedString
		}
		searchInput: {
			/**
			 * Search
			 */
			placeholder: () => LocalizedString
		}
		inputList: {
			/**
			 * Add
			 */
			add: () => LocalizedString
			/**
			 * Remove
			 */
			remove: () => LocalizedString
		}
		table: {
			/**
			 * no result
			 */
			empty: () => LocalizedString
		}
		messageBox: {
			/**
			 * Cancel
			 */
			cancel: () => LocalizedString
			/**
			 * Confirm
			 */
			confirm: () => LocalizedString
		}
		button: {
			/**
			 * Search
			 */
			search: () => LocalizedString
			/**
			 * Create
			 */
			create: () => LocalizedString
			/**
			 * Remove
			 */
			remove: () => LocalizedString
			/**
			 * Unbind
			 */
			unbind: () => LocalizedString
			/**
			 * Save
			 */
			save: () => LocalizedString
			/**
			 * Back
			 */
			back: () => LocalizedString
			/**
			 * Select
			 */
			select: () => LocalizedString
		}
	}
	uiGraphql: {
		table: {
			/**
			 * Remove row?
			 */
			removeModalTitle: () => LocalizedString
			/**
			 * Edit
			 */
			editBtn: () => LocalizedString
			/**
			 * Remove
			 */
			removeBtn: () => LocalizedString
			/**
			 * Cancel
			 */
			cancelBtn: () => LocalizedString
			th: {
				/**
				 * filter
				 */
				filter: () => LocalizedString
				/**
				 * cancel
				 */
				cancel: () => LocalizedString
				/**
				 * No Sort
				 */
				noSort: () => LocalizedString
				/**
				 * ASC
				 */
				asc: () => LocalizedString
				/**
				 * DESC
				 */
				desc: () => LocalizedString
				/**
				 * Equals
				 */
				eq: () => LocalizedString
				/**
				 * Not Equals
				 */
				neq: () => LocalizedString
				/**
				 * Like
				 */
				lk: () => LocalizedString
				/**
				 * Not Like
				 */
				nlk: () => LocalizedString
				/**
				 * Greater Than
				 */
				gt: () => LocalizedString
				/**
				 * Greater Equals
				 */
				gte: () => LocalizedString
				/**
				 * Less Than
				 */
				lt: () => LocalizedString
				/**
				 * Less Equals
				 */
				lte: () => LocalizedString
				/**
				 * Is Null
				 */
				nil: () => LocalizedString
				/**
				 * Not Null
				 */
				nnil: () => LocalizedString
				/**
				 * In
				 */
				'in': () => LocalizedString
				/**
				 * Not In
				 */
				nin: () => LocalizedString
				/**
				 * Between
				 */
				bt: () => LocalizedString
				/**
				 * Not Between
				 */
				nbt: () => LocalizedString
				/**
				 * Filter..
				 */
				filterPlaceholder: () => LocalizedString
			}
			td: {
				/**
				 * save
				 */
				save: () => LocalizedString
				/**
				 * clear
				 */
				clear: () => LocalizedString
			}
		}
	}
	web: {
		/**
		 * Welcome to {name}
		 */
		welcome: (arg: { name: string }) => LocalizedString
		login: {
			/**
			 * Full-stack GraphQL development platform, powered by GraphQL Svelte and Reactor Java
			 */
			detail: () => LocalizedString
			/**
			 * Account
			 */
			account: () => LocalizedString
			/**
			 * Login
			 */
			login: () => LocalizedString
			/**
			 * Password
			 */
			password: () => LocalizedString
			/**
			 * Forgot password?
			 */
			forgot: () => LocalizedString
		}
		localeName: {
			/**
			 * English
			 */
			en: () => LocalizedString
			/**
			 * Chinese
			 */
			zh: () => LocalizedString
		}
		message: {
			/**
			 * Save success
			 */
			saveSuccess: () => LocalizedString
			/**
			 * Create success
			 */
			createSuccess: () => LocalizedString
			/**
			 * Remove success
			 */
			removeSuccess: () => LocalizedString
			/**
			 * Unbind success
			 */
			unbindSuccess: () => LocalizedString
			/**
			 * Request failed
			 */
			requestFailed: () => LocalizedString
			/**
			 * Save failed
			 */
			saveFailed: () => LocalizedString
			/**
			 * Create failed
			 */
			createFailed: () => LocalizedString
			/**
			 * Remove failed
			 */
			removeFailed: () => LocalizedString
			/**
			 * Unbind failed
			 */
			unbindFailed: () => LocalizedString
		}
		path: {
			/**
			 * Home
			 */
			home: () => LocalizedString
			/**
			 * Create {name}
			 */
			create: (arg: { name: string }) => LocalizedString
			/**
			 * Select {name}
			 */
			select: (arg: { name: string }) => LocalizedString
		}
		components: {
			search: {
				/**
				 * Search
				 */
				label: () => LocalizedString
			}
			themeSelect: {
				/**
				 * Theme
				 */
				btn: () => LocalizedString
				themes: {
					/**
					 * light
					 */
					light: () => LocalizedString
					/**
					 * dark
					 */
					dark: () => LocalizedString
					/**
					 * cupcake
					 */
					cupcake: () => LocalizedString
					/**
					 * bumblebee
					 */
					bumblebee: () => LocalizedString
					/**
					 * emerald
					 */
					emerald: () => LocalizedString
					/**
					 * corporate
					 */
					corporate: () => LocalizedString
					/**
					 * synthwave
					 */
					synthwave: () => LocalizedString
					/**
					 * retro
					 */
					retro: () => LocalizedString
					/**
					 * cyberpunk
					 */
					cyberpunk: () => LocalizedString
					/**
					 * valentine
					 */
					valentine: () => LocalizedString
					/**
					 * halloween
					 */
					halloween: () => LocalizedString
					/**
					 * garden
					 */
					garden: () => LocalizedString
					/**
					 * forest
					 */
					forest: () => LocalizedString
					/**
					 * aqua
					 */
					aqua: () => LocalizedString
					/**
					 * lofi
					 */
					lofi: () => LocalizedString
					/**
					 * pastel
					 */
					pastel: () => LocalizedString
					/**
					 * fantasy
					 */
					fantasy: () => LocalizedString
					/**
					 * wireframe
					 */
					wireframe: () => LocalizedString
					/**
					 * black
					 */
					black: () => LocalizedString
					/**
					 * luxury
					 */
					luxury: () => LocalizedString
					/**
					 * dracula
					 */
					dracula: () => LocalizedString
					/**
					 * cmyk
					 */
					cmyk: () => LocalizedString
					/**
					 * autumn
					 */
					autumn: () => LocalizedString
					/**
					 * business
					 */
					business: () => LocalizedString
					/**
					 * acid
					 */
					acid: () => LocalizedString
					/**
					 * lemonade
					 */
					lemonade: () => LocalizedString
					/**
					 * night
					 */
					night: () => LocalizedString
					/**
					 * coffee
					 */
					coffee: () => LocalizedString
					/**
					 * winter
					 */
					winter: () => LocalizedString
				}
			}
			table: {
				/**
				 * Remove row?
				 */
				removeModalTitle: () => LocalizedString
				/**
				 * Unbind row?
				 */
				unbindModalTitle: () => LocalizedString
				/**
				 * Edit
				 */
				editBtn: () => LocalizedString
				/**
				 * Remove
				 */
				removeBtn: () => LocalizedString
				/**
				 * Unbind
				 */
				unbindBtn: () => LocalizedString
				/**
				 * Select
				 */
				selectBtn: () => LocalizedString
			}
			userMenu: {
				/**
				 * Profile
				 */
				profile: () => LocalizedString
				/**
				 * Settings
				 */
				settings: () => LocalizedString
				/**
				 * Logout
				 */
				logout: () => LocalizedString
			}
		}
		errors: {
			/**
			 * Authentication failed
			 */
			'-40101': () => LocalizedString
		}
	}
}

export type Formatters = {}
