query Query_groupUserRelationList($id: StringExpression, $userRef: StringExpression, $user: UserExpression, $groupRef: StringExpression, $group: GroupExpression, $includeDeprecated: Boolean, $version: IntExpression, $realmId: IntExpression, $createUserId: StringExpression, $createTime: StringExpression, $updateUserId: StringExpression, $updateTime: StringExpression, $createGroupId: StringExpression, $orderBy: GroupUserRelationOrderBy, $groupBy: [String!], $not: Boolean, $cond: Conditional, $exs: [GroupUserRelationExpression], $first: Int, $last: Int, $offset: Int, $after: ID, $before: ID) {
  groupUserRelationList(id: $id userRef: $userRef user: $user groupRef: $groupRef group: $group includeDeprecated: $includeDeprecated version: $version realmId: $realmId createUserId: $createUserId createTime: $createTime updateUserId: $updateUserId updateTime: $updateTime createGroupId: $createGroupId orderBy: $orderBy groupBy: $groupBy not: $not cond: $cond exs: $exs first: $first last: $last offset: $offset after: $after before: $before)  {
    id
    userRef
    groupRef
    isDeprecated
    version
    realmId
    createUserId
    createTime
    updateUserId
    updateTime
    createGroupId
    user {
      id
      name
      description
    }
    group {
      id
      name
      description
    }
  }
}