query Query_currentUser($includeId: Boolean = false $includeName: Boolean = false $includeDescription: Boolean = false $includeLastName: Boolean = false $includeLogin: Boolean = false $includeEmail: Boolean = false $includePhones: Boolean = false $includeDisable: Boolean = false $includeIsDeprecated: Boolean = false $includeVersion: Boolean = false $includeRealmId: Boolean = false $includeCreateUserId: Boolean = false $includeCreateTime: Boolean = false $includeUpdateUserId: Boolean = false $includeUpdateTime: Boolean = false $includeCreateGroupId: Boolean = false $includeId: Boolean = false $includeName: Boolean = false $includeDescription: Boolean = false $includeLastName: Boolean = false $includeLogin: Boolean = false $includeEmail: Boolean = false $includeRealm: Boolean = false $includeGroupsAggregate: Boolean = false $includeRolesAggregate: Boolean = false ) {
  currentUser {
    id @include(if: $includeId)
    name @include(if: $includeName)
    description @include(if: $includeDescription)
    lastName @include(if: $includeLastName)
    login @include(if: $includeLogin)
    email @include(if: $includeEmail)
    phones @include(if: $includePhones)
    disable @include(if: $includeDisable)
    isDeprecated @include(if: $includeIsDeprecated)
    version @include(if: $includeVersion)
    realmId @include(if: $includeRealmId)
    createUserId @include(if: $includeCreateUserId)
    createTime @include(if: $includeCreateTime)
    updateUserId @include(if: $includeUpdateUserId)
    updateTime @include(if: $includeUpdateTime)
    createGroupId @include(if: $includeCreateGroupId)
      idCount @include(if: $includeIdCount)
      idMax @include(if: $includeIdMax)
      idMin @include(if: $includeIdMin)
      nameCount @include(if: $includeNameCount)
      nameMax @include(if: $includeNameMax)
      nameMin @include(if: $includeNameMin)
      descriptionCount @include(if: $includeDescriptionCount)
      descriptionMax @include(if: $includeDescriptionMax)
      descriptionMin @include(if: $includeDescriptionMin)
      lastNameCount @include(if: $includeLastNameCount)
      lastNameMax @include(if: $includeLastNameMax)
      lastNameMin @include(if: $includeLastNameMin)
      loginCount @include(if: $includeLoginCount)
      loginMax @include(if: $includeLoginMax)
      loginMin @include(if: $includeLoginMin)
      emailCount @include(if: $includeEmailCount)
      emailMax @include(if: $includeEmailMax)
      emailMin @include(if: $includeEmailMin)
    realm @include(if: $includeRealm) {
        idCount @include(if: $includeRealmIdCount)
        idMax @include(if: $includeRealmIdMax)
        idMin @include(if: $includeRealmIdMin)
        nameCount @include(if: $includeRealmNameCount)
        nameMax @include(if: $includeRealmNameMax)
        nameMin @include(if: $includeRealmNameMin)
        descriptionCount @include(if: $includeRealmDescriptionCount)
        descriptionMax @include(if: $includeRealmDescriptionMax)
        descriptionMin @include(if: $includeRealmDescriptionMin)
    }
    groupsAggregate @include(if: $includeGroupsAggregate) {
        idCount @include(if: $includeGroupsAggregateIdCount)
        idMax @include(if: $includeGroupsAggregateIdMax)
        idMin @include(if: $includeGroupsAggregateIdMin)
        nameCount @include(if: $includeGroupsAggregateNameCount)
        nameMax @include(if: $includeGroupsAggregateNameMax)
        nameMin @include(if: $includeGroupsAggregateNameMin)
        descriptionCount @include(if: $includeGroupsAggregateDescriptionCount)
        descriptionMax @include(if: $includeGroupsAggregateDescriptionMax)
        descriptionMin @include(if: $includeGroupsAggregateDescriptionMin)
        pathCount @include(if: $includeGroupsAggregatePathCount)
        pathMax @include(if: $includeGroupsAggregatePathMax)
        pathMin @include(if: $includeGroupsAggregatePathMin)
        parentIdCount @include(if: $includeGroupsAggregateParentIdCount)
        parentIdMax @include(if: $includeGroupsAggregateParentIdMax)
        parentIdMin @include(if: $includeGroupsAggregateParentIdMin)
        deepCount @include(if: $includeGroupsAggregateDeepCount)
        deepSum @include(if: $includeGroupsAggregateDeepSum)
        deepAvg @include(if: $includeGroupsAggregateDeepAvg)
        deepMax @include(if: $includeGroupsAggregateDeepMax)
        deepMin @include(if: $includeGroupsAggregateDeepMin)
    }
    rolesAggregate @include(if: $includeRolesAggregate) {
        idCount @include(if: $includeRolesAggregateIdCount)
        idMax @include(if: $includeRolesAggregateIdMax)
        idMin @include(if: $includeRolesAggregateIdMin)
        nameCount @include(if: $includeRolesAggregateNameCount)
        nameMax @include(if: $includeRolesAggregateNameMax)
        nameMin @include(if: $includeRolesAggregateNameMin)
        descriptionCount @include(if: $includeRolesAggregateDescriptionCount)
        descriptionMax @include(if: $includeRolesAggregateDescriptionMax)
        descriptionMin @include(if: $includeRolesAggregateDescriptionMin)
    }
  }
}