query Query_groupRoleRelation($id: StringExpression $roleRef: StringExpression $role: RoleExpression $groupRef: StringExpression $group: GroupExpression $includeDeprecated: Boolean $version: IntExpression $realmId: IntExpression $createUserId: StringExpression $createTime: StringExpression $updateUserId: StringExpression $updateTime: StringExpression $createGroupId: StringExpression $groupBy: [String!] $not: Boolean $cond: Conditional $exs: [GroupRoleRelationExpression] ) {
  groupRoleRelation(id: $id roleRef: $roleRef role: $role groupRef: $groupRef group: $group includeDeprecated: $includeDeprecated version: $version realmId: $realmId createUserId: $createUserId createTime: $createTime updateUserId: $updateUserId updateTime: $updateTime createGroupId: $createGroupId groupBy: $groupBy not: $not cond: $cond exs: $exs ) {
    id
    roleRef
    groupRef
    isDeprecated
    version
    realmId
    createUserId
    createTime
    updateUserId
    updateTime
    createGroupId
    role {
      id
      name
      description
    }
    group {
      id
      name
      description
    }
  }
}