query Query_permissionRoleRelation($id: StringExpression, $roleRef: StringExpression, $role: RoleExpression, $permissionRef: StringExpression, $permission: PermissionExpression, $includeDeprecated: Boolean, $version: IntExpression, $realmId: IntExpression, $createUserId: StringExpression, $createTime: StringExpression, $updateUserId: StringExpression, $updateTime: StringExpression, $createGroupId: StringExpression, $groupBy: [String!], $not: Boolean, $cond: Conditional, $exs: [PermissionRoleRelationExpression]) {
  permissionRoleRelation(id: $id roleRef: $roleRef role: $role permissionRef: $permissionRef permission: $permission includeDeprecated: $includeDeprecated version: $version realmId: $realmId createUserId: $createUserId createTime: $createTime updateUserId: $updateUserId updateTime: $updateTime createGroupId: $createGroupId groupBy: $groupBy not: $not cond: $cond exs: $exs)  {
    id
    roleRef
    permissionRef
    isDeprecated
    version
    realmId
    createUserId
    createTime
    updateUserId
    updateTime
    createGroupId
    role {
      id
      name
      description
    }
  }
}