query Query_policyList_agg($include_id: Boolean = false $include_policy: Boolean = false $include_v0: Boolean = false $include_v1: Boolean = false $include_v2: Boolean = false $include_v3: Boolean = false $include_v4: Boolean = false $include_v5: Boolean = false ) {
  policyList {
    id @include(if: $include_id)
    policy @include(if: $include_policy)
    v0 @include(if: $include_v0)
    v1 @include(if: $include_v1)
    v2 @include(if: $include_v2)
    v3 @include(if: $include_v3)
    v4 @include(if: $include_v4)
    v5 @include(if: $include_v5)
  }
}