query Query_groupRoleRelation_group($groupRoleRelation_id: StringExpression $id: StringExpression $name: StringExpression $description: StringExpression $path: StringExpression $deep: IntExpression $parentId: StringExpression $parent: GroupExpression $subGroups: GroupExpression $users: UserExpression $roles: RoleExpression $realm: RealmExpression $includeDeprecated: Boolean $version: IntExpression $realmId: IntExpression $createUserId: StringExpression $createTime: StringExpression $updateUserId: StringExpression $updateTime: StringExpression $createGroupId: StringExpression $groupUserRelation: GroupUserRelationExpression $groupRoleRelation: GroupRoleRelationExpression $groupBy: [String!] ) {
  groupRoleRelation(id: $groupRoleRelation_id ) {
    id
    roleRef
    groupRef
    isDeprecated
    version
    realmId
    createUserId
    createTime
    updateUserId
    updateTime
    createGroupId
    group(id: $id name: $name description: $description path: $path deep: $deep parentId: $parentId parent: $parent subGroups: $subGroups users: $users roles: $roles realm: $realm includeDeprecated: $includeDeprecated version: $version realmId: $realmId createUserId: $createUserId createTime: $createTime updateUserId: $updateUserId updateTime: $updateTime createGroupId: $createGroupId groupUserRelation: $groupUserRelation groupRoleRelation: $groupRoleRelation groupBy: $groupBy ) {
      id
      name
      description
      path
      deep
      parentId
      isDeprecated
      version
      realmId
      createUserId
      createTime
      updateUserId
      updateTime
      createGroupId
      parent {
        id
        name
        description
      }
      subGroups {
        id
        name
        description
      }
      users {
        id
        name
        description
      }
      roles {
        id
        name
        description
      }
      realm {
        name
        description
      }
    }
  }
}