query Query_fileUserRelationList($id: StringExpression, $userRef: StringExpression, $user: UserExpression, $fileRef: StringExpression, $file: FileExpression, $includeDeprecated: Boolean, $version: IntExpression, $realmId: IntExpression, $createUserId: StringExpression, $createTime: StringExpression, $updateUserId: StringExpression, $updateTime: StringExpression, $createGroupId: StringExpression, $orderBy: FileUserRelationOrderBy, $groupBy: [String!], $not: Boolean, $cond: Conditional, $exs: [FileUserRelationExpression], $first: Int, $last: Int, $offset: Int, $after: ID, $before: ID) {
  fileUserRelationList(id: $id userRef: $userRef user: $user fileRef: $fileRef file: $file includeDeprecated: $includeDeprecated version: $version realmId: $realmId createUserId: $createUserId createTime: $createTime updateUserId: $updateUserId updateTime: $updateTime createGroupId: $createGroupId orderBy: $orderBy groupBy: $groupBy not: $not cond: $cond exs: $exs first: $first last: $last offset: $offset after: $after before: $before)  {
    id
    userRef
    fileRef
    isDeprecated
    version
    realmId
    createUserId
    createTime
    updateUserId
    updateTime
    createGroupId
    user {
      id
      name
      description
    }
  }
}