query Query_userPhonesRelation($id: StringExpression $userRef: StringExpression $user: UserExpression $phonesRef: StringExpression $includeDeprecated: Boolean $version: IntExpression $realmId: IntExpression $createUserId: StringExpression $createTime: StringExpression $updateUserId: StringExpression $updateTime: StringExpression $createGroupId: StringExpression $groupBy: [String!] $not: Boolean $cond: Conditional $exs: [UserPhonesRelationExpression] $includeId: Boolean = false $includeUserRef: Boolean = false $includePhonesRef: Boolean = false $includeIsDeprecated: Boolean = false $includeVersion: Boolean = false $includeRealmId: Boolean = false $includeCreateUserId: Boolean = false $includeCreateTime: Boolean = false $includeUpdateUserId: Boolean = false $includeUpdateTime: Boolean = false $includeCreateGroupId: Boolean = false $includeId: Boolean = false $includeUser: Boolean = false ) {
  userPhonesRelation(id: $iduserRef: $userRefuser: $userphonesRef: $phonesRefincludeDeprecated: $includeDeprecatedversion: $versionrealmId: $realmIdcreateUserId: $createUserIdcreateTime: $createTimeupdateUserId: $updateUserIdupdateTime: $updateTimecreateGroupId: $createGroupIdgroupBy: $groupBynot: $notcond: $condexs: $exs)  {
    id @include(if: $includeId)
    userRef @include(if: $includeUserRef)
    phonesRef @include(if: $includePhonesRef)
    isDeprecated @include(if: $includeIsDeprecated)
    version @include(if: $includeVersion)
    realmId @include(if: $includeRealmId)
    createUserId @include(if: $includeCreateUserId)
    createTime @include(if: $includeCreateTime)
    updateUserId @include(if: $includeUpdateUserId)
    updateTime @include(if: $includeUpdateTime)
    createGroupId @include(if: $includeCreateGroupId)
      idCount @include(if: $includeIdCount)
      idMax @include(if: $includeIdMax)
      idMin @include(if: $includeIdMin)
    user @include(if: $includeUser) {
        idCount @include(if: $includeUserIdCount)
        idMax @include(if: $includeUserIdMax)
        idMin @include(if: $includeUserIdMin)
        nameCount @include(if: $includeUserNameCount)
        nameMax @include(if: $includeUserNameMax)
        nameMin @include(if: $includeUserNameMin)
        descriptionCount @include(if: $includeUserDescriptionCount)
        descriptionMax @include(if: $includeUserDescriptionMax)
        descriptionMin @include(if: $includeUserDescriptionMin)
        lastNameCount @include(if: $includeUserLastNameCount)
        lastNameMax @include(if: $includeUserLastNameMax)
        lastNameMin @include(if: $includeUserLastNameMin)
        loginCount @include(if: $includeUserLoginCount)
        loginMax @include(if: $includeUserLoginMax)
        loginMin @include(if: $includeUserLoginMin)
        saltCount @include(if: $includeUserSaltCount)
        saltMax @include(if: $includeUserSaltMax)
        saltMin @include(if: $includeUserSaltMin)
        hashCount @include(if: $includeUserHashCount)
        hashMax @include(if: $includeUserHashMax)
        hashMin @include(if: $includeUserHashMin)
        emailCount @include(if: $includeUserEmailCount)
        emailMax @include(if: $includeUserEmailMax)
        emailMin @include(if: $includeUserEmailMin)
    }
  }
}