query Query_userPhonesRelation($id: StringExpression $userRef: StringExpression $user: UserExpression $phonesRef: StringExpression $includeDeprecated: Boolean $version: IntExpression $realmId: IntExpression $createUserId: StringExpression $createTime: StringExpression $updateUserId: StringExpression $updateTime: StringExpression $createGroupId: StringExpression $groupBy: [String!] $not: Boolean $cond: Conditional $exs: [UserPhonesRelationExpression] $include_id: Boolean = true $include_userRef: Boolean = true $include_phonesRef: Boolean = true $include_isDeprecated: Boolean = true $include_version: Boolean = true $include_realmId: Boolean = true $include_createUserId: Boolean = true $include_createTime: Boolean = true $include_updateUserId: Boolean = true $include_updateTime: Boolean = true $include_createGroupId: Boolean = true $include_user: Boolean = true ) {
  userPhonesRelation(id: $id userRef: $userRef user: $user phonesRef: $phonesRef includeDeprecated: $includeDeprecated version: $version realmId: $realmId createUserId: $createUserId createTime: $createTime updateUserId: $updateUserId updateTime: $updateTime createGroupId: $createGroupId groupBy: $groupBy not: $not cond: $cond exs: $exs ) {
    id @include(if: $include_id)
    userRef @include(if: $include_userRef)
    phonesRef @include(if: $include_phonesRef)
    isDeprecated @include(if: $include_isDeprecated)
    version @include(if: $include_version)
    realmId @include(if: $include_realmId)
    createUserId @include(if: $include_createUserId)
    createTime @include(if: $include_createTime)
    updateUserId @include(if: $include_updateUserId)
    updateTime @include(if: $include_updateTime)
    createGroupId @include(if: $include_createGroupId)
    user @include(if: $include_user) {
      id
      name
      description
    }
  }
}