query Query_current_agg($include_id: Boolean = false $include_name: Boolean = false $include_lastName: Boolean = false $include_login: Boolean = false $include_realmId: Boolean = false $include_groups: Boolean = false $include_roles: Boolean = false ) {
  current {
    id @include(if: $include_id)
    name @include(if: $include_name)
    lastName @include(if: $include_lastName)
    login @include(if: $include_login)
    realmId @include(if: $include_realmId)
    groups @include(if: $include_groups)
    roles @include(if: $include_roles)
  }
}